README.md
The previous example didn't compile, so I added the missing imports and renamed the one referring to `github.com/gianarb/testcontainers`.
Signed-off-by: Sune Keller <sune.keller@gmail.com>
=> Add necessary imports in main.go example

README.md, docker.go, docker_test.go
As suggested by @vdemeester on Slack. Thanks!
=> Terminate accept testing.T to better handle failure.

docker.go
Other than pulling an image to be sure that it exists this PR introduced
a mechanism to download images from a private repository.
Fixed #2 
@sirlatrom what do you think?
=> Pull image and accept registry out

docker.go, docker_test.go
If an image did not exist on the system, the docker image command would
not finish before all the test commands would run.  This lead to various
nil pointer exceptions in the tests.
Once the entire response from the image pull is read, then the container
is now on the system.
=> fix(docker): read entire image pull response to guarantee image download

docker.go
As requested here #20 this PR implements a flow to only create
containers. The container has a new `Start` function to run it when you
wish.
@mraerino
```go
c, err := CreateContainer(ctx, "nginx", input)
....
....
err := c.Run(ctx)
.....
.....
```
Fixed #20
=> Implemented a create-only function

docker.go
This is a suggestion for improved handling of the docker client.
It seems reasonable to reuse the client.
=> Refactor docker handling to create client once for a context

README.md, docker.go, docker_test.go
Hello everyone.
I started this project few months ago but right now using it I
discovered that something needs to change.
So right now I redesigned the function, deprecating the old one.
The new core functions have the same name used from the java
implementation:
* `GetContainerIpAddress` returns the ip of the docker gateway. I decided to go
with this implementation because it should be the most "reusable"
approach right now. We will need to work and port a lot of the logics
the java project learn during all these years.
* `GetMappedPort` returns the port opened in the host.
Combining this two functions together you can reach a particular port in
your container. These two functions should be used as part of the Wait
interface.
For example now it works with docker-in-docker, docker in …
=> BIG CLEANUP AND REFACTORING

container.go, docker.go, docker_test.go, generic.go, go.mod, legacy.go, legacy_test.go, reaper.go
The right name for the package should be testcontainers-go not
testcontainer-go. The `s` is important for consistency with the other
libraries across languages.
This is BC break and to fix this you need to change the import in your
applications.
=> BC BREAk move to testcontainers-go

.travis.yml, README.md
- Fixes broken link to Travis CI job via badge
- Avoids running the default install script (`go get -t -v ./...`) which is unnecessary when using Go modules
=> Fixes to Travis configuration

container.go, docker.go, docker_test.go
Close #52
Now the Container exposes a method called `GetContainerID`. It exposes
the container id provided by the provider (docker atm).
@m4x-h4xx how does it sounds? Thanks
=> Exposed containerID with the function GetContainerID

container.go, docker.go, docker_test.go, go.mod, go.sum, wait/log.go, wait/wait.go
This makes it possible to wait for specific log output.
For example it's useful for MySQL test containers, which has the
port and host available long before it's actually ready to
accept connections.
example usage:
```go
WaitingFor: wait.ForLog("port: 3306  MySQL Community Server - GPL"),
```
Solves #54
=> Implement a Log wait strategy

docker.go, go.mod, go.sum
The docker client can negotiate the right version of the API based on
the docker daemon but there is a specific function to call. We was not
calling it.
Now it should be smart enough to figure out which version of the API to
use.
Fixed #61
=> Fixed API Version Negotiation

container.go, docker.go, reaper.go
Change the name and the visibility of the skip Reaper flag included
in the ContainerRequest structure. Now is possible disable the Reaper
creation from during the container creation request.
=> Change isReaper with SkipReaper

docker_test.go, wait/multi.go
reference #37 
This add a new wait strategy called MultiStrategy that allows waiting for multiple conditions as proposed in #37 
The feature can be used like this
```go
ctx := context.Background()
req := ContainerRequest{
Image:        "mysql:latest",
ExposedPorts: []string{"3306/tcp", "33060/tcp"},
Env: map[string]string{
"MYSQL_ROOT_PASSWORD": "password",
"MYSQL_DATABASE":      "database",
},
WaitingFor: wait.ForAll(
wait.ForLog("port: 3306  MySQL Community Server - GPL"),
wait.ForListeningPort("3306/tcp"),
),
}
```
=> Multiple wait strategy

container.go, docker.go, docker_test.go, generic.go, network.go
This PR adds support for client code to be able to configure networks a container is connected to, which nowadays is impossible as the default network configuration when invoking the Docker client to create and run a container is passed as `nil`.
For that reason, a Network request object is needed, alongside the methods to create/remove/get a network from the Docker client. Those methods have been defined at a new NetworkProvider interface.
As a container could have multiple aliases when connecting to a network, we are also adding that support: when adding a network it's possible to set the aliases for the container in that network.
Client code would eventually like to connect a container run by this library to a specific set of networks, and this library currently disallows it always …
=> (#73) Support attaching containers to different networks than bridge

docker.go, docker_test.go
The original purpose of this PR was to expose the inspectContainer method on the DockerContainer model. In that process, I found that there is a local cache (raw) that allowed to invoke the public methods that internally use `inspectContainer` (Host, Ports...) even after terminating the container, because that local cache was not removed.
For that reason this PR adds that ability to remove the local cache (raw and sessionID) when terminating a container.
Nowadays the API allows to invoke another container method (Host, Ports...) after the container is terminated, and the internal cached state would satisfy the request even when the container is not existing anymore at Docker client level. We are removing the cached values so that we receive the response directly from the container …
=> (#93) Reset internal state after container.Terminate(), and expose InspectContainer

go.mod, go.sum, wait/log.go, wait/log_test.go
This is related to the work @giorgioazzinnaro is doing here
https://github.com/testcontainers/testcontainers-go/pull/98 .
Now you can declare how many times a log line should appear before
having the container declared as ready.
=> Added occurrence for the WaitLogStrategy

README.md, container.go, container_test.go, docker.go, testresources/echo.Dockerfile
resolves #110
Added a ContextArchive attribute to the FromDockerfile struct, this
allows a user to pass in an io.Reader as the Docker build context.
A user will now be allowed to create a dynamic build in code and send it
to the build.
Added test cases for both scenarios (using a local filepath and an
archive).  Added example to README.
=> #110 feature: Context as io.Reader

README.md
Added formatting to Go code block in README. 😎
=> fix: Add Go formatting to README code block

.travis.yml
It adds test info to Travis logs when running Go tests.
Travis logs are not good to debug/trace what happens when a test fails. Here we find a manner to check what is the status of each test method, with a summary at the end of the log (see screenshot)
=> Add more info about failing test on Travis

container.go, docker.go, docker_test.go, go.mod, go.sum, testresources/hello.sh
I wanted to run an [ETCD](https://etcd.io/) cluster using testcontainers-go.
In order to simulate ETCD node crash and recovery, I needed my data to be kept after a terminate of the container so that the new container can use it.
To do this, I used a bind mount so that the data stays on my host.
However, at start-up, ETCD does some Fsync on the data files which, I don't know why, is not working on my environment (Docker for Windows 10).
The alternative I found is to use a Docker volume and mount it into the ETCD container.
=> Support volume mounts

container.go, container_test.go, docker.go, reaper.go
setting any container besides a reaper to not auto-remove when creating
fixes #118 
Now when creating containers, allowing a user to set the `AutoRemove` parameter in the container request, if this is done, then the container will be removed upon stopping.  This is by default set to `false` for user-created containers, but when running a reaper container, this will set it to `true` (reaper cleans up containers, but nothing cleans up reaper so we have to make sure it auto-removes)
=> feat: allow viewing of logs from stopped container

container.go, docker.go, docker_test.go
Hello everyone!
I debugged this issue and founded out that:
When I start container with network: []string{"host"} docker inspect <id> returns in HostConfig.Network = 'default'
Add property in ContainerRequest struct
=> #138 Add NetworkMode host 

container.go, docker.go, docker_test.go
When testing against database containers, most of the time, those containers are thrown away after the tests are finished and we do not care about the data. Docker [provides](https://docs.docker.com/storage/tmpfs/) `tmpfs` mounts that work well for such use cases - the data is only written in memory and not to disk, which in turn allows for tests to run faster.
testcontainers-java [has](https://github.com/testcontainers/testcontainers-java/blob/3cb33792328e49b5ab8d78f747a256d65593dd64/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L1449) an option to configure tmpfs and pass it to docker client too.
This change adds such option for the go library.
I do not know how to best demonstrate in a test that it makes an impact when used.
My local results on a linux computer …
=> Add ability to configure tmpfs for a container

wait/sql.go
#121
A simplified sql db waiting strategy without adding any new dependency to the library. An example usage for a postgres container:
```go
var env = map[string]string{
"POSTGRES_PASSWORD": "password",
"POSTGRES_USER":     "postgres",
"POSTGRES_DB":       "service",
}
var port = "5432/tcp"
dbURL := func(port nat.Port) string {
return fmt.Sprintf("postgres://postgres:password@localhost:%s/service?sslmode=disable", port.Port())
}
req := testcontainers.GenericContainerRequest{
ContainerRequest: testcontainers.ContainerRequest{
Image:        "postgres:latest",
ExposedPorts: []string{port},
Cmd:          []string{"postgres", "-c", "fsync=off"},
Env:          env,
WaitingFor:   wait.ForSQL(nat.Port(port), "postgres", dbURL).Timeout(time.Second*5),
},
Started: true,
}
container, err := …
```
=> Adding a wait for sql strategy

wait/host_port.go
When DialWithContext fails we were not checking for error.
Fixed #139
=> Fix panic in wait host port

reaper.go
Hello everybody!
In this version reaper fixed 
https://quay.io/repository/testcontainers/ryuk/manifest/sha256:bb5a635cac4bd96c93cc476969ce11dc56436238ec7cd028d0524462f4739dd9?tab=vulnerabilities
=> #145 Update default reaper images to 0.2.3

.travis.yml
This PR bumps the Go version in travis ci to 1.14.x
=> Bump travis-ci Go to 1.14.x

container.go, docker.go
It is sometimes useful when running integration test scenarios to force Testcontainers Go to always pull the image. For instance, when test cases are relying on the image with the latest tag and latest tag is always moved when the new image is pushed to the registry.
This PR adds a property to the ContainerRequest structure that instructs CreateContainer to always pull the image even if it already exists when the property in question is set to true. Otherwise, behaviour does not change.
=> Force testcontainers to always pull images when creating container

docker.go, docker_test.go, generic.go, network_test.go, reaper.go
Reusing existing reaper for subsequent container/network create calls. This ensures that any networks, created as part of the test case will be removed.
Fixes #173
=> #173: Reaper reuse

wait/http_test.go
Based on the issue #183 I decided to add this example to explain that by
default wait.HTTP looks for port `80/tcp` but you can override it.
=> docs: add example for wait http

compose.go
It throws error instead of raising panic
It's better raise the error and let the client code to handle it
=> chore: do not raise panic in compose, use exec error instead so the client code can handle it

container.go, docker.go, docker_test.go, go.mod, testing.go, testing_test.go
I implement a new function to use as testing utility.
It skips the test if the provider is not reachable or well provisioned.
You have to declare it in your test, so if you depend on Docker and you
know you need it just keep doing as you are doing today.
In my use case we use testcontainers only for some particular tests, and
I do not like the idea to mark the testsuite as `FAILED` if a colleague
does not have Docker enabled in their local environment. Worst case if
something has to fail CI/CD will tell the truth.
=> feat: implement skip utility function for testing

container_test.go, reaper.go
Fixes #192 by guarding access to shared reaper with a mutex making it thread safe.
=> fixes #192 - guard access to reaper with a mutex

container.go, docker.go, docker_test.go
Closes #208
Signed-off-by: Alex Klinkert <alex@klinkert.io>
=> Add pass-through for entrypoint to ContainerRequest

container_test.go
We have to do our best to keep the number of images overall the test
suite as small as possible, to speed up the testsuite itself.
=> use nginx when possible when writing test

docker_test.go
For a couple of tests the wait strategy where not properly set.
I am trying to figure out if it makes the test suite to pass
=> wait strategy where not properly set

compose_test.go, testresources/docker-compose-complex.yml
It uses Nginx instead of portal, reducing the size from < 2Gb to tens of Mb
Both CI builds and local execution of tests will be faster
- Relates #213
=> chore: simplify complex docker-compose file

go.mod, go.sum
github.com/docker/distribution should be an indirect dependency.
run by `go mod tidy`
=> github.com/docker/distribution should be an indirect dependency

.travis.yml
It enables Travis to run multiple versions of Go
It will allow us to detect potential errors earlier
=> chore: run travis in multiple versions of Go

go.mod
This PR is for updating docker/docker package in go.mod.
`v0.7.3` is too old, so some secury check fails. (In our team, we use yamory (https://yamory.io/) (japanese))
=> update docker/docker package version

.gitignore, container.go, docker.go, docker_test.go, docs/features/copy_file.md
Missing tests and update in documentation.
Just a draft to validate if it looks good so far
=> Added support for copy file to container

docker.go, docker_test.go, reaper.go
This commit resolves the issue of inability to run the tests in the Docker environment with disabled "bridge" network.
The CreateContainer or CreateNetwork function will check if bridge network exists and if does not it creates a reaper_default network and ensure that container is attached to the reaper_default network.
=> Issue #243: Introducing the default network in case "bridge" is disabled

wait/http.go, wait/log.go, wait/sql.go, wait/wait.go
=> Poll interval

go.mod, go.sum
This PR replaces #245
And it fixes: #238
It removes the `replace` for docker/docker and it should not be a
requirement anymore.
=> bump docker/docker to v19.03.13

.github/workflows/ci.yml
Hello everyone!
In this MR I add github action. There are the same steps as in .travis.yml
=> feature: move to github action #242

README.md
It adds the GH badge
To communicate project status on CI
Remove travis integration?
=> chore: add GH action badge

docs/features/docker_compose.md
I found this super nit typo in docs
=> docs: fix variable type

compose.go
To make sure we do not leak containers when destroying a compose
=> chore: support removing orphan containers when destroying the compose

docker.go
Right now when something is wrong with pulling image, for example:
```
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
there is no indication that any action is happening. This log will additional debug information if something is wrong.
=> feat: add logging on image pull error

docker.go, go.mod, go.sum
This should fix #273, as this changes the version of the Docker dependency to 20.10.3.
The backward-incompatible parameter in the call to `ContainerCreate` is the platform, which is for images with different platforms (e.g. `linux/amd64` vs `linux/arm64`). If not specified, this ends up defaulting to the host platform from what I understand, and is only relevant for machines that are multi-platform capable. At any rate, this is an option we can expose as part of this PR, but I think the use-case is so niche, it might not be worth the effort, as testing that might prove difficult.
=> Update Docker dependency to Docker 20.10.3.

docker.go, wait/host_port.go, wait/http.go, wait/sql.go
Docker engine 20.10.3 has changed the way ports are returned from InspectContainer. The array is not always populated which triggers a panic.
Related to #294
=> Wait strategies must poll ports

docker.go
This fixes the issue #319.
When `Reaper` is used, the `DockerContainer.Terminate` and `DockerNetwork.Remove` functions should close the spawned go routine by `Reaper.Connect`.
=> close reaper go routines on `DockerContainer.Terminate` & `DockerNetwork.Remove`

docker.go, logconsumer_test.go
It stores raw information of a container (JSON format) in the Docker Container struct
Caused by #271, where we are getting the state of a container from the Docker client, but we did not add the field
=> fix: store raw information of a container

README.md
This is a minor improvement.  For example, if `testcontainers.GenericContainer` fails for any reason, it doesn't carry on and generate a nil pointer exception.
=> Change t.Error() to t.Fatal() in example

network_test.go, wait/http.go, wait/http_test.go
I also updated the test code to check for this specific issue. If you run the updated tests against the current `master` it will fail due to the bug that this addresses.
Closes #338
Closes #341
=> fix: cache http wait request body

compose.go, compose_test.go
We are providing a simple API to wait for services by service name, only
It will allow consumer to wait on a service without having to pass a port.
=> chore: add WaitForService method to compose

docker.go, docker_test.go
When I try to use docker in docker through the share UNIX socket on GitHub Action, the IP address in the Host Port wait strategy is incorrect.
I found when we trying to get the target host, the default network may not initialize: https://github.com/testcontainers/testcontainers-go/blob/59631817dd3515c7c97e3c84e0201eaa746d6773/docker.go#L895
=> Fix default network is not initialize when get gateway ip

container.go, docker.go, docker_test.go
While working on a k3s-container I needed to extract the kubeconfig from the running container and discovered that there is no CopyFileFromContainer available.
Added CopyFileFromContainer to DockerContainer.
Added Unit-test for the new Function.
=> Added CopyFileFromContainer to DockerContainer

docs/index.md
It creates the section for companies using the project, starting with Elastic
=> docs: add users of testcontainers-go

docker.go, docker_test.go
It is currently not possible to mount a local path to multiple paths in
the container.
BindMounts are currently stored in a `map[string]string` with the
hostPath being the key and containerPath as the value.
This prevents me from mounting a hostPath to multiple paths in the
container. Using a map actually makes sense because it is not possible
to mount multiple host paths to the same path in the container. Key and
value are just swapped. Same with VolumeMounts.
Yes, i know, this a huge breaking change and probably not the best fix.
We could also add an additional map like `BindMountsFixed` and deprecate
the old one. But as this library is still in version 0, a breaking
change might not be a problem?
=> Swap incorrect key and value of BindMounts and VolumeMounts

wait/exec.go, wait/exec_test.go
The work is heavily based on `wait.HttpStrategy`.
This is especially useful with `localstack/localstack` as the readiness of the HTTP API doesn't actually mean anything, you can still get HTTP 500 on request while checking with some kind of client (or a script) with complete logic can give one confident result.
=> Add wait.ExecStrategy to wait on cmd exec in a container

compose.go, compose_test.go, testresources/docker-compose-volume.yml
Following the discussion [here](https://github.com/testcontainers/testcontainers-go/pull/380#discussion_r749166320) this PR adds removal of volumes by default to the compose `Down()` method.
=> feat: additionally remove volumes by default on compose down

docker.go, logconsumer_test.go
As best I can tell, a direct commit to the master branch [bc6fdab](https://github.com/testcontainers/testcontainers-go/commit/bc6fdab92dd3c623ad6654bf301b1a659efeb50e) made an attempt at recovering the log-position of a container in the scenario of a closed connection. The logic is all sound, but I think the string used to detect a closed-connection is not (has never been) correct.
The source of the error is `internal/poll`'s `errNetClosing`. It's error string has been set as: `"use of closed network connection"` since the beginning (5 years ago). Of course it would be much cleaner to detect a connection-closed error without string-matching but as stated in the mentioned commit, the error type for this was only exported by the `net` package in go 1.16
=> Bugfix: log-consumer go-routine should recover from closed-connection

compose.go, compose_test.go, testresources/docker-compose-postgres.yml
Fixes #391 
I added a new docker-compose file with postgres image. Hope thats okay.
Without this fix, services field keeps map for only the last docker-compose file passed. But there could be service that are not overridden in the last file, and it should keep those values in the map.
=> #391: remember service map from all docker compose files

container.go, container_test.go, docker.go, docker_mounts.go, docker_test.go, mounts.go, mounts_test.go, reaper.go
- introduce dedicated type for mounts
- introduce generic and Docker specific types for different mount sources (bind, volume, tmpfs)
- introduce convenience methods to support common mount scenarios
- add validation to avoid duplicate mount targets
The current map based data structure is somehow confusing. This change avoids confusion by introducing dedicated types for all components to get help by IDEs and the compiler.
```go
req := ContainerRequest {
//...
BindMounts: map[string]string{
"/var/run/docker.sock": "/var/run/docker.sock",
}
//...
}
```
becomes:
```go
req := ContainerRequest {
//...
Mounts: Mounts(BindMount("/var/run/docker.sock", "/var/run/docker.sock")),
//...
}
```
```go
req := ContainerRequest {
//...
BindMounts: map[string]string {
// container path : host path …
```
=> Replace ContainerRequest.BindMounts and ContainerRequest.VolumeMounts with ContainerRequest.Mounts as dedicated type

container.go, logger.go
using an interface instead of the std lib struct type for the logger allows for more flexibility with users setting custom logger
=> added interface for logger

compose.go, compose_test.go, container.go, docker.go, docker_test.go, generic.go, logconsumer_test.go, logger.go
Follow up PR for #385 to configure logging instance per container.
To achieve this, it adds variadic options to multiple constructors to propagate the logger finally to the `Container` instance.
- `NewLocalDockerCompose(...)`
- `GetProvider(...)`
- `NewDockerProvider(...)`
The idea is that there's a `GenericProviderOption` interface to act exactly as the name intends: all providers should support these options. Options only supported by Docker can be added as `DockerProviderOption`.
There's a converter function `Generic2DockerOptions` to wrap `GenericProviderOption` as `DockerProviderOption` for `NewDockerProvider`.
Everywhere a logger option can be applied the default is the global logger which can be overridden.
The `WithLogger` function takes a `Logger` and returns a option instance …
=> Logger per container instance

container.go, docker.go, docker_test.go
I have a use case where I need to set the `ulimits` for a container
```yaml
version: "3"
services:
elasticsearch:
container_name: elasticsearch
image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
ports:
- '9200:9200'
ulimits:
memlock:
soft: -1
hard: -1
nofile:
soft: 65536
hard: 65536
environment:
- xpack.security.enabled=false
- discovery.type=single-node
- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
healthcheck:
test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
interval: 30s
timeout: 30s
retries: 3
```
I see we don't expose that configuration so it's impossible to achieve the same thing with testcontainers
Expose HostConfig Resources via ContainerRequest
=> Expose HostConfig Resources via ContainerRequest

docs/quickstart/gotest.md
This allows users to easily copy and paste the test case example.
=> add import statements to quick start

docker.go
This is to prevent these intermediate containers from piling up when images are getting built from a Dockerfile on a local machine.
Related documentation: https://docs.docker.com/engine/reference/commandline/image_build/#options
=> Remove intermediate containers when building from Dockerfile

container.go, docker.go, docker_test.go
this is especially useful in tests, since we do not
need to create a file for testing,
we can just generate it in memory and then
copy it to a container directly
=> expose CopyToContainer so file can be created only in memory

.github/workflows/ci.yml, Pipfile, go.mod, go.sum, requirements.txt, tools/tools.go
It puts gotestsum as a dependency tool, so that the installation is managed by Go dependency manager.
It also pins jinja2 after recent breaking changes (see https://github.com/mkdocs/mkdocs/issues/2799 and what the Java folks have done in https://github.com/testcontainers/testcontainers-java/pull/5186)
See https://go.dev/doc/go-get-install-deprecation
> Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
>
> In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.
Reads about `tools.go`:
- https://marcofranssen.nl/manage-go-tools-via-go-modules
- https://play-with-go.dev/tools-as-dependencies_go115_en/
- …
=> fix: use 1.18 format to install dependencies

.github/workflows/ci.yml
It adds Go 1.16 and 1.17 to the CI matrix to run the tests
Go versions coverage
Should we retire 1.14 (or any other) from the matrix? Which versions should we be compatible with?
=> chore(ci): run tests for more recent Go versions

compose.go
In compose V2, the container name is `<compose name>-<service name>` instead of `<compose name>_<service name>`
The code do referrer it by having `composeV2ContainerName` along `containerName`, but the  `composeV2ContainerName` is constructed by replacing any `_` from `containerName` with `-`. This is a problem because the service may have `_` in its name and it will cause an incorrect container name that won't be found.
=> Fix compose v2 wait strategy

compose.go
Even though client version negotiation has been implemented for vanilla docker [here](https://github.com/testcontainers/testcontainers-go/issues/61), it hasn't been implemented for Docker Compose. I ran into the issue while setting up some integration tests and negotiating the client version fixed the issue and allowed me to make progress.
=> Negotiate client version for docker compose

container.go, docker.go
The code-way of specifying `--add-hosts` on the Docker command-line.
E.g.
```go
var extraHosts = []string{
"subdomain.localhost:127.0.0.1",
}
```
Useful in test scenario's where dynamic domain names are used.
=> Add extra hosts to the container request

container.go, docker.go, docker_test.go, logconsumer_test.go, wait/exec.go, wait/exec_test.go, wait/exit_test.go, wait/host_port.go, wait/log_test.go, wait/wait.go
This should allow the user to read the logs of the command execution. I've tested this quickly locally and it seems to work as expected.
Pushing this so I can get some CI feedback.
I believe this is similar to what was asked for in #126
=> Return a Reader from the Exec function

compose.go, compose_test.go
There was no interface for getting the output of the compose command after calling `Invoke`.
Because you are allowing running any command (using `WithCommand`), it is essential that the user will be able to get the output of the command.
I saw that you're already implemented `capturingPassThroughWriter` that copies the output to a buffer as well as stdout\stderr, so I used it and just added the output to the returning struct.
=> Docker compose: Add the output of the command to the returning struct

docker.go, network.go, network_test.go
I've added a new field for `NetworkRequest`
closes #299
=> feat: add IPAM configs to `NetworkRequest`

go.mod, go.sum
There is a problem with containerd versions lower than v1.5.13 as reported here [CVE-2022-31030](https://github.com/advisories/GHSA-5ffw-gxpp-mxpf).
I'm opening this pull request just for bumping lib version and fixing this problem.
=> chore(deps): bump containerd version to v1.5.13

logconsumer_test.go
Closes #411 
Simple retry with time limit added into test.
Maybe move retry into `Endpoint` function? Or it will be a breaking change?
=> fix: temp fix of flaky test

.github/workflows/ci.yml, docker_test.go, scripts/check_environment.sh
close https://github.com/testcontainers/testcontainers-go/issues/158
=> check that environment is clean

docs/examples/redis.md
`_ "github.com/jackc/pgx/v4/stdlib"` seems like CockroachDB related import.
=> Remove unused import in redis example

docker.go, logconsumer_test.go
Closes #365 
`DockerContainer` func `Logs` now strips header for each line.
This fix cannot be used with TTY mode.
Why strip header?  Due to setting TTY breaks some tests (ex: Test_ShouldRecognizeLogTypes) ...
=> fix: strip stream headers from logs

.github/dependabot.yml
It adds the new e2e module to dependabot's configuration file
Because otherwise, the PRs from dependabot could fail in Go 1.18
=> chore: tell dependabot about the new module

docker.go, docker_test.go, reaper.go
Now the environment variable `TESTCONTAINERS_RYUK_CONTAINER_PRIVILEGED` is read only once in the `configureTC` function that reads the `.testcontainers.properties` file and accesses the environment variable.
=> refactor: read RYUK_CONTAINER_PRIVILEGED once

.github/workflows/ci-podman.yml, .github/workflows/ci.yml, e2e/Makefile
It updates the pipeline for Podman with the recent changes about using a Makefile for running the tests, and a shell script checking there is no containers at the end of the test execution.
Besides, it's adding `go mod` commands to standardize the mod file for each Go version that is supported
Using Make creates a consistent manner of running the tests
The `go mod` commands should fix the Podman pipeline
=> chore(ci): update podman pipeline

docker.go, docker_test.go
The environment variables should trump configuration from `$HOME/.testcontainers.properties` file, but only if they're set and then only if they equal `true` or `false`. This refactors `configureTC` to make sure that environment variables are always considered and indeed trump any configuration in `$HOME/.testcontainers.properties` file, even as parsing the configuration from `$HOME/.testcontainers.properties` completes partially. Also the `HOME is not set` test cases now do not set the `$HOME` so that the `os.UserHomeDir` error path is exercised by the tests.
=> refactor: more nuanced env vs properties config

docs/features/creating_container.md
It uses tabs instead of spaces in the examples for the create_container.md file, also fixing the code block before the parallel container section.
Consistency across existing docs, also fixing the ParallelContainer section, which was embedded into the previous code block
**Before this PR:** https://golang.testcontainers.org/features/creating_container/#parallel-running
**After this PR:** https://deploy-preview-481--testcontainers-go.netlify.app/features/creating_container/#parallel-running
=> docs: fix format for create-container feature

parallel.go, parallel_test.go
Hello) I found a small bug in `ParallelContainers` method. Fixed!
=> fix: return bad error after parallel running

docker.go, docker_test.go, wait/exec_test.go, wait/exit_test.go, wait/host_port.go, wait/log_test.go, wait/wait.go
Relates to https://github.com/testcontainers/testcontainers-go/issues/343
Example:
```dockerfile
EXPOSE 11211
CMD ["memcached"]
```
Old:
```go
port := "11211/tcp"
rq := testcontainers.ContainerRequest{
Image:        "memcached:1.6.10",
ExposedPorts: []string{port},
WaitingFor:   wait.ForListeningPort(nat.Port(port)),
}
```
New:
```go
rq := testcontainers.ContainerRequest{
Image:        "memcached:1.6.10",
WaitingFor:   wait.ForListeningPort(""),
}
```
=> feat: Use exposed ports specified in image if it is not specified in ContainerRequest

docker.go, docker_test.go
In many cases the container is attached to a single, named network of the "bridge" mode. In such scenarios, `DockerContainer.ContainerIP()` should resolve this IP and return it.
For example, imaging the following container definition.
```go
testcontainers.ContainerRequest{
// ...
Networks:     []string{"some-network"},
}
```
Before this change, the function `container.ContainerIP(ctx)` returns an empty string. After this change, it returns the correct container IP.
=> Return container IP when attached to a single named network

.github/workflows/ci-podman.yml, .github/workflows/ci.yml
- chore: retire not supported Go versions from CI
- chore: better CI step name
It retires Go 1.14 and 1.15 from the CI, in both testing pipelines (Docker and Podman)
New PRs using code from 1.16 and above will fail because of the CI complains that the code does not compile in older Go versions
This specially important for security fixes provided by dependabot
- Closes #492
=> chore: retire non-supported Go versions

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/discussions.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/slack.yml
It copies the issue templates that exist in the java project, adapted to Go, such as adding Go version and Go info in the bug report, and inspired by Moby's ones.
Besides that, it adds an issue template linking to the recently added Discussions page
Create a consistent experience reporting issues, enhancements or new features, providing a simple entrypoint for Slack or Discussions
- Closes #502
=> chore: add issue templates

docker_test.go, go.mod, go.sum
Brings the go-redis package up to the latest version.
Ran the test that uses redis: `Test_BuildContainerFromDockerfile` locally and it passes.
Side note: when I try to run all the tests in the repo on main I get failures. Not sure if that has to do with my local setup or if main is broken?
=> Update go-redis to v8.11.5

docs/contributing.md, e2e/go.sum
It adapts the contributing guides from tc-java to tc-go, removing what it's not needed.
The community should have a clear understanding of what are the expectations of the maintainers when receiving a contribution.
This document is a live one, which means that we will be adding and/or removing sections if/when needed.
- Closes #234
=> docs: add contributing guides

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature.yml
It refines the sentences for the issue templates, providing more context about new features, bugs or enhancements
Will put the focus on not opening issues for existing ones
- Relates https://github.com/testcontainers/testcontainers-java/pull/5836/
=> chore: improve issue templates

e2e/container_test.go, wait/sql.go, wait/sql_test.go
=> feat: add host param to url function for wait.ForSQL

.github/workflows/ci.yml
It uses the hashed version of Codecov's GH action, pinning it to v3.1.0. See https://github.com/codecov/codecov-action/releases/tag/v3.1.0
Security concerns about using dynamic version of GH actions
- Closes #312
=> chore: pin codecov's GH action to v3.1.0

.github/workflows/ci-podman.yml, .github/workflows/ci.yml, e2e/go.mod, go.mod
It removes go1.16 and go1.17 from the CI, as they are not supported any more
Let's keep only the supported versions (last two minors)
- Closes #529
- Discoverd while testing #528
We could automate the bump of the Go versions that are supported at CI time, see #529 comment
=> chore: retire old versions of Go

.github/release-drafter.yml
It includes the `type/test-flakiness` GH label into the `Housekeeping` section of the release drafter
To add PRs/issues with that label into the changelog/release notes
- Discovered while testing #528
=> chore: include test flakiness in the release drafter

logconsumer_test.go
It removes the skip condition in the `Test_LogConsumerGetsCalled` test function.
As described in #331, we skipped it because there was flakiness with Go 1.14 and Go 1.15
Since we are supporting only the latest two minor versions of Go in the CI (see #492 and #493), we expect the flakiness disappears.
- Closes #331
=> chore: do not skip test

README.md, docs/contributing_docs.md, docs/features/build_from_dockerfile.md, docs/features/copy_file.md, docs/features/docker_compose.md, docs/features/garbage_collector.md, docs/features/using_podman.md, docs/index.md, docs/quickstart/gotest.md, testing.go
**What does this PR do?**
This PR is meant to improve consistency in documentation and make minor typo adjustments.
**Why is it important?**
Enhance dev understanding and readability in documentation.
**Related issues**
None
=> docs: improve consistency and fix typos

CONTRIBUTING.md, docs/bounty.md
It copies the CONTRIBUTING.md file from tc-java, locating it in the root dir of the project.
Two things: 1) it provides context on how to contribute to the project, and 2) helps with the onboarding process for Hacktoberfest
=> chore: add CONTRIBUTING file

.github/release-drafter.yml
It adds the warning emoji to the `Breaking changes` section in the Release Drafter's configuration file
Consistency with the rest of the sections (emoji + title) and with the Java changelog, which uses the same emoji
=> chore: add emoji to breaking changes in release drafter

docs/features/using_colima.md, mkdocs.yml
This pull request adds documentation around the utilization of Colima with Docker. It includes two ways of integrating with Colima, one of which is suggested by Colima and the other is the workaround defined from a Slack Thread of debugging which also serves as a pre-v0.4.0 Colima solution.
=> docs: add docs regarding Colima usage

docker.go, docker_test.go
docker cannot do container network mode with exposed ports.
in order to make it work, only calculate the default exposed
ports if the NetworkMode is NOT container.
=> fix container NetworkMode usage

container.go, docker.go, docker_test.go
[context from slack](https://testcontainers.slack.com/archives/C1SUBPZK6/p1665000052571229)
adds cap-add/cap-drop to container request and passes to docker host config
=> Support for cap-add/cap-drop

mkdocs.yml
=> Add system requirements parent docs page for podman and colima

docker.go, docs/features/garbage_collector.md
It does :
- prints a simple banner if Ryuk is skipped for a container or a network, displaying a link to the docs.
- changes the block section for the reaper in the docs from a tip to a warning, including reasons why it's not recommended to disable Ryuk.
In the light of #561, good conversations have appeared around disabling Ryuk. For that reason, we are improving the docs and the outcomes of disabling Ryuk at the container request.
=> chore: proper messaging on disabling ryuk

docker.go, reaper.go, reaper_test.go, session.go
It initialises the sessionID of the containers just once, as in the past it was created per-container, and this is not the expected behavior.
For that, we have created a global sessionID variable that is protected by sync.Once, therefore it's called just once.
This variable is used in the library with a singleton method, which is called from everywhere that a new UUID was required by a container. Therefore, all containers will share the same sessionID during a test execution/session.
Besides that, we detected a minor change in how the reaper was declaring its sessionID, using a variable with a wider scope: we have moved that sessionID variable to its own scope.
Finally, we are adding an HTTP header to the setup of the Docker client, which will allow improving tracing and other operations. …
=> feat: add sessionID HTTP Header to the Docker client setup

docker.go
It checks if the container request of the current container is for a reaper before creating a reaper for the container.
Therefore, the banner for the reaper must not be displayed.
When a reaper is created, it always skips the reaper for itself, so we must check if the request is for a reaper, and this is achieved comparing the reaper image and the image of the request
- Caused by #566
=> fix: check if the container request if for the reaper

mkdocs.yml
previously the edit links always showed a 404
as the master branch is not used anymore
now the link is updated to use the current main branch
=> fix: edit link in documentation

docker_test.go
In the `TestDockerCreateContainerWithDirs` test method, there is a test table including an error message to be checked against the possible failure modes of that feature. This error message was created as a string to be compared with the expected error message from the Docker daemon while trying to copy the dirs to the container.
In this PR, we are changing the type of that error message, from a string to an array of strings, so that we are able to check that all parts are contained in the error message from the daemon.
I acknowledge that testing an error message could lead to flakiness in the future, so we could simple remove the assertions.
We have observed two different error messages in the Docker daemon for the same operation of copying a directory to a path that does not exist in …
=> chore: check error message in parts when testing the CreateContainerWithDirs method

docker_test.go
It enriches the error messages to be verified when copying directories into non-existing paths in a container
Fix the build
- Completes #576
=> fix: better error message in tests

mkdocs.yml, wait/sql.go
It bumps the version of the library in the docs site, and adds named parameters in a function of the public API.
Keep docs up-to-date, and increase the readability of that function while consuming it.
=> chore: prepare for 0.15.0 release

.github/workflows/ci.yml, .gitignore, Makefile
=> Remove tests coverage

.github/release-drafter.yml, .github/settings.yml, docs/contributing.md, docs/contributing_docs.md
Automated sync for OSS governance files
=> chore: sync governance files

generic.go, parallel_test.go
It adds a sync.Mutex lock/unlock when a reusable container is created, including a test that demonstrates the bug
In the original bug report (#592), a repro snippet was added, although I preferred a different test that leverages our `testcontainers.ParallelContainers` API, adding code coverage to the library. 
Thanks to @mhatch-nxcr, who reported this bug in #592, we demonstrated that the implementation of the reusable containers was not complete in terms of a parallel execution of tests creating containers with the library. The bug report found a race condition while checking the Docker client to find containers with the same name when called from a goroutine (i.e. running multiple Test functions including `t.Parallel()` or our `ParallelContainers` function).
Internally, when we are …
=> fix: support parallel execution of reusable containers

.github/workflows/ci.yml
Hello everyone! I hope you are doing well!
In this PR bump test-summary version 
Fix #582
=> feat: bump version of test-summary

docs/index.md, mkdocs.yml
Aligns the Testcontainers OSS naming conventions with the MKDocs Go documentation.
Creates a more unified appearance for Testcontainers language documentations. The Java and .NET implementation are following the same conventions.
\-
=> docs: Rename the MkDocs site name to match other Testcontainers languages

docs/examples/pulsar.md, mkdocs.yml
A quick example of how I used Pulsar in a recent test for another project which others might find useful.
It essentially mimics the way the testcontainers-java Pulsar module sets up Pulsar.
=> add example of using Pulsar with testcontainers-go

docs/features/build_from_dockerfile.md, docs/quickstart/gotest.md
It uses "Testcontainers for Go" in the docs
Because the umbrella project is "Testcontainers", and this library is the implementation for the Go language.
=> docs: wording in project name

docker_test.go, docs/features/networking.md, mkdocs.yml
It documents the networking basics:
- exposing ports to the host
- getting container host
- advanced networking such as creating networks and attaching containers to them, including aliases
It uses the `codeinclude` mkdocs plugin, to embed code snippets demonstrating each feature.
This docs page is basically a copy from the Java one, but removing the section that explains how to bind a host port to the container.
Docs, docs, docs!!
- Closes #607
=> docs: networking basics

docker_test.go, docs/features/wait/log.md, docs/features/wait/multi.md
It extracts the mysql docker image string to a constant in the tests, using a fixed version (8.0.30) instead of latest.
Consistency in the code. I'm also seeing certain unstability in the tests consuming the MySQL image when running them in the CI:
```
goroutine 1743 [sleep]:
time.Sleep(0x5f5e100)
/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/time.go:194 +0x12e
github.com/testcontainers/testcontainers-go/wait.(*LogStrategy).WaitUntilReady(0xc000846270, {0x2220b20?, 0xc0008be060?}, {0x2223870, 0xc0005f9a40})
/home/runner/work/testcontainers-go/testcontainers-go/wait/log.go:99 +0x165
github.com/testcontainers/testcontainers-go/wait.(*MultiStrategy).WaitUntilReady(0xc000699520, {0x2220ae8?, 0xc000136000?}, {0x2223870, 0xc0005f9a40}) …
```
=> chore: use a fixed version of MySQL

docs/quickstart/gotest.md
Fixes errors in the example codeю
The example code is not working as expected.
Just run the example code.
=> update gotest.md - fix errors in the example

README.md
This is a documentation enhancement.
Fix an outdated method in README.md
Environment: `go 1.19.3`, `testcontainers-go v0.15.0`.
Most users would grab this example for test. So, it should work out of the box.
Too tiny to create an issue.
=> README: update `nginxC.Terminate`

docs/quickstart/gotest.md
It documents the replace directive that is needed to be added after the `v0.16.0` release.
It could create confusion if not documented, as expressed in #629
- Discovered in #629
- Relates https://github.com/docker/compose/issues/9946#issuecomment-1288923912
- Closes #634
=> docs: document replace directive for Docker Compose

mkdocs.yml
It bumps the version in mkdocs to the latest_version
TBH I'm not sure if this extra value is used by mkdocs to render the docs site. According to their docs: https://www.mkdocs.org/user-guide/configuration/#extra
> A set of key-value pairs, where the values can be any valid YAML construct, that will be passed to the template. This allows for great flexibility when creating custom themes.
>
> For example, if you are using a theme that supports displaying the project version, you can pass it to the theme like this:
```yml
extra:
version: 1.0
```
But I cannot see any occurrence of the `latest_version` key.
=> chore: bump version in mkdocs

docs/examples/index.md, examples/_template/go.mod.tmpl, examples/main.go, examples/main_test.go
This PR is doing a few things to modify how the docs site is generated:
- it uses the current latest version of Testcontainer for Go, taken from the `mkdocs.yml` file (see extra.latest_version field)
- updates the instructions on how to run the generator, as it included an old version
- fixes the generator to make sure the index.md file is the first element in the examples nav bar. The rest of examples will be alphabetically sorted
- makes a restriction on examples name: only alphabetical chars are allowed
Improve the experience of generating examples for the latest release
Run the tests :)
=> chore: adjust generator for the docs site

examples/main.go, examples/main_test.go, mkdocs.yml
It fixes how the nav bar for the examples is generated, not appending the examples to the "non"-empty array that the generator created to define the examples nav bar.
It added empty elements to the nav bar, that the user must remove before submitting the example
-
=> fix: do not create garbage in examples nav bar

.github/dependabot.yml
It removes quotes from dependabot config, preparing for #654
YAML marshaling will not quote values unless they change their meaning when unquoted, which is the case
- Blocks #654
=> chore: remove quotes from dependabot updates

examples/datastore/datastore_test.go, examples/firestore/firestore_test.go, examples/pubsub/pubsub_test.go, examples/spanner/spanner_test.go
Avoid use of env vars due to will not allow running parallel tests.
Use `options` instead to set the container address.
=> Improve datastore, firestore, pubsub and spanner tests

.github/workflows/bigtable-example.yml, .github/workflows/ci.yml, .github/workflows/cockroachdb-example.yml, .github/workflows/datastore-example.yml, .github/workflows/firestore-example.yml, .github/workflows/golangci-lint.yml, .github/workflows/mysql-example.yml, .github/workflows/nginx-example.yml, .github/workflows/postgres-example.yml, .github/workflows/pubsub-example.yml, .github/workflows/pulsar-example.yml, .github/workflows/redis-example.yml, .github/workflows/spanner-example.yml, .github/workflows/toxiproxy-example.yml, examples/_template/ci.yml.tmpl, examples/main_test.go
It will avoid multiple pushes to have concurrent builds, aborting running builds in the followins scenarios:
- for PRs, a new commit will abort running builds for the workflow
- for branches, because it will use the SHA commit as discriminator, a new commit won't abort the running builds
Taking a look at https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration, it seems there is a max number of concurrent builds per organization.
@kiview, we should consider this for any project spanning multiple builds (per lang, per module, per OS...).
-
=> chore: reduce concurrent builds

.github/dependabot.yml, examples/dependabot_test.go, examples/main.go, examples/main_test.go
It adds the compose module to dependabot updates.
Keep dependencies up-to-date after moving the compose code to a separate Go module
- Completes #650
=> chore: add compose module to dependabot

modules/compose/testresources/docker-compose-complex.yml
It bumps the version of the MySQL docker image, from 5.7 to 8.
mysql:5.7 does not have an ARM flavor, which makes impossible to run the tests locally on a Mac M1
=> chore: support running MySQL compose in ARM

examples/bigtable/go.mod, examples/cockroachdb/go.mod, examples/datastore/go.mod, examples/firestore/go.mod, examples/mysql/go.mod, examples/nginx/go.mod, examples/postgres/go.mod, examples/pubsub/go.mod, examples/pulsar/go.mod, examples/redis/go.mod, examples/spanner/go.mod, examples/toxiproxy/go.mod, mkdocs.yml
It bumps all example modules to tc-go 0.17.0
Keep example modules up-to-date
=> chore: bump testcontainers-go to 0.17.0 in examples

wait/http.go
From to the documentation:
> If the returned error is nil, the Response will contain a non-nil body
which the user is expected to close.
Close the response body according to the documentation.
Failed requests (due to wrong response or status code) were leaving open connections.
- None, afaik
=> fix: close response body in http strategy

examples/mongodb/mongodb_test.go
cleaner example of using mongo test
-
=> simplify mongodb test

docs/examples/index.md, examples/_template/Makefile.tmpl, examples/_template/ci.yml.tmpl, examples/_template/docs_example.md.tmpl, examples/_template/example.go.tmpl, examples/_template/example_test.go.tmpl, examples/_template/go.mod.tmpl, examples/_template/tools.go.tmpl, examples/main.go, examples/main_test.go
This PR is adding a flag to the examples generator so that it's possible to define a camelcase version of the name to be used when initials are present.
It will allow creating an example but overriding the default name with a custom title that follows the same rules that a name, i.e. alphabetical
characters, only. The only difference is that it allows uppercase chars that will be used when certain initials are needed in uppercase: i.e.
mongodb and MongoDB (before this changes it was Mongodb).
This title will be used here:
- the CI descriptor, as its name
- the H1 heading in the docs page for the example
- the struct for the example, which is now exampleDBContainer
- the setupExample function name, which is now setupExampleDB
As detected …
=> chore: support for titles in examples

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/spanner/go.mod, examples/spanner/go.sum
- chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples/spanner (#781) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples/firestore (#780) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples/pubsub (#779) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples/bigtable (#778) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples/datastore (#777) @app/dependabot
- Closes #781
- Closes #780 
- Closes #779
- Closes #778
- Closes #777
=> chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples

.github/dependabot.yml, examples/dependabot.go, examples/dependabot_test.go
It updates dependabot's descriptor and the code generator to use a weekly schedule for dependabot updates.
We want to reduce the overhead of merging dependabot's updates, which could lead to have as many PRs as example modules exist in the project.
We currently mitigate this issue combining PRs that are related, but we still suffer when the dependencies are bumping multiple versions in the same week.
With this PR we expect to have this overhead, at most, once a week instead of multiple times a week.
=> chore: check dependabot dependencies weekly

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/spanner/go.mod, examples/spanner/go.sum
- chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples/spanner (#788) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples/pubsub (#787) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples/datastore (#786) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples/bigtable (#785) @app/dependabot
- chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples/firestore (#784) @app/dependabot
- Closes #788
- Closes #787
- Closes #786 
- Closes #785 
- Closes #784
=> chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples

docs/features/docker_compose.md
It fixes the import paths for the compose module in the documentation
It was using the root package as import path, which was correct before moving compose to its own package. This PR fixes it
- Asked on Slack by @lbergengruen, who created the following repro repo: https://github.com/lbergengruen/test-app
- Fix for the repro: https://github.com/lbergengruen/test-app/pull/1
=> fix: use right import package for compose in docs

docker.go, internal/testcontainersdocker/docker_host.go, internal/testcontainersdocker/docker_host_test.go, reaper.go, reaper_test.go
This PR moves the extract docker host function to an internal package, as it's an implementation detail of the internals of this library. Therefore, we consider this should not be exposed outside of the library.
In Go, an internal package is an special package that is interpreted by the Go compiler, checking that only packages having the same parent package as the internal can actually import it.
This is handy to hide functionality to be used _internally_ from the public API.
=> chore: extract docker host calculation to an internal package

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/cockroachdb/go.mod, examples/cockroachdb/go.sum, examples/consul/go.mod, examples/consul/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/mongodb/go.mod, examples/mongodb/go.sum, examples/mysql/go.mod, examples/mysql/go.sum, examples/nginx/go.mod, examples/nginx/go.sum, examples/postgres/go.mod, examples/postgres/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/pulsar/go.mod, examples/pulsar/go.sum, examples/redis/go.mod, examples/redis/go.sum, examples/spanner/go.mod, examples/spanner/go.sum, examples/toxiproxy/go.mod, examples/toxiproxy/go.sum
It runs `make -C examples tidy-examples` to synchornize example modules dependencies with root package
Avoid compile problems when working with the example modules
- Caused by #793
=> chore: bump containerd in examples

docs/index.md
Signed-off-by: Samantha Coyle <sam@diagrid.io>
Update docs section to include Intel as using pkg.
Maintain accurate account of testcontainers-go users.
None
Verify doc updates.
=> docs: add intel as user

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/spanner/go.mod, examples/spanner/go.sum
- chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples/bigtable (#808) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples/datastore (#807) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples/pubsub (#804) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples/firestore (#805) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples/spanner (#803) @app/dependabot
- Closes #808
- Closes #807
- Closes #804
- Closes #805
- Closes #803
=> chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples

modules/compose/compose_api.go
Prevent concurrent writes to the `dockerCompose.containers` map using a mutex.
To avoid occasional panics when running tests that use Docker Compose with multiple wait strategies.
- Fixes https://github.com/testcontainers/testcontainers-go/issues/811
=> fix: Synchronise writes to dockerCompose.containers map

wait/health.go, wait/health_test.go
Fixes a panic caused by a `nil` pointer dereference in the `HealthStrategy.WaitUntilReady` function.
See Issue #801 
Anyone using the `HealthStrategy` for their tests would see them failing with the panic.
- Closes #801
I have added the following tests, to cover the various scenarios:
```
PASS wait.TestWaitForHealthTimesOutForUnhealthy (0.20s)
PASS wait.TestWaitForHealthSucceeds (0.00s)
PASS wait.TestWaitForHealthWithNil (0.30s)
```
The `TestWaitForHealthWithNil` test will cause the panic with the original code, but it does not after the PR is applied.
=> fix: nil pointer dereference in HealthStrategy

docker.go, docker_test.go, internal/testcontainersdocker/labels.go, internal/version.go, reaper.go, reaper_test.go
This PR adds a Go file in the internal package with the constants representing the Docker labels that will be applied to all the containers produced by this library.
We are deprecating the old ones, as they were part of the public API, and using the new ones internally (production and test code). We are keeping the usage of the old labels for backwards compatibility in the case any of our users was using the old labels.
For the version of the library, which we do not want to expose at this moment, it lives in the internal package.
It will allow us to identify containers created by testcontainers for Go in a more consistent manner.
=> chore: update Docker labels for containers

scripts/release.sh
- fix: unstash does not exist
- fix: use the right IRL endpoint for go proxy
It fixes two parts of the release script:
- replaces `git unstash` :facepalm: with `git stash pop`
- appends the `.info` suffix to the Go proxy URL
Otherwise it's not possible to perform the release
- Caused by #776
=> fix: tune release script

modules/localstack/localstack.go, modules/localstack/localstack_test.go, modules/localstack/v1/s3_test.go, modules/localstack/v2/s3_test.go
It removes the usage of AWS_ env vars for the localstack module, as they are deprecated in the upstream project. 
KISS
- Relates https://github.com/localstack/docs/pull/486
=> chore: simplify env vars for localstack module

modulegen/_template/ci.yml.tmpl, modulegen/_template/docs_example.md.tmpl, modulegen/_template/tools.go.tmpl, modulegen/main.go, modulegen/main_test.go
- fix: update tests for gh workflow modules
- fix: update tests for docs and modules
- fix: support passing the parent dir
- fix: update tools.go
This PR fixes the generated code for modules in the following places:
- the GH workflow, where the path was hardcoded to use `examples`.
- the website docs for the module, where the path was also hardcoded to use `examples`.
- the tools.go file, where the commet used `example` type
The generated code, although valid in terms of the compiler, generates metadata that is incorrect. E.g. it's not possible to render the website because certain paths don't exist. At the same time, the GH workflow would fail because the path is also incorrect.
- Discovered while testing #876
=> fix: update modules path in generator

.github/dependabot.yml, modulegen/_template/go.mod.tmpl, modulegen/main.go, modulegen/main_test.go
This PR fixes the generated code for modules:
- the module dir in Go module file was hardcoded to `examples`: now it is modules or examples, depending on the module type.
- alphabetically sorts dependabot configs, which simplifies the code generation
- modifies the generator to properly sort dependabot updates
- fixes the go mod file, where it was prepending 'v' to version
Make the code generation experience even smoother, as there is no need to manually update any file
- Discovered while tesing #876
- Continues #877
=> fix: proper sorting of dependabot updates when generating a module

docs/features/docker_compose.md, modules/compose/go.mod
Fixes https://github.com/testcontainers/testcontainers-go/issues/892
Without this change folk can't pull and use the latest compose module v0.18
- Closes #892
Run:
`go clean --modcache` then `go mod tidy`
Without this change it'll break with the below:
`go: github.com/cucumber/godog@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`
With this change dependancies should sync.
=> bug(892): include godog in replace block of compose gomod

docs/modules/index.md, modulegen/main.go, modulegen/main_test.go
This PR relaxes the requirement around example names and titles.
Names and titles cannot currently include any numbers, which is too limiting.
This is important for products where numbers are included... like Neo4j :)
This is a prerequisite for the Neo4j work initially discussed in #636, and isolated in #921.
```
cd modulegen
go run . --name neo4j --image "docker.io/neo4j:5.5" --title Neo4j
```
This should now work.
=> Allow numerical characters in example names/titles

modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_api_test.go, modules/compose/compose_local.go
1. Add a test to demonstrate the issue problem.
2. Add logger in dockerCompose struct to fix the panic problem.
I need to restart services in some test cases.
- Relates #917
=> Fix stop services in docker compose

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/cockroachdb/go.mod, examples/cockroachdb/go.sum, examples/consul/go.mod, examples/consul/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/mongodb/go.mod, examples/mongodb/go.sum, examples/mysql/go.mod, examples/mysql/go.sum, examples/nginx/go.mod, examples/nginx/go.sum, examples/postgres/go.mod, examples/postgres/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/redis/go.mod, examples/redis/go.sum, examples/spanner/go.mod, examples/spanner/go.sum, examples/toxiproxy/go.mod, examples/toxiproxy/go.sum, modules/localstack/go.mod, modules/localstack/go.sum, modules/pulsar/go.mod, modules/pulsar/go.sum
It runs go mod tidy in all modules:
- make -C examples tidy-examples
- make -C modules tidy-modules
- make -C modulegen tools-tidy
Preparation for the new release
-
=> chore: sync dependencies

scripts/release.sh
This PR fixes the release script:
- it now handles the next version in go modules properly, as it was replacing too many things, such as the replace directive in the Go modules
- it uses the right path to each module when replacing the current version
Make the script as autonomous as possible
=> fix: use right paths in the release script

RELEASING.md, examples/bigtable/go.mod, examples/cockroachdb/go.mod, examples/consul/go.mod, examples/datastore/go.mod, examples/firestore/go.mod, examples/mongodb/go.mod, examples/mysql/go.mod, examples/nginx/go.mod, examples/postgres/go.mod, examples/pubsub/go.mod, examples/redis/go.mod, examples/spanner/go.mod, examples/toxiproxy/go.mod, mkdocs.yml, modules/compose/go.mod, modules/localstack/go.mod, modules/pulsar/go.mod, scripts/release.sh
This PR prepares the Go modules to the next v0.19.0 release. And for that:
- we added support for skipping git/curl operations in the release script. This is necessary to support modifying the mod files, only.
- actually update the mod files for next release
For the skip git/curl support, the script now accepts a `COMMIT` environment variable, taking `false` as default value. If set to true, any git/curl operation will be indeed performed. At the same time, the `DRY_RUN` variable controls the script, so if any of them are set (`DRY_RUN=true OR COMMIT=false`) then the operation won't take effect.
Therefore, performing a release needs:
- pass `DRY_RUN=false` explicitly.
- pass `COMMIT=true`, explicitly.
In the case we want to prepare a release, which means updating the Go modules to use the …
=> chore: prepare Go modules for the next release

scripts/release.sh
It fixes the release script to move to the parent directory before executing `git add`.
It did not find the changes produced by the build script.
=> fix: move to the right dir to git commit when releasing

docker_test.go, docs/features/docker_auth.md
- docs: fix snippet for containerRequest and private registries
- docs: use codeinclude
It updates the code snippet used in the Docker Auth section of the docs, which was wrong.
At the same time, it uses a `codeinclude` snippet.
Fix the code snippet, ensuring it comes from a real code block, instead of being a plain text that could be easily outdated.
- Caused by #869
=> fix: update code snippet for Docker Auth

examples/consul/consul.go
There is a deprecation notice about using `consul` and the
suggestion is to use `hashicorp/consul` instead.
It will also help as a reference when it turns out into a
module
=> Use `hashicorp/consul` in examples

.github/workflows/module-couchbase.yml, modules/vault/go.mod, modules/vault/go.sum
- chore: go mod tidy in vault module
- chore: bump Go version in Couchbase module
This PR runs `go mod tidy` in the Vault module, updating its deps, and bumps the Go version in the Couchbase module.
Keep deps in sync, also using the valid Go versions on CI
- Completes #942
- Completes #876
=> chore: update Go deps in modules

docs/modules/postgres.md, modules/postgres/postgres.go, modules/postgres/postgres_test.go
It removes the hardcoded `sslmode=disable` parameter from the connection string, as it could be the case where users set up an instance with SSL enabled.
In the tests for the module, it's disabled on purpose for simplicity.
Let the users decide
- Completes #945
=> chore: do not force SSL disabled in the connection string

docs/index.md
It's reordering the supported langs in the docs site, to have NodeJS before Python.
Consistency in the order of the languages
=> Reorder docs language links

docs/theme/partials/nav.html
It removes the trailing slash from the SRC attribute of the social links in the website.
They do not get rendered when in a multi-deployment scenario (main, v0.19.0, v0.18.0, etc)
=> chore: render logos from the base location

.github/workflows/bigtable-example.yml, .github/workflows/ci-reaper-off.yml, .github/workflows/ci.yml, .github/workflows/cockroachdb-example.yml, .github/workflows/consul-example.yml, .github/workflows/datastore-example.yml, .github/workflows/firestore-example.yml, .github/workflows/module-compose.yml, .github/workflows/module-couchbase.yml, .github/workflows/module-localstack.yml, .github/workflows/module-mysql.yml, .github/workflows/module-neo4j.yml, .github/workflows/module-postgres.yml, .github/workflows/module-pulsar.yml, .github/workflows/module-vault.yml, .github/workflows/mongodb-example.yml, .github/workflows/nginx-example.yml, .github/workflows/pubsub-example.yml, .github/workflows/redis-example.yml, .github/workflows/spanner-example.yml, .github/workflows/toxiproxy-example.yml, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go
This PR adds a filter when listening to push/pull_request events on the GH workflows, to ignore the events when the changeset includes only files in those paths.
With the raise of modules and the ability to run in multiple versions, we are seeing hundreds of GH actions being executed under the testcontainers GH org... and there are [limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) that we are hitting everyday (20 concurrent jobs) specially when dependabot wants to play with us.
With this change we expect to mitigate that issue, and only run the CI jobs with tests for code, not for docs (they are already rendered by Netlify)
=> chore: skip CI builds when updating the docs

docs/theme/partials/nav.html
This reverts commit b89457c21b4cb87dbd4471276687648dbe52ff37.
For some reason, Netlify renders the icons properly in the preview URL, but does not (404 NotFound) for the production URL.
- Reverts #995
=> Revert "chore: render logos from the base location (#995)"

mkdocs.yml
It adds a configuration to mkdocs to render a permalink next to each section from the table of contents. See https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=toc#+toc.permalink
Render URL: https://deploy-preview-1032--testcontainers-go.netlify.app/
It's possible to get the permalink from the TOC (right sidenav) but many times it's handy to copy a permalink from the content itself.
=> docs: add permalink to mkdocs headings

docs/features/wait/exec.md, wait/exec.go, wait/exec_test.go
It adds `WithResponseMatcher` to the wait.ForExec strategy, so that it behaves as in the wait.ForHTTP strategy.
Provide support for the use case where we want to run a command in a container, and verify the output of that command.
- Discovered while testing #994
=> feat: support for wait.ForExec with response matcher

container.go, docker.go, docs/features/creating_container.md, lifecycle.go, lifecycle_test.go
This PR opens the gates to the extension of a container, defining lifecycle hooks that can be leveraged by the consumers of the library to extend how a container is defined.
We have defined 8 lifecycle hooks:
1. Creating, executed right before the container is actually created by the Docker engine
2. Created, executed right after the container is created by the Docker engine
3. Starting, executed right before the container enters the Running state
4. Started, executed right after the container enters the Running state
5. Stopping, executed right before the container is stopped
6. Stopped, executed right after the container is stopper
7. Terminating, executed right before the container is terminated, removed from the Docker engine
8. Terminated, executed right after the container is …
=> feat: provide container lifecycle hooks

container.go, docker.go, docs/features/creating_container.md, lifecycle.go, lifecycle_test.go
- chore: support for multiple container life cycles
- chore: define a default logging hook
- chore: extract copying files to the postCreate hook
In this PR we are updating the lifecycle field of the container request to accept an array of lifecycles structs.
With this in mind, a user could define custom lifecycles to be appended to the list of container lifecycles, which the library will execute in the order they are passed.
Therefore, given two lifecycles in a container request this will be the execution order:
1. lifecycle-1
1.1 pre-create
1.2 post-create
1.3 pre-start
1.4 post-start
1.5 pre-stop
1.6 post-stop
1.7 pre-terminate
1.8 post-terminate
2. lifecycle-2
2.1 pre-create
2.2 post-create
2.3 pre-start
2.4 post-start
2.5 pre-stop
2.6 post-stop
2.7 pre-terminate
2.8 post-terminate …
=> chore: support for multiple lifecycles defined by the user

docs/features/networking.md
Document the `TC_HOST` environment variable in the container networking section.
Our CI Kubernetes runners were incorrectly returning `localhost` via the `Host` call. After going through the `docker.go` code I noticed there is a manual override via the `TC_HOST` ENV variable. Document this so it's more visible in the future.
=> docs: document tc_host inside the networking section

modulegen/_template/example_test.go.tmpl, modulegen/main.go, modulegen/main_test.go
- fix: update template for tests
- chore: run go vet when generating code
This PR adds a check at the end of the generated code to run `go vet` in the generated module, updating the template generating the default test file for the new functions of the module design.
The template included code for the old behaviour, and now the generated code compiles, running the check at the end of the code generation.
- Caused by #1016 #1042
=> fix: generated code must compile

modules/localstack/go.mod, modules/localstack/go.sum
- chore(deps): bump github.com/aws/aws-sdk-go-v2 from 1.17.8 to 1.18.0 in /modules/localstack (#1120) @app/dependabot
- chore(deps): bump golang.org/x/mod from 0.9.0 to 0.10.0 in /modules/localstack (#1098) @app/dependabot
- chore(deps): bump github.com/imdario/mergo from 0.3.14 to 0.3.15 in /modules/localstack (#986) @app/dependabot
- Closes #1120
- Closes #1098
- Closes #986
=> chore(deps): bump dependencies in /modules/localstack

docker.go
After updating the dependencies in my project from `v0.19.0` to `v0.20.0`, I get this error while running the tests
```
==================
WARNING: DATA RACE
Read at 0x00010366fa60 by goroutine 27:
github.com/testcontainers/testcontainers-go.ReadConfig()
/go/src/github.com/nhatthm/testcontainers-go-extra/vendor/github.com/testcontainers/testcontainers-go/config.go:45 +0x5c
github.com/testcontainers/testcontainers-go.NewDockerClient()
/go/src/github.com/nhatthm/testcontainers-go-extra/vendor/github.com/testcontainers/testcontainers-go/docker.go:787 +0x30
github.com/testcontainers/testcontainers-go.NewDockerProvider()
/go/src/github.com/nhatthm/testcontainers-go-extra/vendor/github.com/testcontainers/testcontainers-go/provider.go:139 +0x1e4 …
```
=> Fix race condition while initializing docker client

.github/workflows/golangci-lint.yml, .golangci.yml, container.go, container_test.go, docker.go, docker_mounts.go, docker_test.go, generic_test.go, logconsumer_test.go, mounts.go, network.go, network_test.go, reaper.go, wait/exec_test.go, wait/health_test.go
Enables [misspell](https://golangci-lint.run/usage/linters/#misspell) and [gci](https://golangci-lint.run/usage/linters/#gci) linters
Fixes and prevent misspellings and organize in a fixed order the dependencies imports.
=> ci(lint): enable misspell and gci linters

RELEASING.md, internal/version.go, mkdocs.yml, scripts/pre-release.sh, scripts/release.sh
- chore: improve dry_run log when hitting the Golang proxy
- chore: bump tc-go version in mkdocs
- docs: verify that the origin remote is set
- fix: define a two-phase release process
This PR resolves the inconsistencies in the current release script, defining two separate phases for the release: pre-release and release.
The pre-release phase includes the modification of the files, based on the state of the version value in the `version.go` file. This version contains the next development version, and it's the value used to perform a release.
Therefore, that value drives the release process to set it as the version for all downstream modules and examples.
This pre-release phase will modify the files without creating a commit, so that an eventual release engineer is able to check that the …
=> fix: define a two-phase release process

reaper.go, scripts/bump-reaper.sh
- chore: bump Ryuk to v0.5.1
- chore: add a script to bump ryuk in an automated manner
This PRs bumps Ryuk to the latest version (v0.5.1), and adds a shell script to bump the Ryuk version in an automated manner. The script consumes just the first argument of a call, which should be the full qualified name of the Docker image representing Ryuk: e.g. "docker.io/testcontainers/ryuk:0.5.1"
This script is used to bump the version of Ryuk in Testcontainers for Go, modifying the "reaper.go" file. By default, it will be run in dry-run mode, which will print the commands that would be executed, without actually executing them.
>Usage: ./scripts/bump-reaper.sh "docker.io/testcontainers/ryuk:1.2.3"
It's possible to run the script without dry-run mode actually executing the commands.
> Usage: …
=> chore: support for bumping ryuk in an automated manner

docs/modules/k3s.md, modules/k3s/k3s.go
Fixes version of k3s to pull its docker image. 
cc @mdelapenya
=> chore: use fixed version in k3s module

examples/bigtable/go.mod, examples/bigtable/go.sum, examples/datastore/go.mod, examples/datastore/go.sum, examples/firestore/go.mod, examples/firestore/go.sum, examples/pubsub/go.mod, examples/pubsub/go.sum, examples/spanner/go.mod, examples/spanner/go.sum
- chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples/spanner (#1227) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples/firestore (#1219) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples/datastore (#1212) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples/pubsub (#1213) @app/dependabot
- chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples/bigtable (#1209) @app/dependabot
- Closes #1227
- Closes #1219
- Closes #1212
- Closes #1213
- Closes #1209
=> chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples

docs/system_requirements/docker.md, docs/system_requirements/index.md, mkdocs.yml
It documents the Go versions that are used for building the library, which are recommended to be used in the projects, linking to the Github action where defines the Go versions to build the project.
Inform the user about the supported Go versions.
=> docs: document the Go version

docs/features/build_from_dockerfile.md
Doc fix, the current given example does not compile, suggested a fix.
=> docs: fix passing env vars example

docs/index.md
This updates the Java docs domain in any links in the docs. 
The Java docs are migrating subdomain from `www` to `java`.
=> Update java docs domain

docker_test.go, docs/features/networking.md, testing.go
- chore: use filepath to build the absolute path in tests
- fix: skip host network tests in Docker Desktop
This PR adds a public function to skip tests in the case Docker Desktop is used. We are also using this new function in 4 tests, that are setting Docker's host network via the `HostConfigModifier`. Therefore, they will be skipped when run on Docker Desktop.
This PR fixes the execution of the test suite in those environments where it's not possible to run all the tests. As an example, using the host network is not possible when running Docker Desktop (for Mac or for Windows).
With this change, it's possible now to run the entire test suite across all OSs
=> fix: skip host network tests in Docker Desktop

config.go, config_test.go, docker_test.go, docs/features/configuration.md, internal/config/config.go, internal/config/config_test.go, internal/testcontainersdocker/client.go, internal/testcontainersdocker/docker_host.go, logconsumer_test.go, provider.go
It removes the Go context object from the ReadConfig call, as it's not used internally.
It's not needed: we added it in an intermediate state of #1161
- Closes #1290
=> chore: simplify ReadConfig signature, not passing context

modules/k3s/k3s.go
The k3s module previously didn't work properly inside of a Docker container; the caller would connect to its HTTPS server via the Docker network gateway, which wasn't included in the list of SANS from the TLS certificate exposed by the k3s container. This would cause requests to fail due to TLS validation errors:
```
Get "https://172.17.0.1:32776/api/v1": tls: failed to verify certificate: x509: certificate is valid for 10.43.0.1, 127.0.0.1, 172.17.0.6, ::1, not 172.17.0.1
```
This change determines what the DaemonHost address is prior to creating the container request, and then injects that address as one of the TLS SANs.
When not running in a Docker container, the k3s module continues to function as it did before, as the DaemonHost address in that scenario is "localhost".
I have …
=> fix: support detecting if k3s module is running from inside a Docker container

mkdocs.yml
Fix a bug with the documentation generating a sitemap with `<loc>None</loc>` seamingly caused by not having `site_url` set in the mkdocs config.
e.g. 
```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>None</loc>
<lastmod>2023-06-15</lastmod>
<changefreq>daily</changefreq>
</url>
...
</urlset>
```
Search engines and other tools use the sitemap, presenting correct information is important for discoverability of the documentation.
=> Fix locations set to None in sitemap

internal/testcontainersdocker/docker_socket.go
Instead of blindly assuming a Linux operating system we can rely on the docker client package to tell us the appropriate default docker host.
I've changed the default `DOCKER_HOST` socket from its Linux value by relying on Docker's client library to supply their cross-platform values.
I chose to parse their value as a URL (I say `parseURL` doing the same) to separate between the schema and the path.
I was defensive because I am unfamiliar with the codebase - that's the reason for the suffix/prefix validations. Also, upon errors (url parsing, or unknown schema) I fallback to the predefined default rendering the changes of this PR a no-op.
Windows users really want to use test-containers too! 🪟🐳 
Before release `v0.20.1` the host was not explicitly set to a default, hence it fell-back to …
=> fix: prefer cross-platform default DOCKER_HOST

docker_auth_test.go, docs/features/files_and_mounts.md, docs/system_requirements/ci/aws_codebuild.md, docs/system_requirements/ci/bitbucket_pipelines.md, docs/system_requirements/ci/circle_ci.md, docs/system_requirements/ci/concourse_ci.md, docs/system_requirements/ci/dind_patterns.md, docs/system_requirements/ci/drone.md, docs/system_requirements/ci/gitlab_ci.md, docs/system_requirements/ci/tekton.md, docs/system_requirements/ci/travis.md, mkdocs.yml, modulegen/mkdocs.go, mounts_test.go
It copies and adapts the docs for CI services from the Java project, using Go images and Go commands to run the tests.
In the process we found that we were not documenting the "BindMounts and Volumes", so we have added it to the docs too.
Improve the docs!
- Closes #1291 
- Closes #430
=> docs: document CI services

docker.go, lifecycle.go, lifecycle_test.go
- chore: move waitFor to the default container hooks
- chore: print wait for values in the log
- feat: add container logs when the starting/started hooks of the container fails
This PR adds 3 things:
1. it extract the logic to start the wait strategies from the Start container method to the default life cycle hooks, as the first PostStart function.
2. it adds the string representation of the wait strategy struct to the log, using the `%+v` formatter, which will add fields and values. I'm doing it in this manner for simplicity: to avoid adding a String method to all the wait strategies, with custom output message. But I'm OK if we want to do that in this PR or in a follow up one.
> 2023/06/20 08:43:28 🚧 Waiting for container id bc42707acea8 image: …
=> feat: provide container logs on container startup failures

docker_auth_test.go
Do not assume non-empty auths section in local config file but test that getDockerConfig returns default config when DOCKER_CONFIG env variable is not set.
Also remove t.Cleanup calls that restore env variables because t.Setenv restores them itself.
Fixes failing test that depends on local environment.
- Relates #1394
=> test: fix TestGetDockerConfig

modules/redpanda/mounts/bootstrap.yaml.tpl, modules/redpanda/mounts/redpanda.yaml.tpl, modules/redpanda/options.go, modules/redpanda/redpanda.go, modules/redpanda/redpanda_test.go
Adds an option to enable topic auto-creation
The option to enable automatic topic creation is particularly useful for testing environments, allowing users to produce data into topics without the need to create them beforehand.
=> feat(redpanda): Add option to enable topic auto-creation

.github/workflows/ci-windows.yml
It executes a Powershell command on the Windows worker to enable long paths.
This is a temporary fix until the target machine have it as a built-in
The git checkout fails and we think this is the most plausible solution
- Continues #1375
In a PR, i.e. this one, add the `/windows-test` GH comment so that the Windows workflow gets triggered.
=> chore(ci): set LongPathsEnabled on WIndows workers

docs/system_requirements/index.md
It updates the link to the GH action in the docs site, replacing a relative URL (relative to the website, not the sourcecode) with the full URL of the Github action in the Github repository.
The link was broken in the docs site, causing a bad experience on users.
- Closes #1369
=> docs: fix link to GH action in docs site

.github/workflows/ci-test-go.yml, .github/workflows/ci-windows.yml, .github/workflows/golangci-lint.yml
- chore(deps): bump test-summary/action from 2.0 to 2.1 (#1423) @app/dependabot
- chore(deps): bump actions/github-script from 0.9.0 to 6.4.1 (#1422) @app/dependabot
- chore(deps): bump actions/setup-go from 3 to 4 (#1421) @app/dependabot
- Closes #1423
- Closes #1422
- Closes #1421
=> chore(deps): bump Github actions

internal/testcontainersdocker/docker_host.go
Closes unused docker client.
Docker client uses idle connections and if it is not closed it triggers goroutine leak detector.
I've created #1358 previously but while it is in discussion I propose to fix this obvious case which would also be enough for our project, see https://github.com/zalando/skipper/pull/2436
- Relates #1358
=> internal/testcontainersdocker: close unused client

.github/workflows/ci-windows.yml
Removes the temporary workaround to apply long paths to Windows 
It failed so we added to the self-hosted machine.
=> chore: remove temporary workaround for windows

.github/workflows/ci-windows.yml
Do not use make
It's not installed on windows
=> fix: simplify and do not run make on windows

.github/workflows/ci-windows.yml
It runs all the GH steps in the GH workflow for windows in an Alpine container. See https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
> Use jobs.<job_id>.container to create a container to run any steps in a job that don't already specify a container. If you have steps that use both script and container actions, the container actions will run as sibling containers on the same network with the same volume mounts.
>
> If you do not set a container, all steps will run directly on the host specified by runs-on unless a step refers to an action configured to run in a container.
```yaml
name: CI
on:
push:
branches: [ main ]
jobs:
container-test-job:
runs-on: ubuntu-latest
container:
image: node:14.16
env:
NODE_ENV: development …
```
=> chore: run Windows tests on a Linux container

.github/dependabot.yml, modulegen/dependabot.go, modulegen/main.go, modulegen/main_test.go
Use the sorter capabilities to handle the sorting.
It uses the package-ecosystem and the directory. 
I know that the result is a bit different from the actual.
=> Simplify dependabot updates sorting

.github/workflows/ci-windows.yml
max timeout *3 for the workflow run, which now takes +10m on Windows
Avoid killing the worker too early
-
=> chore: triple max timeout for the workflow run, which takes +10m

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml, modulegen/main_test.go
This PR adds a new input parameter to the reusable workflow, in order to "run the tests" step. Is true, it will execute the step.
With this approach the caller decides whether the tests are run or not passing true/false in the new `run-tests` parameter. In general, they will pass a `true` value, but for the core library, where we want to run the tests only for Linux, we must check that the platform is `ubuntu-latest`, only.
We noticed the value was hardcoded to run the tests only on Ubuntu, directly into the reusable workflow, but there are callers that need to run the tests on Mac and Windows too. For that reason we needed a way to tell the reusable workflow to skip the tests or to run them.
- Completes #1478
=> fix: run tests for module generator in all platforms

modules/postgres/postgres.go, modules/postgres/postgres_test.go
Use generic db url format with PG containers instead of PG specific one.
Before we where using the PG specific url format but most tools would expect the url on the generic one (i.e https://github.com/golang-migrate/migrate).
People could indeed write their own connString mapper but that would be unnecessary. (Ideally tools would not try to parse the url and instead just use the string but sometimes they might need to, thus using the generic format would work most of the times)
=> chore: Use generic db url for postgresql container

docs/features/copy_file.md
Examples of file permissions should be in octal format. But in the code examples they are not. This PR fixes that.
Change examples in docs.
Docs should be correct.
=> doc fix: make file permission examples octal

docs/modules/redpanda.md, modules/redpanda/mounts/redpanda.yaml.tpl, modules/redpanda/options.go, modules/redpanda/redpanda.go, modules/redpanda/redpanda_test.go
Adds `WithEnableTLS` option to enable TLS with a custom certificate and key PEM.
I also tweaked redpanda to clean up any temporary files as it currently leaves behind a bunch of files on every run which are never removed. Happy to move that into a separate PR if you guys feel it conflates this one a little too much.
This allows testing code which requires TLS connections to Kafka.
-
=> feat(modules/redpanda): support tls

config_test.go, internal/config/config_test.go, logconsumer_test.go
It resets the config synchronisation (sync.Once) in order to not affect other tests.
I found this issue as a side effect of debugging another thing, and it took me a couple of hours to understand that the testcontainers.properties file was empty because somebody in the test execution called the ReadConfig() method, initialising the `sync.Once` that protects from multiple reads of the config.
I noticed the HOME variable was empty when reading the Docker Host, os.UserHomeDir returned an error, and that led me to identify the config as the culprit. Following the rabbot hole I found there were two tests reading the config but not resetting the original state (only available for internal use of the library), and this PR fixes that.
=> fix: reset config in tests

internal/testcontainersdocker/docker_host.go, internal/testcontainersdocker/docker_host_test.go
This PR removes the code to parse the docker host when it comes from the `docker.host` property in the testcontainers.properties file.
It must behave as the DOCKER_HOST variable.
- Resolves #1338
=> fix: do not remove the file schema in docker.host property

modulegen/context.go, modulegen/context_test.go, modulegen/go.mod, modulegen/go.sum, modulegen/internal/mkdocs/main.go, modulegen/internal/mkdocs/reader.go, modulegen/internal/mkdocs/types.go, modulegen/internal/mkdocs/writer.go, modulegen/main.go, modulegen/main_test.go, modulegen/mkdocs_test.go
Refactor mkdocs code in modulegen
=> modulegen: create internal/mkdocs

.github/workflows/ci.yml, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go
When dependabot is creating a PR to update dependencies, it generates 226 jobs while on a PR from a fork on 116 are generated.
Triggering tests only on push on main branch will avoid this.
=> chore: fix workflow

modulegen/_template/Makefile.tmpl, modulegen/dependabot.go, modulegen/internal/make/main.go, modulegen/main.go, modulegen/make.go, modulegen/mkdocs.go, modulegen/types.go, modulegen/workflow.go
- extract Makefile file generation in /internal/make
- Extract the generation in a dedicated file for each internal domain.
- Isolate Example in a dedicated file `types.go`.
=> modulegen: create internal/make

docs/modules/pulsar.md
The pulsar module docs incorrectly mentioned the redis module. This PR updates the docs to correctly reference the pulsar module.
This is a pretty minor change that just updates some documentation.
-
=> fix: use proper service name in Pulsar module

modulegen/_template/example_test.go.tmpl, modulegen/main_test.go
Closes #1544
I tested it with : 
```
go run . --name questdb --image "questdb/questdb:latest" --title QuestDB
```
=> Fix module generator for examples

modulegen/_template/example.md.tmpl, modulegen/internal/mkdocs/template.go, modulegen/main.go, modulegen/mkdocs.go
This removes codeinclude function and use text/template instead of html/template.
It also moves the logic of markdown example file creation to the internal/mkdocs package.
This is separating code in there domain to improve the readability and maintanability.
- Relates #1536
Remove Example functions and replace them with fields so they are calculated once.
=> modulegen: generate md file inside internal/mkdocs

.github/workflows/ci.yml, .vscode/.testcontainers-go.code-workspace, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go
Removes an entry in the VSCode workspace file.
Added by mistake from a dirty Git workspace
- Added by me by mistake in #1551
=> fix: remove wrong example from workspace

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go
- chore: let all modules to finish their execution
- chore: save workers for examples
This PR adds a new input parameter to the reusable workflow to run the Go tests, making it possible to call it with a fail-fast strategy.
At the same time, we are not running the Go examples (modules that do not expose any API, just code snippets) in one single version of Go: 1.20.x, and only in Ubuntu.
The first change tries to avoid the cancellation of the entire matrix for modules, which could happen if a flaky build fails: the rest of those 60 builds will be cancelled.
The second change is to save GH workers, as examples as less critical in terms of build conditions. We will reduce by 4 the number of user workers for the examples: Given there are 10 examples, instead of 40 builds, we will have just …
=> chore: refine fail-fast strategy on CI

Pipfile, Pipfile.lock
This updates Python version to 3.8. It also synchronize pipenv.lock with requirements.txt.
Dependabot updates for pip are blocked because pipenv where using 3.7 version while runtime.txt was 3.8.
=> Update Pipenv to use Python 3.8

.github/workflows/ci-windows.yml
Update actions/github-script to 6.4.1.
Adapt the script to use last version of github client.
Allow to be compatible with the new versions of actions/github-script
=> Update actions/github-script to 6.4.1

.github/dependabot.yml, .github/workflows/ci.yml, modulegen/_template/ci.yml.tmpl, modulegen/internal/dependabot/types.go, modulegen/main_test.go
This PR removes the dependabot groups, turning back to a state where each update comes in a single PR
At the same time, skips the GH actions for any PR from @dependabot that is not already approved:
```yaml
if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.state != 'approved' && github.triggering_actor == 'dependabot[bot]') }}
```
That way, we will be able to manually combine the PRs if/when needed, not exhausting the allocated workers in the GH organisation every time @dependabot sends updates (in a monthly manner).
To extract the above condition, we created this truth table:
Resulting in that we want to process the jobs for the contrary cases of:
- the github event is a pull_request, and
- the pull_request state is not approved, and
- the author of the …
=> chore: remove dependabot groups

.github/workflows/codeql.yml
Setup [codeql](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages) scan
Helps identify vulnerabilities through the go and javascript code.
=> ci(security): setup codeql scan 

.golangci.yml, docker.go, internal/testcontainersdocker/docker_host.go, internal/testcontainersdocker/docker_rootless.go, parallel_test.go, wait/errors.go, wait/exec_test.go, wait/host_port.go, wait/http.go, wait/sql.go
Enables [errolint](https://golangci-lint.run/usage/linters/#errorlint) linter
Errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
=> ci(lint): enable errorlint linter

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml, commons-test.mk, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go, sonar-project.properties
Hi @mdelapenya, 
It seems like sonar requires a SONAR_TOKEN secret, I tried to compare with testcontainers-donet and testcontainers-node that reports code coverage on their sonarcloud reports but I couldn’t find anything comparable as they are not using the sonarcloud action to upload their test results.
I tried to provide my own SONAR_TOKEN but it seems it not possible to use it in a fork repository. 
Any idea ? Or you prefer to keep things as it is now ?
=> chore(ci): enable code coverage on Sonarcloud

sonar-project.properties
remove extra equal in sonar.organization
Otherwise the name is not recognized
=> fix: remove extra equal in sonar.organization

.github/workflows/ci-test-go.yml, .golangci.yml, sonar-project.properties
* run sonarcloud only when docker is not rootless
* generate a checkstyle report from golangci-lint for sonarcloud,  see [documentation](https://docs.sonarcloud.io/enriching/external-analyzer-reports/) 
* correct path of test report as it was not correctly discovered
=> ci(sonarcloud): run only when docker is not rootless

commons-test.mk, examples/Makefile, modules/Makefile, modules/compose/compose_local.go
- chore: support running golangci-lint for all modules
- fix: typo in error message
It adds a Make goal to run the golangci-lint tool for all modules, with a single command.
Support for running and fixing the lint stage locally before submitting a PR.
Run `make -C modules lint-modules` or `make -C examples lint-examples` or `cd modulegen; make lint`
=> chore: support linting all modules locally

modulegen/_template/examples_test.go.tmpl, modulegen/_template/module_test.go.tmpl, modulegen/internal/module/main.go, modulegen/main_test.go
This PR updates the module templates to always include the default image for the new module. It applies to:
- examples_test.go
- module_test.go
Therefore, the all `RunContainer` calls in the examples will include the `testcontainers.WithImage("foo:bar")` functional option.
Users copy&pasting our code examples will receive a code snippet including the image, which is important for awareness of what version of the technology they are using.
=> chore: always generate the examples including a explicit image

docs/modules/localstack.md, modules/localstack/localstack.go, modules/localstack/localstack_test.go
This PR adds a functional option to the localstack module, making it possible to create a Docker network for it and run localstack in that network with a given alias.
Support for running the localstack module in a network, as demo'ed in the existing tests.
- Closes #1602
=> feat: support creating a network for localstack

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml, commons-test.mk, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go, sonar-project.properties
Uploads unit-tests.xml and coverage.out in the sonarcloud artifact during the test phase. After the test-examples job the sonarcloud scan is executed with the artifacts uploaded.
This helps providing a correct code coverage on sonarcloud
=> ci(sonarcloud): upload artifact

scripts/pre-release.sh
Updates the pre-release shell sccript to also modify the sonarcloud properties file, bumping the project version in it.
Update all files including a version
- Continues #1518
=> chore: update sonarcloud properties when releasing the project

docker_client.go
It restores the state of the `sync.Once` instance out of the Do block, which was incorrect, and buggy.
Before the changes, a panic was raised, but now we'll have a proper error message:
```
--- FAIL: TestContainerAttachedToNewNetwork (26.59s)
docker_test.go:78: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?: failed to create network
```
Removes a deadlock in the case the tests are run without Docker already running on the system.
- Caused by #1490
1. Stop Docker (or its alternatives: Testcontainers Desktop, Podman...)
2. Run a test using testcontainers-go
**Expected result**: the test fail with a proper error message that Docker is not running
**Before this PR**: the test panicked with a deadlock.
=> fix: avoid deadlocks when Docker is not available

scripts/release.sh
It forces the `linux/amd64` platform and the interactive flag when running the semver Docker image using during the release.
When running against a remote Docker engine, there was no response, causing a commit with an empty value for the next release. See:
- fee2ce2b309c5acc1ae9a55d8a6e3a1a98f99ca7
- fe847d2372d70a0ff14d423644657653e7be8cbe
They were caused because of I was running against a remote Docker daemon.
=> fix: support running the semver Docker image interactively during the release process

docs/modules/artemis.md, docs/modules/clickhouse.md, docs/modules/couchbase.md, docs/modules/elasticsearch.md, docs/modules/k3s.md, docs/modules/kafka.md, docs/modules/localstack.md, docs/modules/mariadb.md, docs/modules/mongodb.md, docs/modules/mysql.md, docs/modules/nats.md, docs/modules/neo4j.md, docs/modules/postgres.md, docs/modules/pulsar.md, docs/modules/redis.md, docs/modules/redpanda.md, docs/modules/vault.md, generic.go, generic_test.go, modulegen/_template/module.md.tmpl
- feat: add a generic option to add startup commands
- docs: include startup commands in all modules
This PR adds a functional option to run arbitrary commands in the container that uses them.
The startup commands will be treated as an slice of strings that will be executed in the container right after it's started. For that, it will leverage the lifecycle hooks of the container, more specifically the `PostStarts` hooks. A new lifecycle hook will be created, which will be appended to the existing lifecycle hooks.
Finally, the new functional option has been documented in all existing modules, including the template for new ones.
Containers, and more importantly modules, many time needs to run commands right after they are started to define a desired state. With this approach, we will …
=> feat: add functional option for startup commands

internal/config/config.go, internal/config/config_test.go, reaper.go, reaper_test.go
This adds two new properties, like
ryuk.connection.timeout=2m
ryuk.reconnection.timeout=3m
to control the timeouts used with the reaper container.
Their defaults are 1 minute (connection) and 10 seconds (reconnection), matching the defaults of the ryuk container's env vars.
In an E2E run, TC had problems re-creating the reaper container after it had stopped because the reconnection timeout was exceeded. With this, we can workaround that problem by increasing the timeout.
[🗨️ Discussed in Slack](https://testcontainers.slack.com/archives/CBWBNR76G/p1695319794716519)
Unit tests have been updated and added.
1. Some properties can also be controlled via env vars. We could do the same for these two new ones.
2. It might make sense to also add support for `ryuk.verbose=true`.
3. The actual …
=> make ryuk timeouts configurable via properties file

modules/couchbase/go.mod, modules/couchbase/go.sum, modules/vault/go.mod, modules/vault/go.sum
:warning: This PR has been created with the [combine-prs](https://github.com/mdelapenya/gh-combine-prs) `gh` extension.
Command:/Users/mdelapenya/.local/share/gh/extensions/gh-combine-prs/gh-combine-prs --query author:app/dependabot gjson --interactive --verbose --skip-pr-check.
It combines the following PRs:
- chore(deps): bump github.com/tidwall/gjson from 1.16.0 to 1.17.0 in /modules/couchbase (#1674) @app/dependabot
- chore(deps): bump github.com/tidwall/gjson from 1.16.0 to 1.17.0 in /modules/vault (#1672) @app/dependabot
- Closes #1674
- Closes #1672
=> chore(deps): bump github.com/tidwall/gjson from 1.16.0 to 1.17.0 in /modules/couchbase and /modules/vault

docs/modules/index.md, modulegen/_template/examples_test.go.tmpl, modulegen/internal/module/main.go, modulegen/main_test.go
In the modules page, it gives more importance to the code snippet for running the CLI tool to create a new module.
It also updates the template that generates the code for examples, removing the need for generating the examples_test.go file for example modules.
Before these changes, the first code snippet was for creating a code example, which was misleading causing confusion on how to run the tool.
Fix the bug in the template is also important.
- Relates #1689
=> docs: improve experience for creating modules for first time

docker_auth_test.go, testdata/auth.Dockerfile
Port 5000 is used by "Control Center" on Mac OS Monterey and above. So it's essentially a reserved port on Macs. This PR simply uses port 5001 instead so that TestBuildContainerFromDockerfileWithDockerAuthConfig will pass on MacOS. 
MacOS is a fairly common developer platform. Seems like the tests should pass there as well as Linux. 
N/A
<!-- Recommended
Tests should just run as normal. Simple port change.
=> TestBuildContainerFromDockerfileWithDockerAuthConfig working on MacOS

docker_test.go
TestContainerNonExistentImage/the_context_cancellation_is_propagated_to_container_creation was failing on my laptop. After a bit of debugging it looks like there was a race condition and the container was able to startup and error out before the context timeout period.  
Heres the error text:
> === RUN   TestContainerNonExistentImage/the_context_cancellation_is_propagated_to_container_creation
> 2023/09/27 17:24:00 🐳 Creating container for image [[docker.io/postgres:12](http://docker.io/postgres:12)](http://[docker.io/postgres:12](http://docker.io/postgres:12))
> 2023/09/27 17:24:00 ✅ Container created: 3ba961202c0e
> 2023/09/27 17:24:00 🐳 Starting container: 3ba961202c0e
> 2023/09/27 17:24:01 ✅ Container started: 3ba961202c0e
> 2023/09/27 17:24:01 🚧 Waiting for container id 3ba961202c0e …
=> reduce timeout in context cancellation propegation test for test stability

docker_test.go
This PR uses the non-alpine influxdb image for the TestContainerRunningCheckingStatusCode test. There's no ARM alpine image for influx db. See https://github.com/influxdata/influxdata-docker/issues/335.
The test won't pass with Docker running under ARM. Example: Mac OS with Apply Silicon and Docker Desktop.  Seems like a simple fix to get the test passing more broadly.
N/A
<!-- Recommended
This should work under both x86 and ARM since it's just using the default non-alpine image (tested on ARM).
=> fix TestContainerRunningCheckingStatusCode to pass on arm platforms

modules/rabbitmq/go.mod
Bumps the testcontainers-go dependency from 0.23.0 to latest (0.24.1)
It was outdated, possibly after a rebase/merge before the releases.
=> fix: bump tc-go dependency in RabbitMQ

wait/http.go, wait/http_test.go
I've observed intermittent failures with TestShouldStartContainersInParallel. After digging into it I realized that there's a race in http WaitUntilReady. There's a brief period of time where no error is returned, but the external port hasn't been bound yet. To fix this I simply updated the logic so that one interval passes before we check the ports for the first time. This seems to do the trick and the test doesn't fail intermittently for me now.  
The interval time still seems like an arbitrary sleep though.  I also tried a different solution which retried until the port gets bound (or context timed out), but then you would need to  either: 
1) Change multiple other tests to accommodate timeouts and get rid entire concept of "No exposed tcp ports or mapped ports - cannot wait for …
=> avoid race conditions by waiting one polling interval 

docs/system_requirements/rancher.md, mkdocs.yml
=> Rancher Desktop instructions

docs/system_requirements/rancher.md
Missed a forward-slash: unix:/ -> unix://
=> DOCKER_HOST var typo

docs/modules/mariadb.md, docs/modules/postgres.md
Some document fixes what i come across:
- Fix typo in postgresql doc `WithInitScript` -> `WithInitScripts` 
- Mention the `WithScripts` name in mariadb document just like mentioned in mysql document
=> docs: Fix typo and mention the relevant function name in doc

docs/modules/k6.md, modules/k6/examples_test.go
This PR adds the core options to the k6 module, updating the markdown file for it.
At the same time, it's splitting the usage example in different parts: create the httpbin app using a generic container, getting its IP, the JS script to be used, and the k6 container.
We forgot adding them in previous PRs.
- Completes #1721
=> docs: add default options to k6 module

docs/modules/neo4j.md, modules/elasticsearch/options.go, modules/gcloud/gcloud.go, modules/nats/options.go, modules/rabbitmq/options.go
I came across some wrong module names that were probably forgotten after copy-paste, then I checked all modules and fixed them.
=> Fix wrong module names in docs and comments

modulegen/go.mod, modulegen/go.sum, modules/elasticsearch/go.mod, modules/elasticsearch/go.sum, modules/kafka/go.mod, modules/kafka/go.sum
:warning: This PR has been created with the [combine-prs](https://github.com/mdelapenya/gh-combine-prs) `gh` extension.
Command:/Users/mdelapenya/.local/share/gh/extensions/gh-combine-prs/gh-combine-prs --query author:app/dependabot --interactive --verbose --skip-pr-check.
It combines the following PRs:
- chore(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 in /modules/elasticsearch (#1731) @app/dependabot
- chore(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 in /modules/kafka (#1729) @app/dependabot
- chore(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 in /modulegen (#1727) @app/dependabot
- Closes #1731
- Closes #1729
- Closes #1727
=> chore(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 in /modules/{elasticsearch,kafka} and /modulegen

commons-test.mk, docker_client.go, docker_client_test.go
This fixes a data race in docker client `Info()` which occurs when e.g. docker socket is unreachable:
```
==================
WARNING: DATA RACE
Write at 0x0001098d6700 by goroutine 29:
github.com/testcontainers/testcontainers-go.(*DockerClient).Info()
/Users/USER/code_/testcontainers-go/docker_client.go:69 +0xa4
github.com/testcontainers/testcontainers-go.NewDockerClientWithOpts()
/Users/USER/code_/testcontainers-go/docker_client.go:110 +0xd4
github.com/testcontainers/testcontainers-go.NewDockerProvider()
/Users/USER/code_/testcontainers-go/provider.go:142 +0x1e4
github.com/testcontainers/testcontainers-go.ProviderType.GetProvider()
/Users/USER/code_/testcontainers-go/provider.go:113 +0x654
github.com/testcontainers/testcontainers-go.GenericContainer() …
```
=> fix: data race in docker client `Info()`

docker.go
As part of trying to fix the issues discuss in #1700, I tried this first. Turns out  the lack of sychronization in StartLogProducer and StopLogProducer was actually red herring, however it seems like is still a useful addition so I thought I'd send out the PR for review. 
Makes (Start/Stop)LogProducer  more deterministic and perhaps will prevent future race condition bugs.
=> Log producer start stop sync

modules/localstack/examples_test.go
It refactors the localstack example using lambdas to consume the lambda with an HTTP client instead of running a command inside the container.
It will be easier for consumer to use their own tools that invoking the container's ones.
- Completes #1790
=> chore: use HTTP calls to invoke the lambda from the tests

testcontainer.go, testcontainers_test.go
- chore: expose session ID
- chore: add tests for session ID
It adds a new function to the API, exposing the internal SessionID so that consumer can read it and do whatever they need with it: e.g. naming things that need to be unique across different test sessions.
Users actually need this to name things in an unique manner across test sessions.
- Relates #1788 (see thread: https://github.com/testcontainers/testcontainers-go/pull/1788#discussion_r1371189053)
=> chore: expose SessionID

.github/workflows/ci-test-go.yml, .github/workflows/codeql.yml, .github/workflows/scorecards.yml, README.md
This is used by prometheus, see [this issue](https://github.com/prometheus/prometheus/issues/11325#issue-1378232774)
It provides Sonarcloud and Slack badges in the README which is also indented to present clearly the different kinds of badges.
=> Add OpenSSF Scorecards GitHub Action

container.go, docker.go, docker_test.go, docs/features/build_from_dockerfile.md
Adds an option to keep images if they have been built.
This avoids the need to build these images every time from scratch.
Built images are being kept in `DockerContainer.Terminate` when `KeepImage` is set to `true` in `ContainerRequest`.
If images for testing are built with long build time, they are currently always deleted.
This means that for each test run, the whole image needs to be rebuilt.
If the image stays the same for every test, this may take up a lot of time.
_None_
Create a container with image-build manually and set `KeepImage` to true.
Tests for this functionality have been added as well.
=> feat: add image-keep option for built images

modules/redpanda/redpanda.go
When starting the Redpanda container, adds the readiness condition to wait for the listening port to be available.
The container may not be ready to accept connections yet, although the process started gets to log the targetted log: "Successfully started Redpanda!"
- Closes #1827
Just run the tests in the redpanda module:
```
cd modules/redpanda
make test
```
=> fix(redpanda): add wait for listening port condition on startup

docs/features/common_functional_options.md, docs/modules/localstack.md, generic.go, modules/localstack/localstack.go
- feat: move WithNetwork functional option to the core
- chore: reuse the network if it already existed
This PR moves the existing `WithNetwork` functional option that was present in the localstack module to all the modules.
This option will be improved to detect if a network with that name already existed and, in that case, reuse it instead of creating a new one. The latter was the observed behaviour in case somebody imported the localstack module to use that option: a new network would be created even though they used the same name.
Allow modules to run on a separate network, and make it possibly in a reusable manner, without creating multiple networks.
=> feat: expose a WithNetwork functional option

container_test.go, generic.go, generic_test.go, options.go, options_test.go
This PR does:
- adds tests for withNetwork option
- moves all the existing functional options to its own file, options_test.go, not changing the public APIs.
- enriches the assertions for the with-startup-command tests
- moves existing test for CustomiseRequest to options_test.go
Adds more code coverage, making pass the sonar GH check.
- Relates #1887, as it introduced the new functional option.
=> chore: add tests for withNetwork option

modules/neo4j/examples_test.go, modules/neo4j/neo4j.go
Respect all `ContainerCustomizer` options passed to the neo4j `RunContainer` function.
Additionally, this fixes a nonexistent image tag in the `ExampleRunContainer` test.
Currently the neo4j module only respects `ContainerCustomizer`s that affect the `ContainerRequest` field, not other fields. This means that options like the logging implementation cannot be changed.
- Closes #1901
=> Fix - respect ContainerCustomizer in neo4j module

modules/redpanda/go.mod, modules/redpanda/go.sum
:warning: This PR has been created with the [combine-prs](https://github.com/mdelapenya/gh-combine-prs) `gh` extension.
Command:/Users/mdelapenya/.local/share/gh/extensions/gh-combine-prs/gh-combine-prs --query author:app/dependabot --interactive --verbose --skip-pr-check.
It combines the following PRs:
- chore(deps): bump github.com/twmb/franz-go from 1.15.0 to 1.15.1 in /modules/redpanda (#1871) @app/dependabot
- chore(deps): bump github.com/twmb/franz-go/pkg/kadm from 1.9.2 to 1.10.0 in /modules/redpanda (#1870) @app/dependabot
- Closes #1871
- Closes #1870
=> chore(deps): bump github.com/twmb/franz-go and github.com/twmb/franz-go/pkg/kadm in /modules/redpanda

modules/rabbitmq/examples_test.go, modules/rabbitmq/types_test.go, options.go
- chore: add raw command implementation of Executable
- chore: make rabbitmq examples more readable
This PR adds a new struct implementing the Executable interface. This new type is basically a slice of string representing a `RawCommand` that can be used in the `WithStartupCommand` functional option.
As a consequence, we can simplify the examples for RabbitMQ without exposing in the docs the sample types we created for reference only (not public API). We are simply using the new type, which makes the examples copiable.
Simplicity
- Closes #1702
=> chore: make rabbitmq examples more readable

container.go, docker.go, docker_test.go
This change allows the container working directory to be specified in the `ContainerRequest` struct.
Setting the working directory allows users to perform actions on files in an isolated directory, and to use relative paths, without using `cd` inside their containers.
A test (`TestWorkingDir`) has been added to cover this feature. This change can also be manually verified by setting the `WorkingDir` field in a `ContainerRequest`, using it to start a container, and validating the current working directory of the launched container using the `pwd` utility (if present in the image).
=> feat: Allow the container working directory to be specified

reaper.go, reaper_test.go
Reaper reuse/creation logic has been adjusted to facilitate the reuse of already running reapers. This includes using a specific naming convention based on the session id, and handling failed container creation attempts due to name conflicts by retrieving the already running reaper container. This fixes a race condition when tests are run in parallel in multiple packages which renders global locks ineffective.
Reaper container now uses a deterministic name based on the session id.
If container creation fails due to name conflict, we reuse the existing  container.
If an application uses testcontainers in multiple packages, `go test` will run them isolated from each other.
This will render global locks as in _reaper.go_  ineffective causing a race condition as multiple reapers are created. …
=> fix(reaper): fix race condition when reusing reapers

.golangci.yml, docker.go, modules/kafka/consumer_test.go, modules/localstack/localstack.go, wait/exit.go, wait/health.go, wait/host_port.go, wait/http.go, wait/log.go, wait/sql.go
Enable nonamedreturns linter which ensures there is no named return value
It ensures the rule stay applied along time
Relates to https://github.com/testcontainers/testcontainers-go/pull/1902#discussion_r1382933308
=> lint: enable nonamedreturns

modules/clickhouse/clickhouse_test.go
Reduce flakiness in ClickHouse tests by replacing `performCRUD` with `performCRUDWithRetry`.
- Closes https://github.com/testcontainers/testcontainers-go/issues/1898
=> Reduce flakiness in ClickHouse tests

docs/features/wait/sql.md
Documentation change for the [SQL Wait strategy](https://golang.testcontainers.org/features/wait/sql/) page.
Users might get confused when running the tests they just wrote if they forget to import the appropriate driver.
N/A
The docs will have to be rebuilt & redeployed.
PS: Thank you for maintaining this cool project!
=> Add database driver note to SQL Wait strategy docs

modules/kafka/kafka.go
Avoid using MaxInt64, which only works on 64-bit systems.
Telegraf is a project that runs on a variety of architectures, and we do run our tests on a 32-bit system to ensure compatibility.
```s
❯ GOARCH=386 go vet ./modules/kafka/kafka.go 
vet: modules/kafka/kafka.go:55:72: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
```
fixes: #1921
=> fix(modules.kafka): Switch to MaxInt for 32-bit support

docker.go, docker_exec_test.go, docs/features/common_functional_options.md, exec/processor.go, modules/cassandra/executable.go, modules/rabbitmq/examples_test.go, modules/rabbitmq/rabbitmq_test.go, modules/rabbitmq/types_test.go, options.go, options_test.go
This PR adds some functional options to be applied to the ProcessOptions struct, in order to customise the container exec create response.
For that, and to avoid changing the signature of the Exec method, we are exntending the ProcessOptions struct to accept the User, WorkingDir and Env for a command. We are also adding the options to contribute them to the exec create response.
Because of the previous design, in which the ProcessOptions struct applies to the container exec attach response, we are making the current Multiplexed option to not be executed if its reader is nil. This is needed because we need two loops in the options:
1. for the exec create options
2. for the exec attach options
Without changing the API, this is the simplest manner to achieve it.
Finally, it includes a …
=> feat: support for executing commands in a container with user, workDir and env

logconsumer_test.go
It skips the TestContainerLogWithErrClosed tests on Rootless docker environments, as it is flaky under those conditions.
Keep the build stable
- Related to #1924
=> chore: skip TestContainerLogWithErrClosed as flaky on rootless docker

modules/mongodb/mongodb.go, modules/mongodb/mongodb_test.go
This will add username and password functions to mongodb module. I removed mongodb_test module and put the tests in mongodb module. Because this was the pattern for other modules like postgres and mariadb.
This enables users to be able to configure username and password. Also, it creates feature parity with other modules.
- Closes #1908
I already created a test for the change in mongodb_test.go file.
=> Add username and password functions to mongodb

container.go, container_test.go, docker.go, docs/features/common_functional_options.md, docs/features/configuration.md, docs/features/image_name_substitution.md, docs/system_requirements/ci/bitbucket_pipelines.md, image_substitutors_test.go, internal/config/config.go, internal/config/config_test.go, mkdocs.yml, network.go, options.go, reaper.go, reaper_test.go, scripts/bump-reaper.sh
This PR does two major things:
1. It tries to simplify how the reaper is internally configured, and for that:
- deprecates the reaper options defined in the container and network requests. This is needed because we do not want to configure the reaper per container, but instead, do that in one single place: the testcontainers configuration
- moving the constant representing the Ryuk version to internal, as we do not want users to modify it but instead make it possible to define a custom prefix (see later)
- removing ocurrences of the deprecated code at the test level, which they won't do anything to not collide with the new features.
2. It adds support for configuring a Docker Hub prefix to be prepended to any Docker Hub image, with:
- the `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX` env var, or …
=> feat: support for custom registry prefixes at the configuration level

docs/modules/mongodb.md, modules/mongodb/mongodb.go, scripts/pre-release.sh
- docs: include mongodb options into the docs
- chore: apply introduced-when string to all markdown files from the docs
It adds the new two functional options for MongoDB to the module's docs.
It also modifies the shell script for the pre-release to locate all the markdown files to replace the introduced-at string.
We are seeing more places where the introduced-at string is required, so instead of applying to modules, we apply it to all the markdown files.
- Completes #1910
=> docs: include MongoDB's username and password options into the docs

container.go, docker.go, docs/features/build_from_dockerfile.md, from_dockerfile_test.go, testdata/target.Dockerfile
- break: add BuildOptions method in order to support advanced customisations at build time
- chore: add a test for not finding the given target in the Dockerfile
- chore: make sure the auth configs are always added
- docs: document the advanced usage
This PR adds a new field to the `FromDockerfile` struct, in order to hold a customizer function that will be executed when building a Docker image. This customizer will have access to the `ImageBuildOptions` Docker type, allowing users to build the image with as many configuration as they need. Of course, under their own risk.
We were forced to add a new method to the `ImageBuildInfo` interface, `BuildOptions`, in order to call the customizer defined by the user.
This customizer causes the deprecation of the `GetAuthConfigs` method from the …
=> feat: support customizing the Docker build command

docker_auth.go, docker_auth_test.go
This PR will fix an issue when config.json contains `auths` with keys set to the a registry URL such as `https://artifactory.com`. This way the authentication configuration for the registry will be matched with the configuration file and used.
In case where a registry is configured with an `https://` prefix, the authentication to pull images from that registry fails.
Manually add a registry and its authentication config in the `~/.docker/config.json` and run a test that requires authentication to pull images and start containers.
=> fix: fallback matching of registry authentication config

docker_exec_test.go, exec/processor.go, modules/compose/go.mod, modules/compose/go.sum
This PR allows container command execution to return stderr, when the command execution produces an error.
It's important to get the output of a error when executing a command in a container, to facilitate the error debug.
- Closes #1932 
- Relates #1932
=> fix: exec multiplexed to return stderr

docker_test.go, docs/features/override_container_command.md
I'm adding more content to command section on the documentation. I didn't know about the `Exec` method until I came across this [issue](https://github.com/testcontainers/testcontainers-go/issues/126). So, I thought it'd be nice to have this documented.
As I described above, that method is really useful when it comes to run tests on a CI environment and everybody should know about it.
There's no issue, I just asked if this is important enough to take the time to push some changes to the docs.
- 
Just run `mkdocs serve` as stated in the [contributions guideline](https://github.com/testcontainers/testcontainers-go/blob/main/docs/contributing_docs.md).
=> Add more content on how to use Exec function

lifecycle.go
This PR uses the Docker type `image.Config` to the lookup of the exposed ports from the underlying image. 
If there are no exposed ports in the container request, the code  previously checked the Docker type `image.ContainerConfig`. There are recent errors in the GH actions regarding this: exposed ports being moved from `image.ContainerConfig` to `image.Config`, because it has been deprecated and depending on how the images were built it could be the case that the `ContainerConfig` field comes empty (e.g. images built with buildkit).
- Relates to https://github.com/moby/moby/pull/46939
=> chore: lookup exposed ports in the image from Config, not from ContainerConfig

docs/features/configuration.md, internal/config/config.go, internal/config/config_test.go, reaper.go, reaper_test.go
It adds `ryuk.verbose` property to the Testcontainers property file to enable running Ryuk in verbose mode (see https://github.com/testcontainers/moby-ryuk/?tab=readme-ov-file#ryuk-configuration). It can be set there, or using the `TESTCONTAINERS_RYUK_VERBOSE=true` env var.
There are situations where we need to debug Ryuk, like being terminated too early. With this change, we will be able to tell Ryuk to run in verbose mode from testcontainers-go.
- See https://github.com/testcontainers/moby-ryuk/pull/71
=> feat: support configuring Ryuk verbose mode at config level

modules/neo4j/config.go, modules/neo4j/neo4j_test.go
This PR adds the ability to use the Neo4j Enterprise Edition docker image by setting the correct environment variable.
Many production-ready users of Neo4j use the Enterprise edition. Some features can only be tested on the Enterprise edition.
I haven't opened a concomitant Issue, @mdelapenya let me know if I should open one.
Simply run a container with image tag `enterprise` (i.e. `neo4j:enterprise`) with the new option and see that the container does not crash immediately with the following error:
<details><summary>Details</summary>
<p>
```text
In order to use Neo4j Enterprise Edition you must accept the license agreement.
The license agreement is available at https://neo4j.com/terms/licensing/
If you have a support contract the following terms apply …
```
=> Add neo4j license agreement customization options

internal/config/config.go
It removes the `docker.io/` prefix from the default Ryuk image, to adhere to the docs in https://golang.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names
It will make Ryuk configurable with the `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX` env var or the `hub.image.name.prefix` property,
allowing developers to put Ryuk on their own registries if/when needed.
- Closes #2045
- Closes #2044
- Caused by https://github.com/testcontainers/testcontainers-go/pull/1928
Update the `~/.testcontainers.properties` with:
```properties
hub.image.name.prefix=registry.mycompany.com/mirror
```
Then run a test in the project: because the prefix points to a non-existent registry, the test will fail because Ryuk cannot be found,
meaning that the prefix was applied to …
=> fix: remove docker.io from Ryuk image name

docker.go, image_substitutors_test.go, options.go
It removes the need to read the config from the prependHubRegistry image substitutor, and instead receives the prefix from the conf.
It makes the tests not depend on the singleton config, but instead in the prefix to be used. As a consequence, the unit tests are not flaky anymore.
- Caused by #1928
=> chore: do not read config but instead pass the hub prefix to the prependHub modifier

modules/gcloud/bigquery.go, modules/gcloud/bigtable.go, modules/gcloud/datastore.go, modules/gcloud/firestore.go, modules/gcloud/gcloud.go, modules/gcloud/pubsub.go, modules/gcloud/spanner.go
Fixes the GCloud modules to correctly pass the `GenericContainerRequest` into `applyOptions` as a pointer instead of copying the struct.
Currently, the modifications are done, but are thrown away because `req` is passed as a copy.
Currently, any container customizations will completely be wiped out as the `req` param is copied into `applyOptions`
- None found.
1. Start on the current `main` branch
2. Make an image modification (using `WithImage()`) verify that the image is NOT modified
3. Apply this PR
4. Redo the test from step 2 and verify that the image is now correctly modified
=> fix(modules.gcloud): pass as ptr to allow request customization

docker.go, docker_client.go, generic.go, internal/core/bootstrap.go, internal/testcontainersdocker/client.go, internal/testcontainerssession/session.go, reaper_test.go, testcontainer.go
Following the very same semantics as in #1513, we are capturing the project path for the parent PID in order to be sent to the Docker daemon, using the `x-tc-pp` HTTP header.
It will enrich the calls to the Docker daemon, passing the path where the `go test` binary was called.
As an example, running the tests of this library with `go test ./... -v` from the root:
- project path for the root package will be `/Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go`.
- project path for the wait package will be `/Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go` too.
On the other hand, running the tests of the `wait` package of this library with `go test ./... -v`, from the wait dir:
- project path for the wait package will be …
=> chore: enrich HTTP headers to the Docker daemon with the project path

generic.go, generic_test.go
`GenericContainer` function: in case of error: return a reference to the failed container. This way, the caller has an opportunity to clean things up and call Destroy on the failed container.
If a `WaitStrategy` fails (timeouts for instance, context canceled, etc.), we may still want to return a reference to the running container so that the caller can Destroy() it and not leave half-healthy containers around.
=> GenericContainer: in case of error: return a reference to the failed container

docker.go, docker_test.go, file.go
It adds the ability to create directories as needed upon request when a copy file request has a directory that doesn't exist, similar to how the Testcontainers Java implementation behaves.
Because, in many containers, to customize or import something, you may need a directory that doesn't exist in the image.
- Closes #1336
=> feat: copy files to the container and create directories as needed upon request

modules/rabbitmq/examples_test.go, modules/rabbitmq/rabbitmq.go, modules/rabbitmq/rabbitmq_test.go
Updates rabbitmq image to `3.12.11-management-alpine`.
The RabbitMQ module was broken if used without passing in an admin username that is not guest and would fail with the error `user 'guest' can only connect via localhost` (see #1702). It appears this issue no longer happens on 3.12.
- Closes #1702
=> fix(modules/rabbitmq): update container image to 3.12.11 to allow connections without passing admin credentials

reaper.go, reaper_test.go
Fixes ryuk recreation such that a new container is spun up if the previous container has terminated and been removed. This involves checking for ErrNotFound during the Ryuk state check, triggering the creation of a new ryuk container if this error is returned.
It is essential to reset `reaperOnce`. Without resetting, no attempt to create a new reaper will be made.
* Test suites that exceed the ryuk timeout fail because a new container is not created.
* Relying on clients to extend timeout as a workaround adds unnecessary work for end users.
- Closes #1671 
Run test `Test_RecreateReaperIfTerminated` to validate changes.
Or run the following test suite with env variable `SLEEP=11s`. Without changes made in this PR `TestC` would fail, but with them all tests pass.
```go
package foo
import ( …
```
=> fix: Recreate Ryuk container if terminated

docs/modules/redpanda.md, modules/redpanda/mounts/redpanda.yaml.tpl, modules/redpanda/options.go, modules/redpanda/redpanda.go, modules/redpanda/redpanda_test.go
Add a new `WithListener` function to allow adding new listeners to the advertised listeners so connection within the docker networks is possible
- Added a method to add new listener to the containers
- Validate the listener
- Iterate over the networks and add the new listeners as alias so it can be easily accessible.
Currently there is no way to access the Kafka Api from another container in the same docker network, at least not an obvious one, so as [Redpanda docs suggests](https://docs.redpanda.com/current/manage/security/listener-configuration/#advertise-a-listener) adding an extra advertise listener allows access to the Kafka endpoint from within the docker network so it can be consume from another test-container. 
-
=> feat: expose Redpanda's listener in the docker network

.github/workflows/ci-test-go.yml, .golangci.yml, docker_auth_test.go, docker_test.go, file_test.go, from_dockerfile_test.go, internal/core/docker_host_test.go, internal/core/docker_rootless_test.go, lifecycle_test.go, logconsumer_test.go, modulegen/context_test.go, modulegen/main_test.go, modulegen/mkdocs_test.go, modules/cassandra/cassandra_test.go, modules/clickhouse/clickhouse_test.go, modules/localstack/localstack_test.go, modules/localstack/v1/s3_test.go, modules/localstack/v2/s3_test.go, modules/postgres/postgres_test.go, modules/redpanda/redpanda_test.go, modules/vault/vault_test.go, mounts_test.go, network/network_test.go, options_test.go, reaper_test.go, wait/health_test.go
Setup testifylint linter and apply it’s recommandations .
It also requires at least golangci-lint 1.55 to be working so it is now 1.55.2
This will help using testify as it help configuring the test tool with the best practices.
=> lint: enable testifylint

.github/workflows/ci-test-go.yml, modules/pulsar/pulsar_test.go
Enable golangci-lint for pulsar module and fix the raised issues
Linting pulsar module helps it staying maintenable.
=> enable golangci-lint for pulsar

modulegen/internal/main.go, modulegen/internal/tools/exec.go
- chore: run make lint for new modules
- chore: add readability in the generate function
It automatically runs `make lint` on new modules created with the module generator tool.
New module authors could contribute a module but forget to run the lint, ending up in failures in the CI.
- Discovered while testing #2117
=> chore: run make lint on new modules

.github/workflows/ci-test-go.yml, .github/workflows/ci-windows.yml, commons-test.mk
Define Makefile targets to install golangci-lint and gotestsum 
Helps having the right requirements to make different targets work.
=> Go install gotestsum and golangci-lint 

.github/workflows/ci-test-go.yml, modules/redis/redis_test.go
Enable golangci-lint for redis module and fix the raised issues
Linting redis module helps it staying maintenable.
=> enable golangci-lint for redis module

.github/workflows/ci-test-go.yml, examples/cockroachdb/cockroachdb_test.go
Enable golangci-lint for cockroachdb and toxiproxy examples and fix the raised issues
Linting helps examples staying maintenable.
=> enable golangci-lint for examples

docs/features/build_from_dockerfile.md, modules/redis/testdata/Dockerfile, testdata/Dockerfile, wait/testdata/Dockerfile
Pin Docker images version
Helps improve OSSF score
=> pin Docker images version

.github/workflows/ci.yml, docker_test.go, from_dockerfile_test.go, modulegen/_template/ci.yml.tmpl, modulegen/main_test.go
In this PR, we are removing an assertion by the error message, as it changed in upstream moby (see https://github.com/moby/moby/pull/46754/files and https://github.com/moby/buildkit/pull/4394).
At the same time, we are skipping an assertion only for Rootless mode, as it's causing a failure on Docker v25.0.0, but not on lower versions.
Finally, and for the sake of reducing the total build time of the pipelines, we are moving the no-reaper and the rootless pipelines from the second stage to the first one, so that the ~5min they take happen at the same time as the main `test` pipeline.
We noticed that, since 3 days ago, the Github workers are including Docker v25.0.0 for rootless Docker, which causes the above error to appear.
The regular workers are still in v24.0.7, which will eventually …
=> chore: skip assertions for Docker Rootless

docker_mounts.go
As things are, the logger statement here always triggers for normal use cases. For example, if I start a container with this `mount: testcontainers.VolumeMount("some-vol", "/some/dir")`
then I get this weird message in my logs
`Mount type %!s(testcontainers.MountType=1) is not supported by Testcontainers for Go`
because a GenericVolumeMountSource doesn't have an implementation of `GetVolumeOptions() *mount.VolumeOptions`
I suggest removing that logging, as in this PR, because it's going to be purely confusing for 99% of users.
removes bad logging
because it was confusing before
=> chore(docker_mounts): stop doing misleading logging

docker_mounts.go
It brings back the BindMount type to the mounts mapping, as it was removed in https://github.com/testcontainers/testcontainers-go/pull/1907/files#diff-f8dd512f57a3d3bc890983ea0164e44d1aa69034527ccf41217f0f2807a76917L6
The BindMount type needs to exist in the mapping until the type is
finally removed, otherwise the deprecation path is broken for those
using the BindMount type before the final removal.
- Completes #1907
- Closes #2179 
1. Fetch this branch
2. Clone https://github.com/srabraham/demobindmount
3. Update go.mod to replace the testcontainers-go dependency to use the local branch
4. Run `go mod tidy && go run main.go` in the repro project.
=> fix: deprecate BindMounts correctly

docker_mounts.go, mounts_test.go
Adds the tescontainers-go labels to all the mounts.
Otherwise, Ryuk won't remove them.
- Relates #2163
- Relates https://github.com/testcontainers/moby-ryuk/issues/103
Run this test with and without the fix. Then monitor the volumes with `watch -n 1 docker volume ls`
```shell
go test -timeout 600s -run ^TestContainerCreationWithVolumeAndFileWritingToIt$ github.com/testcontainers/testcontainers-go -count=1 -v
```
After the fix, the `volumeName` volume should be pruned by Ryuk. Before it, not.
=> fix: all mounts should contain the testcontainers labels

README.md
fix go doc reference broken image
Make link more accessible
=> fix: go doc reference broken image

docker_mounts.go, mounts_test.go
This PR applies the testcontainers-go labels only to volumes, as it was applying them to all types of mounts, which is incorrect.
Debugging another issue with Docker bind mounts I discovered this issue.
- Caused by #2191
=> fix: apply volume options only to volumes

.github/workflows/ci.yml, modulegen/_template/ci.yml.tmpl
This PR removes the fail-fast situation when a CI build fails, making all the build in the following matrices to continue:
- main job
- reaper-off
- rootless docker
Many times the failure could be caused for some flakiness in that particular build, and its sibling could not be affected.
We run all the tests in the two current releases of Go, so if it fails in Go 1.20.x we still want to continue the execution for Go 1.21.x
=> chore(ci): do not fail fast main tests in different Go versions

docker_files_test.go
It grows the startup timeout from 200ms to 2s (x10) in the test introduced in #2199
We are seeing certain flakiness in the CI, so those 200ms could be not enough for the file to exist in the container.
- Caused by #2199
=> fix: wait more time in test

modulegen/go.mod, modulegen/go.sum, modules/kafka/go.mod, modules/kafka/go.sum
> [!NOTE]
>This PR has been created with the [combine-prs](https://github.com/mdelapenya/gh-combine-prs) `gh` extension:
>gh combine-prs --query author:app/dependabot mod --interactive --verbose --skip-pr-check.
It combines the following PRs:
- chore(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 in /modules/kafka (#2233) @app/dependabot
- chore(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 in /modulegen (#2214) @app/dependabot
- Closes #2233
- Closes #2214
=> chore(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 in /modules/kafka, golang.org/x/mod from 0.14.0 to 0.15.0 in /modulegen

modulegen/_template/examples_test.go.tmpl, modulegen/_template/module_test.go.tmpl, modulegen/main_test.go, modules/cassandra/cassandra_test.go, modules/clickhouse/clickhouse.go, modules/clickhouse/clickhouse_test.go, modules/k6/k6_test.go, modules/kafka/consumer_test.go, modules/kafka/kafka_helpers_test.go, modules/kafka/kafka_test.go, modules/mariadb/mariadb_test.go, modules/minio/minio_test.go, modules/mockserver/coverage.out, modules/mssql/mssql_test.go, modules/nats/nats_test.go, modules/openldap/openldap_test.go, modules/redis/options_test.go, modules/redis/redis_test.go, modules/redpanda/redpanda_helpers_test.go, modules/redpanda/redpanda_test.go
- fix: include import of the log package
- chore: use test package in new modules
- chore: use test package in modules
- chore: improve mssql test
This PR uses the `_test` package in all the modules that were not using it.
When needed, we have created a separate test file living in the same package's context in order not to leak helper functions to the public API of the module.
Consistency across the project, following a best practice
-
=> chore: enforce test package in modules

modulegen/_template/examples_test.go.tmpl
Added the `// nolint:gocritic` comment in the module `example_test.go` template
to make the `make lint` command succed and in consequence allow to create
modules without errors.
It is not critical, but it really confuses the module creator, also it requires
manual fix of the problem to be able to pass the linter check.
You can try to create a new module before and after the PR, you will see that
the before state is going to lead you to an error executing make lint, and the
new one passes properly.
=> Fix modulege template to succeed on make lint command

modules/milvus/milvus.go
This PR removes the rendering of the etcd config template using the random exposed ports, and the applications won't use the embed etcd.
Because it's internal to milvus, let's keep it with the default values.
- Continues #2245
=> chore(milvus): embed etcd should use default ports

docs/features/common_functional_options.md, options.go, options_test.go
Add WithEnv which set additional environment variables on a request so that callers can customise a request.
This can be used to easily add environment variables to a container created using one of the standard module e.g. postgres.
```shell
go test -run=^TestWithEnv$
```
=> feat: WithEnv customize request option

internal/config/config.go, logconsumer.go, modules/couchbase/couchbase.go, modules/couchbase/storage_mode.go, modules/neo4j/config.go, options.go, testing.go
Fix doc generation comments being included package documentation by ensuring they are separated by a blank line.
So that package documentation doesn't have processing information in them which is confusing to users.
=> docs: fix comment corruption

container.go, container_test.go, testdata/.dockerignore
When the user adds `Dockerfile` to the `.dockerignore` file, `testcontainers` is not able to build the image with error:
`Error response from daemon: Cannot locate specified Dockerfile`
This is because `testcontainers` doesn't include the `Dockerfile` to the `buildcontext` on purpose, it only expects to do so, if it is not included on the `ignorefile`. The docker client doesn't this either, the Docker cli is aware of this and maintainers have addressed this limitation in this [PR](https://github.com/moby/moby/pull/8748) long ago as the have tweaked the client to include both files to the build context.
To fix this, I added the `.dockerignore` file in the current context and the target `Dockefile` to the Build Context.
```go
includes = append(includes, dockerIgnoreLocation, …
```
=> Fix Dockerfile not located when added to dockerignore

docs/features/common_functional_options.md, logger.go, logger_test.go
Add support to use `WithLogger` as a `ContainerCustomizer` so that callers have an easy way to configure the logger of a container.
Add tests for `WithLogger`.
Validate `Logger` and `LoggerOption` implement the required interfaces.
Also fix a comment typo and remove an unneeded return.
Allows users to easily configure container loggers which is useful when using modules e.g. postgres or redis.
```shell
go test -run=^TestWithLogger$
```
=> feat: WithLogger ContainerCustomizer support

container_test.go, generic.go
Clearer error message `generic.go: GenericContainer()` function
It's customary to prefix an actual Go error with a generic message explaining the error context. 
It looks like it's already done this way [everywhere](https://github.com/search?q=repo%3Atestcontainers%2Ftestcontainers-go%20%22failed%20to%20start%20container%22&type=code) else in the code base, but not here.
=> generic.go: GenericContainer(): clearer error message

scripts/release.sh
It adds a check for the new image after the bump: if it's empty, it will stop the release the soonest.
This has been an issue when the underlying container runtime has a different platform, causing the bump process to fail, resulting in a blank value for the new version.
That causes a commit with an invalid value.
Therefore, we are forced to produce a new patch release (to adhere to semver), as all the git tags for the modules will point to a version that is incorrect: being the version empty will mean that the Docker labels added to the containers will be empty, and the HTTP headers used to interact with the Docker client will add an empty value to the testcontainers-go version of the User-Agent header.  
- See https://github.com/testcontainers/testcontainers-go/commit/e48323c39590887b518 …
=> chore: check that the new version is not empty

modules/consul/consul.go, modules/consul/examples_test.go
Fixes a race where tests can fail due to trying to use the HTTP port before it is listening
I swapped out host-based consul in a private project with testcontainers, and all the tests failed until I swapped the health check to block until the port is ready
- Closes #2335
run `make test` in the modules/consul directory
=> fix: consul race on HTTP port

docs/modules/weaviate.md
Fix weaviate module name in its docs
Copy&Paste's are risky
=> docs: fix wrong copy&paste

docs/modules/localstack.md, modules/localstack/examples_test.go, modules/localstack/localstack_test.go
It uses `WithEnv` instead of the Override container request option, which is heavier.
Simpler code
=> chore: use withEnv in localstack module

modules/weaviate/examples_test.go, modules/weaviate/go.mod, modules/weaviate/weaviate.go, modules/weaviate/weaviate_test.go
This PR adds a convenience `GrpcHostAddress` method to Weaviate module, to get the `gRPC` host.
In addition to our REST API Weaviate is also exposing `gRPC API` which greatly improves performance. It would be nice to have 
none
There are tests added to the Weaviate module package that test `gRPC` connection.
=> Add method for getting Weaviate's gRPC port

modules/redpanda/redpanda.go
Redpanda module has a custom entrypoint file `/entrypoint-tc.sh` that waits until the actual Redpanda broker node config file is mounted.
Then proceeds to call the normal Redpanda entryfile `/entrypoint.sh`.
The current implementation of the module sets the entrypoint file into the `Cmd` of the `ContainerRequest`. 
This seems to work with `Docker`, but does not work with `Podman`.
This results in an error when starting the container:
```sh
+ '[' '' = true ']'
+ exec /usr/bin/rpk /entrypoint-tc.sh redpanda start --mode=dev-container --smp=1 --memory=1G
Error: unknown command "/entrypoint-tc.sh" for "rpk"
Run 'rpk --help' for usage.
```
Since the intent is to override the entrypoint, we should be setting `Entrypoint` property as this is more appropriate.
In more detail, if we inspect the …
=> redpanda: set entrypoint to the custom entrypoint file

docs/features/wait/http.md, wait/http.go, wait/http_test.go, wait/testdata/main.go
This PR supports passing HTTP headers to the wait.ForHTTP strategy, including a matcher for response header.
We would want to wait for a certain HTTP response header to be added to a response, or we would want to pass HTTP headers to the wait strategy, and that was not possible.
=> feat: support for waiting for response headers

.github/workflows/ci-test-go.yml
Fix typo in ci-test-go.yml `Docket` -> `Docker`
=> docs: Fix typo in ci-test-go.yml

docker.go, modules/k3s/k3s_test.go
This authenticates on PullImage and improves the k3s LoadImages test so that a failure to start the pod will fail the test.
I'm using k3s with private images, so I want to use the `LoadImages` feature. The instructions to do this included running `PullImage` first, which works on anonymous images, but not authenticated ones. By re-using the same auth code used to run a container, I can now use the `LoadImages` feature in k3s with private images.
While trying to figure out what was wrong I used `Test_LoadImages` which is quite nice, but accidentally had a problem where a container can fail to run, yet still pass the test. This lost me time, so I figured I would improve it for the next person.
maybe #1685?
Change the image in Test_LoadImages from "nginx" to a privately hosted image (like a …
=> feat: authenticate docker on PullImage

docs/features/docker_compose.md, modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_local.go
- **chore: migrate from docker-compose (v1) to compose (v2)**
- **chore: lowercase error message**
- **chore: lint**
This PR changes the implementation of the local docker compose support to shell-out to the `docker` binary, with `compose` as first argument, instead of to the `docker-compose` binary.
At the same time, we are deprecating all the methods and types from the LocalDockerCompose implementation.
compose v1 was deprecated back in July '23, and the Github workers are not installing `docker-compose` in the workers by default.
- Github notice: https://github.com/actions/runner-images/issues/9557
=> chore: use "docker compose" (v2) instead of "docker-compose" (v1)

modules/rabbitmq/rabbitmq.go, modules/rabbitmq/rabbitmq_test.go
Fixes AQMPS url
Fixes the AMQPS URL. Adds test.
User reported an issue - https://github.com/testcontainers/testcontainers-go/issues/2457
- Closes #2457
Will include unit-tests covering aqmps/tls
This currently won't work, while the AMQPS url is fixed it looks like container doesn't support TLS. I'll see if I can resolve that without too much difficulty.
=> bug:Fix AMQPS url

docs/features/common_functional_options.md, modules/neo4j/config.go
This PR updates the implementation of neo4j enterprise to use the newly added `testcontainers.WithEnv` instead of directly accessing the environment of `req`, which is erroneous.
Also, this PR fixes a minor typo in the docs.
The `Env` map of `req` may be nil. Also, dog fooding our own API is a good practice.
I've tested that this PR does not break `neo4j` tests. I trust the CI other than that.
=> Upgrade neo4j module to use features from v0.29.1 of testcontainers-go

docker_exec_test.go, exec/processor.go
Updates the `Multiplexed` option to combine the output of stdout and stderr, changing the previous behavior where stderr was preferred over stdout. Now, both streams are properly combined into a single stream.
Previously, the `Multiplexed` option prioritized stderr over stdout, potentially leading to unexpected results. By updating it to combine both stdout and stderr into a single stream, we ensure consistency and accuracy in handling the output of executed commands. This change prevents potential confusion or errors resulting from the previous preference for stderr over stdout.
- Relates #2451
=> fix(exec): updates the `Multiplexed` opt to combine stdout and stderr

docker.go, file.go, file_test.go
This changes code interacting with file copies to and from the container to use optimized functions. Doing so reduces buffering and gives a chance for to use [Go 1.22's optimized paths for linux](https://github.com/golang/go/issues/58808).
I'm using rather large images in k3s. For example, nodejs images get easily over a GB each. I found this copy logic accounts for the majority of test fixture setup, in our case sometimes over a minute is spent here even when images are available locally.
Originally added in #347
you can use k3s and its `LoadImages` function which will hit all the paths here.
=> feat: optimizes file copies to and from containers

docker.go, lifecycle.go, logconsumer_test.go
Fix logging deadlock, causing lots of test timeouts.
This refactors how logging shutdown is handled, eliminating unnecessary captures, use idiomatic wait group to signal processor completion and remove unnecessary `nil` initialisation.
Fix race condition in log testing which was reading `Msg` while the processor was still running.
Switch to checking `GITHUB_RUN_ID` environment variable to detect GitHub as `XDG_RUNTIME_DIR` can be present in other situations.
@mdelapenya edit:
> Capture all errors in the lifecycle hooks, refactoring the code in a single `apply` function that will be used in all the lifecycle hook methods.
Tests and runtime is currently flakey due to race condition during start and stop of logging.
Testing is hard as it's fixing a random race condition, but tests should now …
=> fix: logging deadlock

wait/http.go, wait/http_test.go, wait/testdata/main.go
When specifying a wait strategy using HTTP with query params, they are not sent to the container.
For example, to ensure the elasticmq container is ready, as advised in [this issue](https://github.com/softwaremill/elasticmq/issues/776), one must
poll the `/?Action=ListQueues` endpoint.
Currently this returns a 400 Bad request because the query parameters are not sent correctly to the endpoint.
The way the fix work is to parse the given path to create a `url.URL` instance and update the fields with the other values. This way the query parameters and the path are correclty handled.
Here is a reproduction with the elasticmq container:
```go
req := testcontainers.ContainerRequest{
Image:        "softwaremill/elasticmq-native:1.5.7",
ExposedPorts: []string{"9324/tcp"},
WaitingFor: …
```
=> Fix: HTTP wait strategy does not take query params into account

container.go, container_ignore_test.go, docs/features/build_from_dockerfile.md
- **chore: only include the dockerignore if it contains ignore files**
- **fix: the inclusions must be relative to the context**
- **docs: document the dockerignore feature**
This PR is fixing a cosmetic change in the logs of the library, which showed an error while building the Docker build context for the dockerignore file, as it was built with an absolute path instead of using the relative to the build context one.
At the same time, and discovered while running the tests, we were always adding the dockerignore file to the exclusions list, which is incorrect: we want to exclude it if and only if it exists.
Finally we are documenting the dockerignore file.
There was an ugly log error showing that the tar file was incorrect becuase of the dockerignore file having an absolute path. Now the …
=> fix: handle dockerignore exclusions properly

modules/elasticsearch/elasticsearch.go, modules/elasticsearch/elasticsearch_test.go
This makes optional the retrieval of the Elasticsearch generated CA for version 8 when CA generation has been explicitly disabled.
While Elastic supports security on by default and users should use the CA and authentication, the container shouldn't fail if one of the TLS config option has been explicitly disabled.
Tests come with the PR.
Fixing this would allow to finish the adaptation of the [go-elasticsearch client integration tests to testcontainers](https://github.com/elastic/go-elasticsearch/pull/824)!
=> Elasticsearch disable CA retrieval when ssl is disabled

docs/modules/postgres.md, modules/postgres/examples_test.go, modules/postgres/postgres.go
Bump the default postgres image to latest.
The default image version was `11` that version is unsupported  https://www.postgresql.org/support/versioning/
Run the unit tests.
=> feat: Bump default postgres version

docker_auth.go, docker_auth_test.go
Allows for auth config values like
```json
"auths": {
"artifactory.mycompany.com": {
"auth": "somebase64encodedcredential"
}
}
```
to be found when an image like `artifactory.mycompany.com/myImage:latest` is used.
Also prevents that an image without registry (e.g. `image:latest`) matches against that auth. Before, an empty registry matched because of how the URL used after parsing.
Using image without registry should not lead to using credentials that might not be valid for the default registry.
- Closes #2484
=> fix: fallback to URL-path when parsing auth config URL without scheme

docs/features/docker_compose.md, modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_api_test.go
This PR adds a stack option to pass a variadic list of io.Reader to the creation of the compose instance, so the user is able to pass a list of file paths (as strings),
or a list of readers containing the bytes to generate the compose files on the fly.
It will use a temporary directory in the O.S. to generate the compose files from the readers, removing them after the compose.Down is called. The tmp dir will be subdir from the current time in nanoseconds.
Support users that generate the compose files from other sources (e.g. downloading it from the internet).
- Closes #285
=> feat: support passing io.Reader for compose files when creating a compose instance

docs/features/docker_compose.md, modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_api_test.go
It adds two options: `WithRecreate` and `WithRecreateDependencies` that will allow to override the default behaviour of compose, which was set to `api.RecreateDiverged`.
Now it would be possible to set it to `api.RecreateDiverged`, `api.RecreateForce` or `api.RecreateNever`. If any other value is passed, then `Force` will be used.
Support more user customisation of the compose execution.
- Closes #1276
=> feat: support overriding the default recreate options for compose

docker.go, docker_test.go
This PR introduces the concept of non-retryable errors that might be returned by the APIClient. If such an error is encountered within a retry loop then the loop is broken since retrying will not change the result.
One exemption is `IsNotFound` during `waitContainerCreation` since the flow relies on that condition.
The docker API should not be called repeatedly since this might result in negative side effects (e.g. being blocked by a registry due to repeated failed authorization attempts).
- Closes #2502
Some unit tests around the retry behaviour where added.
=> fix: don't retry on permanent APIClient errors

docs/features/common_functional_options.md, docs/features/networking.md, options.go, options_test.go, port_forwarding.go, port_forwarding_test.go
This PR documents the new feature for exposing host ports to containers. It uses the Java docs as reference, adapting it to the implementation details of the Go version.
Document the new feature.
- Completes #2471
=> docs: document the SSHd tunnel

docker.go, exec/processor.go
Adds documentation for the `Exec` method in the `DockerContainer` struct.
The documentation emphasizes that reading directly from the `io.Reader` may result in unexpected bytes due to custom stream multiplexing headers. It recommends using `stdcopy.StdCopy()` from the Docker API to properly separate the stdout and stderr.
See: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/503
=> docs: add documentation for Exec method

port_forwarding.go
This PR is returning back the original value of the password, which was hardcoded for testing locally.
Use non-deterministic password for the sshd server.
- Caused by #2471
- Related to #2514
=> fix: use new UUID for sshd server password

modules/compose/compose_api.go
This PR uses the existing lock to protect the access to the containers map, which after #2485 caused the race condition.
Prevent race conditions
- Caused by #2485
I discovered this issue while running the compose tests with `-race`.
=> fix(compose): avoid race conditions when caching services

modules/influxdb/influxdb.go, modules/influxdb/influxdb_test.go
It updates the regex for InfluxDB v2, as we found the log output changed its format.
For that we have used a fixed version of the v2 image: `2.7.5-alpine`.
The CI started to fail for influxdb:latest
- Discovered while testing #2531
=> fix(influxdb): include more characters in wait for log regex

container.go, docker.go, docker_test.go, modules/localstack/localstack_test.go, wait/exec_test.go, wait/exit_test.go, wait/health_test.go, wait/host_port.go, wait/host_port_test.go, wait/http.go, wait/http_test.go, wait/nop.go, wait/wait.go, wait/wait_test.go
It exposes the existing inspect method to the Container interface. That will allow consumers to get the JSON representation of the container.
This new method will cache the raw JSON, which will be cleaned after stopping/terminating a container. Remember that when a container is stopped, the JSON representation could change.
At the same time, given the Inspect method retrives all the container info, we are deprecating two container methods: Name and Ports, as they are just passing-through ones. Consumers will just call inspect and from there get the container name and the ports. The deprecation paths have been properly set in the method comments, so the IDEs and the linters will complain/warn about them.
- c.Name(ctx): Use `c.Inspect(ctx).Name` instead
- c.Ports(ctx): Use …
=> feat: expose JSON representation of a container with Inspect

docs/modules/mongodb.md, modules/mongodb/mongodb.go, modules/mongodb/mongodb_test.go
Implementing a `WithReplicaSet` function to configure the container to run with a default single-node replica set named "rs". This function appends "--replSet rs" to `req.Cmd` to initialize MongoDB in preparation to receive a replica set. Additionally, after execution, it initializes the replica set using "rs.initiate()", configuring the current host as the PRIMARY.
I've been utilizing testcontainers to test my service environment, which necessitates a replica set to execute transactions. As I've developed this functionality for internal use, I believe it would be beneficial to others as well.
This PR closes #2138. Additionally, I noticed that there is another PR, #2139, which also aims to implement this feature. However, it has not been updated for a while, and this branch has certain …
=> feat(modules.mongodb): add replica set support via opts

modulegen/_template/module.go.tmpl, modulegen/main_test.go
This PR adds a missing import for "fmt" in the template that generates the module Go file.
The modules are generated, but the process fails because the code does not compile: missing import.
- Caused by #2267
There is no need to create a patch release, as users of the module generation tool will use it from the source code.
=> fix: add import to module generation

docs/system_requirements/ci/circle_ci.md
This PR adds a better configuration for CircleCI, fixing a typo and providing a way to install different versions of Go in the worker machine.
The page contained a typo referring Maven instead of Go, and the example was very simple. This config file has been tested in https://github.com/mdelapenya/testcontainers-go-compose
- Relates https://github.com/mdelapenya/testcontainers-go-compose/pulls/16
=> docs: fix CircleCI docs

docs/features/configuration.md, internal/config/config.go, internal/config/config_test.go
* Add the possibility to use environment variables to configure ryuk timeouts (reconnection and connection).
* Update unit tests
* Update documentation
* Fix up a minor typo in tests
Default timeout are not suitable in all situations :
* tests taking longer than 10s gets killed before completing (and may make also the following test fail from what I've observed)
* if image building / pulling takes more than 1m to complete, ryuk will timeout and make the test fail.
Configuring these timeouts is currently done via property file which must be located in user home.
This is not very convenient in CI context (need to create proper property file in runner home).
For some common configuration settings, such as TESTCONTAINERS_RYUK_{DISABLE,VERBOSE} it is possible to use env variable which is much …
=> feat(ryuk): allow to configure ryuk timeouts using env variables

docs/features/test_session_semantics.md, mkdocs.yml
This PR adds a section in the docs to explain how Testcontainers for Go builds the test session semantics.
Render URL: https://deploy-preview-2544--testcontainers-go.netlify.app/features/test_session_semantics/
More docs!
=> docs: document test session semantics

.gitignore, Makefile, docs/contributing_docs.md
This PR adds a few Make commands to interact with the docs in a more consistent way: using a Python's virtual environment.
It'll allow updating the docs in a more friendly and consistent manner.
- Discovered while working on #2544
=> chore: use a virtualenv for working with the docs site

docs/contributing_docs.md
It adds docs for the codesnippet plugin: https://github.com/rnorth/mkdocs-codeinclude-plugin
Render URL: https://deploy-preview-2546--testcontainers-go.netlify.app/contributing_docs/
Enhance the docs contribution experience.
=> docs: improve contributing docs for code snippets

docs/theme/partials/header.html
This PR updates the name of the mkdocs' search plugin, from `search` to `material/search`, in the header.html partial.
Render URL: https://deploy-preview-2547--testcontainers-go.netlify.app/
Search bar was not shown.
- Caused by #2524 because of https://github.com/squidfunk/mkdocs-material/commit/4b51fa21a8e1f585392b70a73c7f4001f872cb84 in https://github.com/squidfunk/mkdocs-material/pull/4628
=> fix: update search bar eval in mkdocs

docs/modules/vearch.md, modules/vearch/examples_test.go, modules/vearch/vearch.go, modules/vearch/vearch_test.go
It pins the version of the Vearch module, to avoid using latest.
For some reason I noticed it during the review but did not commented about it. Changing it is important for reproducibility and not receive a wrong version of the module each time it's used.
- Caused by #2560
=> chore: pin vearch version

port_forwarding.go
This PR does handle properly the error case while creating a ssh connection needed for port forwarding.
Without this, if the ssh connection could not be established for some reason, it would leave the wait on the channel lock forever and ignore context timeout. This would make test hang for a long time on my Mac.
- Closes #2540 
Running the port_forwarding tests on Mac should now error early with a proper error message.
Need to adjust the port_forwarding tests depending on the platform they are run on.
=> Handle error properly during port forwarding initialization.

docs/features/docker_compose.md
This fixes a typo in the docker compose docs for this repo
This helps readers to understand the documentation
=> docs(compose): Fix typo docker compose docs

docker.go, generic_test.go, internal/config/config_test.go, lifecycle.go, reaper.go
Updates [`lookUpReaperContainer`](https://github.com/testcontainers/testcontainers-go/blob/main/reaper.go#L66) to consider the [health](https://docs.docker.com/reference/dockerfile/#healthcheck) of the ryuk container.
* If the ryuk container advertises a health status, `lookUpReaperContainer` will require a healthy container before returning.
* If the ryuk container does not advertise a status, the `lookUpReaperContainer` will return the container.
The ryuk container can be exposed by the Docker API before it is ready to accept connections, resulting in messages like:
```
2024/04/21 22:25:10 🔥 Reaper obtained from Docker for this test session 99998b629eea57023f49aefc9eda5406c84ce4c91d0c6005c1b8c00dcbbce0d7
2024/04/21 22:25:10 failed to start container: dial tcp 127.0.0.1:32917: connect: …
```
=> Fix race condition when looking up reaper (ryuk) container

docs/system_requirements/using_colima.md
This PR updates the Colima setup docs, with the info provided by the community here: https://github.com/testcontainers/testcontainers-go/issues/815#issuecomment-2094646790
Keep docs updated.
Render URL: https://deploy-preview-2578--testcontainers-go.netlify.app/system_requirements/using_colima/
- Closes #815
=> docs: update colima docs

container.go, docker.go, image_substitutors_test.go
This PR considers the case where an image can be built from a Dockerfile and receives Image substitutors, applying them to build the complete image name after the build.
Built images did not receive the image substitutors
- Closes #2554
=> fix: prepend substitutors for built images

reaper_test.go
This PR skips two tests for creating the resource reaper, Ryuk, when Ryuk is disabled.
They are not of interested in that scenario.
It'll also improve the reliability in the CI pipeline, as we have seen some flakiness in these two skipped tests when Ryuk is disabled.
=> chore: skip reaper tests if ryuk is disabled

.github/workflows/ci-test-go.yml, Makefile, commons-test.mk, docs/contributing.md, examples/Makefile, modules/Makefile
Render URL: https://deploy-preview-2586--testcontainers-go.netlify.app/contributing/
This PR updates the contributing guide including how to update the codebase when the core go.mod is updated.
It also include info about passing golangci-lint in the codebase (core and submodules).
Finally it updates the makefile to use simpler names.
Everytime the core go.mod is updated, the changes must be propagated to all the downstream modules.
- Relates #2584
=> docs: update contributing guide

docker.go, logconsumer_test.go
This PR simplifies the sync mechanisms for starting and stopping the produciton of logs:
- the wait group controls the goroutine that reads the logs
- the start logs method initialises the logProductionStop channel, as a buffered channel of 1, so that the stop can close it properly
- the start logs method already used the logProductionStop channel to wait for a signal to stop processing logs
- the start logs method always adds 1 to the wait group, as it'll be the goroutine processing the logs
- the stop logs method will wait for all goroutines to finish
- the stop logs method will signal the logProductionStop channel so that the start method can stop
See https://go.dev/play/p/x0pOElF2Vjf, where we have created a simplified scenario for it.
As a consequence, the mutex is not needed …
=> fix: proper synchronisation for start/stop log production

network/network.go
Setting this value is a no-opt, as it's automatically set by the client, and the field will be removed in the next release of the docker module, so let's already remove it.
updates 6e086e8de13a97106bbb29a5a8aee7b0d28fe963, which deprecated this function.
- follow-up to https://github.com/testcontainers/testcontainers-go/pull/2584
=> network: WithCheckDuplicate: don't set CheckDuplicate value

mkdocs.yml
It uses the new version of emoji for mkdocs: `material.extensions.emoji.to_svg` and `material.extensions.emoji.twemoji`.
The previous one is deprecated and will be removed in the next version (obtained from the build logs of `make serve-docs`).
=> docs: fix deprecation warning for material extensions emoji

docs/modules/nats.md, modules/nats/examples_test.go
It adds a testable example for the creation of a NATS cluster, which includes:
- a docker network in which the containers will live. Then, containers can resolve by hostname/alias in the network
- three NATS containers properly configured for the cluster setup
- NATS client configured with the servers URL
- some example operations for interacting with the cluster (subscribe, unsubscribe, etc)
This PR finally updates the current docs, as the `WithArgument` option was missing:
- Render URL for the docs: https://deploy-preview-2591--testcontainers-go.netlify.app/modules/nats/#nats-cluster
Show by example how to set up a NATS cluster without adding anything to the current API, just configuring it properly.
- Closes #2393
=> docs: example for NATS cluster

modules/compose/compose_api.go, modules/compose/compose_api_test.go
Both `WithStackFiles` and `WithStackReaders` assign to the `Paths` field of the `composeStackOptions` which would result in the last option to overwrite all earlier options. 
The documentation specifies that it's possible to use both files and readers.
This PR aligns the implementation with the documentation by appending to the `Paths` field instead of overwriting it.
Align the implementation with what one would expect from the documentation
I've included a test that includes both a file and a reader
=> fix: allow compose files and readers to be used together

docs/features/configuration.md
It adds the `ryuk.disabled` property to the Ryuk settings docs.
Render URL: https://deploy-preview-2603--testcontainers-go.netlify.app/features/configuration/#customizing-ryuk-the-resource-reaper
The docs only showed that it's possible to do it with the env var, but the property is also a way to do it.
- Discovered while testing https://github.com/testcontainers/testcontainers-go/issues/2172#issuecomment-2185332511
=> docs: document disabling ryuk with properties

modules/weaviate/examples_test.go, modules/weaviate/weaviate.go, modules/weaviate/weaviate_test.go
This PR updates Weaviate's default version to latest `v1.25.5` it also adds a wait for http check just to be 100% sure that Weaviate is up and running.
Adds support for latest stable Weaviate v1.25 version.
none
=> Add support for Weaviate v1.25

docker.go
I'm getting an error when my container cleanly stops:
> container log error: EOF. Stopping log consumer: Headers out of sync
Please see individual commits. I tried to tidy up a bit, I hope this is fine.
The error is a red herring and distracts users of the library.
-
=> chore: improve log handling when container is stopping

.github/workflows/docker-moby-latest.yml
- **chore: continue on error for the nightly build**
- **chore: pass docker install type to the payload**
This PR enrichs the JSON payload we submit to Slack when the test-docker-latest build fails, passing if the docker was installed as rootful or rootless.
Have a quicker preview of the root cause of the error in the Slack message
- Continues #2611
=> chore(ci): pass docker install type to the nightly build payload

docker.go, options_test.go
I was debugging [failures in CI](https://github.com/testcontainers/testcontainers-go/actions/runs/9675487368/job/26693089053#step:10:2551) and found a few issues in code. See individual commits. I think the failure was not a real log reading failure - the container just failed to start for an **unexpected** reason but the test didn't catch it because it didn't check the error message.
Then, panic is a red herring too because the returned container is `nil`.
We want clear test signals that help pinpoint the bugs, we don't want hard to understand failures.
-
=> chore: test cleanups

.github/workflows/ci-windows-trigger.yml, .github/workflows/ci-windows.yml
- **chore: use ubuntu latest in the trigger command**
- **chore: narrow down self-hosted labels**
This PR updates the existing trigger-workflow to:
1. use ubuntu-latest as the worker to receive the command and dispatch the build to the self-hosted worker
2. use a more precise set of labels to match the right self-hosted Windows worker, using intel.
Start testing Docker Desktop on Windows
- Relates #2449
=> chore: use self-hosted worker for Windows tests

docs/features/configuration.md, docs/features/docker_compose.md
It documents the ryuk timeouts for the compose module.
Improve the docs to cause a better experience, removing a questions in Slack or as issues.
- Relates #2618
- Closes #2563
- Relates #2485
=> docs: document ryuk timeouts for compose

modules/postgres/postgres_test.go
Uses the new Run method in the Postgres module's tests.
Remove the deprecation warning in the lint
- Caused by #2610
=> fix: do not use deprecated method in postgres tests

docker.go, lifecycle.go, modules/clickhouse/clickhouse_test.go, reaper.go
Add logging of errors that are retried.
I want to see any unexpected errors when they happen. Otherwise nothing is logged and the test appears to be stuck forever.
-
=> Log retried errors

container.go, docker.go
Please see individual commits. The most important fixes are to not reuse the `Context` and to close it to release resources.
`BuildOptions()` calls `GetContext()` which calls `archive.TarWithOptions()` which [starts a goroutine](https://github.com/moby/moby/blob/v27.0.3/pkg/archive/archive.go#L850). This goroutine will be stuck until the reader is closed. So, current code leaks goroutines and open files when `BuildImage()` fails.
Improves reliability of image building.
-
=> Fix issues in BuildImage()

lifecycle.go
Still try to output the logs when the error which triggered is due to context timeout so that the user has a better chance to debug the issue.
=> fix: log output after context timeout

docker_auth.go
Improve the performance of retrieving docker authentication configuration by performing requests in parallel and only performing lookups once.
For a simple double layer image with standard Google Cloud Registry configuration this reduced the time spent doing authentication config lookups from ~4.6s to ~400ms.
=> perf: optimise docker authentication config lookup

docker.go
Add system errors to list of permanent errors which fixes infinite retries when a build is attempted with an invalid label.
=> fix: retry on label error

image_substitutors_test.go, options.go
The new substitutor can be used by modules whose images are not placed on `DockerHub` by default. This way, you don't need to manually prefix your image with a custom container registry. Instead, you can configure your registry with a prefix at the configuration level using hub.image.name.prefix.
In a development environment, `hub.image.name.prefix` is commonly empty, so `CustomHubSubstitutor` will add the desired default prefix. However, in a CI environment, the default prefix will not be added, and the config prefix will be used (handled by `prependHubRegistry`).
``` golang
func Run(ctx context.Context, img string, opts ...testcontainers.ContainerCustomizer) (*KeycloakContainer, error) {
req := testcontainers.ContainerRequest{
Image: img,
Env: map[string]string{ …
```
=> feat: add custom container registry substitutor

docs/features/creating_container.md, docs/quickstart.md
Fixes the compilation of the code snippet examples "Reusable Container" and "Spin Up Redis".
Users reading the documentation should be able to copy and paste the code snippets, and they should work without any modifications.
=> docs: fix compilation of examples

container.go, docker.go, docs/features/wait/host_port.md, docs/features/wait/http.md, wait/host_port.go, wait/http.go
Ensure `Container.Endpoint` returns the lowest numbered aka first port when there is more than one exposed.
Ensure that `wait.ForHTTP` uses the lowest numbered aka first port when there is more than one exposed.
Prior to this a random port would be returned leading to unpredictable 
results.
Fixed: #2640
=> fix: container.Endpoint and wait.FortHTTP to use lowest internal port

lifecycle.go, lifecycle_test.go
If an explicit port mapping is given in the definition of a container (through `exposedPorts`), the default readiness check fails. See the related issue below for an example. This PR fixes the issue by using the `nat.ParsePortSpecs` function instead of the `nat.Port` function when parsing the `exposedPorts`.
Anyone who upgrades to v0.32.0 and has a port defined as for example `4443:4443/tcp` will run into the below issue.
- Closes https://github.com/testcontainers/testcontainers-go/issues/2652
I still need to add a unit test for this, any advice on how to approach this?
=> fix: incorrect parsing of exposedPorts in readiness check

docker_client.go
It captures the Docker labels returned by the calls to `docker info`, and adds them to the initial banner:
Sample output:
```
2024/08/05 13:16:51 github.com/testcontainers/testcontainers-go - Connected to docker: 
Server Version: 26.1.4 (via Testcontainers Desktop 1.15.1)
API Version: 1.45
Operating System: Docker Desktop
Total Memory: 7841 MB
Labels:
com.docker.desktop.address=unix:///Users/mdelapenya/Library/Containers/com.docker.docker/Data/docker-cli.sock
Testcontainers for Go Version: v0.33.0
Resolved Docker Host: tcp://127.0.0.1:50211
Resolved Docker Socket Path: /var/run/docker.sock
Test SessionID: f15d9d974dddf9f2151699b9b87ae005de5b0d208c9911f666e1b821b106c735
Test ProcessID: 3a9b55d9-47e5-42f7-9940-db2843dfe504
```
If there are no labels, no entry will be added to the banner. …
=> chore: print Docker Info labels in banner

mounts_test.go
Fix test for image label setting which could fail if the volume already existed.
=> test: fix image label test

container_test.go, docker.go, from_dockerfile_test.go, generic.go, testdata/error.Dockerfile
Ensure build errors are returned to the caller when PrintBuildLog is not set to true.
DisplayJSONMessagesStream and JSONMessage.Display  performs processing of the stream to catch command failures, so needs to always be called.
=> fix: missing image build errors

port_forwarding.go
Fix port forwarding race condition by waiting for the exposed port which was causing random test failures.
Make errors and parameters more consumable while there.
=> fix: port forwarding race condition

port_forwarding_test.go
Fix racy creation of free ports in port forwarding tests which were causing random failures.
=> test: racy port creation in port forwarding tests

modules/mongodb/mongodb.go, modules/mongodb/mongodb_test.go
Fix mongodb replica test failures due to client using the internal container addresses when direct connection is not requested.
Fix invalid use of log.Fatal instead of tt.Fatal which was causing failures to not be output correctly due to os.Exit.
=> test(mongodb): fix replica test failures

modules/milvus/go.mod, modules/milvus/go.sum, modules/milvus/milvus.go, modules/milvus/milvus_test.go
Fix race in container setup caused by copying the files into the container manually.
While here update tests to use require so they are easier to follow.
=> fix(milvus): racy container setup

wait/health_test.go
Fix the data race on access to health in TestWaitForHealthSucceeds.
=> fix(wait): data race in test

modules/inbucket/go.mod, modules/inbucket/go.sum, modules/inbucket/inbucket.go, modules/inbucket/inbucket_test.go
Expose the POP3 port and wait for all ports which fixes the race condition in the tests.
=> feat(inbucket): expose POP3 and wait for all ports

modules/redpanda/examples_test.go, modules/redpanda/mounts/bootstrap.yaml.tpl, modules/redpanda/options.go, modules/redpanda/redpanda.go, modules/redpanda/redpanda_test.go
WithBootstrapConfig adds an arbitrary config kvp to the Redpanda container. Per the name, this config will be interpolated into the generated bootstrap config file, which is particularly useful for configs requiring a restart when otherwise applied to a running Redpanda instance.
Several Redpanda cluster config properties can be updated live but require a node restart to take effect. The simplest way to expose these to testcontainer consumers is to provide generic access prior to container startup.
An example usage case is an integration test for a particularly memory hungry Wasm Data Transform, where tuning the per core and per function memory limits in a flexible, implementation driven way may be the difference between testing or not testing that function.
-
=> feat(redpanda): Add option for arbitrary bootstrap config

docker_test.go, testdata/retry/Dockerfile
Add a test to cover the retry on system error test.
Update test to use empty context to prevent knock on failures being logged confusing the output and check the error returned.
=> test: add retry on system error test

docs/features/creating_networks.md, network/examples_test.go, network/network_test.go
It separates the tests from the testable examples for the network creation, updating the docs to the new examples.
The new testable examples contain clearer code snippets for creating networks with and without options.
Render URL: https://deploy-preview-2703--testcontainers-go.netlify.app/features/creating_networks/#__tabbed_1_1
Try to avoid confusing users reading our docs, as the default snippet used the internal option for creating networks, and this could cause issues when accessing the ports of containers in that internal network.
Considering deprecating the functional option to make a network internal (which great power...)
=> docs: add consistent snippets for network creation

modules/compose/compose_api_test.go, modules/compose/testdata/docker-compose-build.yml, modules/compose/testdata/docker-compose-complex.yml, modules/compose/testdata/docker-compose-container-name.yml, modules/compose/testdata/docker-compose-no-exposed-ports.yml, modules/compose/testdata/docker-compose-override.yml, modules/compose/testdata/docker-compose-postgres.yml, modules/compose/testdata/docker-compose-short-lifespan.yml, modules/compose/testdata/docker-compose-simple.yml, modules/compose/testdata/docker-compose-volume.yml
Remove the obsolete version field from all docker compose files to stop it warning.
=> chore: remove obsolete compose version

modules/registry/registry_test.go
Disable build log so its easier to see where failures occur.
=> chore(registry): disable build log

container.go, docker.go
Improve the documentation for container Terminate and IsRunning methods.
=> docs: improve docs for container methods

docker.go, lifecycle.go
Remove unused parameters from the defaultPreCreateHook function.
=> chore: remove unused params from defaultPreCreateHook

modules/compose/compose_api.go, modules/compose/compose_api_test.go, modules/compose/compose_local.go
Remove test volumes so that we don't leave orphaned resources after tests have run.
Remove really unused code as there is no need for it.
Add missing error checks on pipe setup.
=> fix(compose): remove test volumes

docker.go
Don't return context errors from log production as it's confusing to callers which cancel, making it harder to understand any actual errors that occurred.
=> fix: filter context errors from log production

docs/features/wait/host_port.md, wait/host_port.go
Add the ability to skip the internal host port check when performing as HostPortStrategy check. This is useful when a container does bind to the internal port until additional conditions are met.
=> feat(wait): skip internal host port check

modules/mockserver/mockserver.go
Silence the warning about being unable to check internal port by switching to SkipInternalCheck.
Ensure that container is returned on error.
=> chore(mockserver): silence warning about internal port

logconsumer_test.go, wait/log_test.go
Increase timeout values from microseconds to milliseconds as the former can lead to failures depending on hardware.
=> chore: increase timeout values

wait/log_test.go
Increase the log test timeout to avoid random test failures on slow machines.
Convert to require to make tests easier to read / understand.
=> chore(wait): log test timeout

modules/compose/compose_api.go
Fix container locking which was duplicated and held for the duration of the concurrent operation so preventing any concurrency.
=> fix(compose): container locking

docker_test.go
Fix tests which make http requests to nginx container by switching to http startup check, which avoids issues on nginx being able to respond to requests.
=> chore: fix nginx request failures in tests

commons-test.mk
It adds the verbose flag to `go test` in the makefile.
We want verbosity in the CI logs to debug test errors.
=> chore: run make tests in verbose mode

docker.go, generic.go, modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_local.go
Improve error wrapping to help detect failures in compose and wait tests.
=> chore: improve error wrapping in some docker container methods and compose module

container.go, container_test.go, docker.go, docker_auth.go, docker_auth_test.go, internal/core/images.go
Check and return errors in the process of determining authentication configs so that unexpected failures don't occur latter in the process of build an image or creating a container.
BuildOptions will now return an empty result on error instead of an incomplete one, to ensure that consumers don't use partial data.
Fix builds with different config or override environments failing when the authentication configuration changes, which was introduced by #2646.
Report errors from GetRegistryCredentials calls to avoid unexpected failures latter on in the authentication process.
Split out the functionality to read a Dockerfile from an io.Reader into ExtractImagesFromReader, as required when processing from a tar archive.
Deprecated function ContainerRequest.GetAuthConfigs will now panic if an …
=> fix!: docker authentication setup

lifecycle.go, logconsumer_test.go
Fix being able to stop and restart a container by moving the stop processing from PreTerminates to PostStops hooks.
Fix log consumer being duplicated when restarting.
Fix race condition in log consumer test, cleaning up to flow to validate correctly.
=> fix: logging restart

modules/redpanda/redpanda.go
Use SkipInternalCheck to wait for ports to be bound externally only  before trying to get the mapped port. This fixes a race condition in the setup of the container which was causing random test failures.
=> fix(redpanda): race condition on port check

internal/config/config.go, logger.go
Fix the ability to set the configuration of testcontainers using an environment variable set by a caller before the use of testcontainers.
This removes the warning about disabling the reaper which is actually safe when done correctly.
Also optimise verbose check while there.
Fixes: #2701 #2636 #2609
=> fix: config via environment

docker_auth_test.go, testdata/auth.Dockerfile, testhelpers_test.go
Fix docker auth tests to run on WSL by using the local IP instead of localhost, which can be unreliable.
While there refactor the tests to use a helper instead of hand coding each environment setup.
Remove duplicate logging about terminating container as default hooks already provide this.
=> fix: authentication tests on WSL

docker_test.go, testdata/echoserver.go, wait/testdata/main.go
Remove use of log fatal which prevents defers and correct order of Write and WriteHeader.
=> chore: avoid using of log.Fatal in main in tests

docker_test.go, options.go
Fixes Trailing Slash on Image Prefix.
Because we need to manually remove the Trailing Slash specifically for Go Projects. Where we want consistency between Testcontainers Java and Go
- Closes #2746 
Unit Test Created
=> Fix trailing slash on Image Prefix

modules/milvus/go.mod, modules/milvus/go.sum
Fix checksum mismatch by upgrading `milvus-io/milvus-sdk-go` from `v2.3.6` to `v2.4.0`.
Fix checksum mismatch caused by `milvus-io/milvus-sdk-go@v2.3.6`.
#2751
=> Upgrade milvus-io/milvus-sdk-go to avoid checksum mismatch.

docker_client.go, docs/features/configuration.md, image_test.go, internal/core/client.go, internal/core/docker_host.go, internal/core/docker_host_test.go, internal/core/docker_rootless.go, internal/core/docker_rootless_test.go, modules/localstack/localstack.go, provider.go, provider_test.go, reaper.go, reaper_test.go, testcontainers.go
This PR adds a check for each discovered Docker host in order to verify if a vanilla Docker client can talk to that host.
It will remove the confusion when a testcontainers.properties file exists and the Testcontainers Desktop (TCD) app has been used in the past, adding a `tc.host` entry in the properties. In the case TCD is not running, and the container runtime is running (i.e. Docker Desktop), then the latter should be used. Before this fix, the code will cause the discovery algorithm to get the tc.host entry first (it simply exists) and use it, even though it's not responding.
With this fix we'll fail if that Docker host is not accessible, continuing with the Docker host resolution.
- Closes #2622
=> fix: check if the discovered docker socket responds

modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_api_test.go, modules/compose/compose_builder_test.go, modules/compose/testdata/docker-compose-profiles.yml
This PR adds the option to use [Compose profiles](https://docs.docker.com/compose/profiles) to enable/disable services based on the profiles defined in the compose file:
```golang
func WithProfiles(profiles ...string) ComposeStackOption
```
The current behavior is not changed unless `WithProfiles` is used.
We would like to use our existing Compose files with `testcontainers-go/modules/compose` to set up test environments locally and in our pipelines.
However, our workflow relies on Compose profiles, which currently makes the use of `testcontainers-go/modules/compose` impossible, as only services without profiles are enabled by default.
Our workaround is to set up the test environment via the Compose CLI, but we think this could be well automated if `testcontainers-go` supported Compose …
=> feat(compose): select services via profiles

modules/postgres/options.go, modules/postgres/postgres.go, modules/postgres/postgres_test.go
Restores the original behavior of the Postgres snapshot functionality, that would use a default snapshot name, if no snapshot name was specified.
Without this change, #2600 is a breaking change, that requires user to make changes to their test code, manually specifying a snapshot name.
- Fixes regression from #2600
Multiple test cases for the default and custom snapshot name were added to `postgres_test.TestSnapshot()`.
=> fix(postgres): Apply default snapshot name if no name specified

modules/mongodb/mongodb.go, modules/mongodb/mongodb_test.go
This will add a test for writing to the mongodb module replica set so we can catch the error `(NotWritablePrimary) not primary`. It also adds a new wait strategy when using `mongodb.WithReplicaSet()` that waits for replica set status to be available.
We get flaky tests in our CI (seems to be present on slow hardware) and they fail sometimes since we try to write to a mongodb container which isn't ready.
There are tests added to test for this error. Tests will randomly fail when the wait strategy in `WithReplicaSet` is removed.
=> feat(mongodb): Wait for mongodb module with a replicaset to finish

container.go, container_test.go, internal/core/labels.go, internal/core/labels_test.go
=> fix: do not override ImageBuildOptions.Labels when building from a Dockerfile

wait/host_port.go, wait/host_port_test.go
- Handle 127 error code for podman compatibility.
- After merging this, we still need to disable ryuk for tests to work with Podman. Raised an issue for this: https://github.com/testcontainers/testcontainers-go/issues/2781
- Docker has a bug where it overrides exit code = 127 with exit code = 126. However, Podman handles these error codes separately.
- While testing etcd module, my container was returning exit code = 127 on Podman. test-containers.go didn't know what to do with 127 error code as it follows the moby project so, it was stuck in an infinite loop.
- Although, the container was up but the code was panicking.
- Some relevant PRs in other projects:
- https://github.com/containers/podman/issues/367
- https://github.com/moby/moby/issues/45795
- Output for `podman exec -ti …
=> fix: handle 127 error code for podman compatibility

modules/mssql/examples_test.go, modules/mssql/mssql.go, modules/mssql/mssql_test.go
~~Disable all mssql tests as the container is currently crashing, see #2785~~
This PR uses the MSSQL image that does not crash with the current update in the GH workers.
- Relates https://github.com/testcontainers/testcontainers-dotnet/pull/1265
- Relates https://github.com/actions/runner-images/issues/10646
- Relates https://github.com/actions/runner-images/issues/10649
- Closes #2785
=> fix(mssql): bump Docker image version

.github/workflows/ci-test-go.yml, commons-test.mk, container.go, internal/config/config_test.go, modules/consul/consul_test.go
Update golangci-lint to v1.61.0 and update the action to v6.1.0.
=> chore: golangci-lint 1.61.0

docker_test.go
Reduce the timeout for TestContainerCreationTimesOutWithHttp to reduce the likely hood of failure.
=> fix: container timeout test

docker_auth_test.go, modules/registry/registry.go
Switch registry containers to wait for http response to ensure the container is ready to serve requests, which was causing random test failures.
Also remove unnecessary context creation.
=> fix(registry): wait for

parallel.go, parallel_test.go
Simply the logic in parallel containers, eliminating a clean up race condition where multiple clean ups on the same container could occur at the same time.
=> fix: parallel containers clean race

wait/exec_test.go
It changes a localstack:latest image in a test with an alpine:latest one
Reduce the size of the pulled images, reducing the test time.
Also important to use a reduced set of images for testing.
=> chore: use a much smaller image for testing

docker.go, docker_test.go, lifecycle.go, logconsumer_test.go
Refactor container log handling simplifying the logic fixing various issues with error handling and race conditions between the complex combinations of multiple channels that have been causing random deadlocks in tests.
The new version has simple for loop with an inter call to ContainerLogs and stdcopy.StdCopy leveraging an adapter between io.Writer and LogConsumer.
This could be used to easily expose separate stdout and stderr handlers.
=> fix: container logging deadlocks

modules/grafana-lgtm/examples_test.go, modules/grafana-lgtm/go.mod, modules/grafana-lgtm/grafana_test.go
It updates the module path from `grafanalgtm` to `grafana-lgtm`.
During the release process of the modules, the git tag for each module uses the directory name as tag name, so it was wrong for grafana: its directory is `grafana-lgtm` and the module used `grafanalgtm`.
As a consequence, the pkg.go.dev site did not recognize the Grafana module.
- Closes #2745
=> fix(grafana): update module path

modules/elasticsearch/elasticsearch.go, modules/elasticsearch/options.go
Wait for the HTTP port to be available to prevent random failures when the container isn't fully started and returns 503 errors.
=> fix(elasticsearch): wait for

modules/redpanda/redpanda.go
Wait for the admin interface to response to HTTP to avoid failures in configuring the instance when its not fully ready.
=> fix(redpanda): wait for

container_test.go, docker_test.go, internal/core/docker_host_test.go, internal/core/docker_rootless_test.go, internal/core/images_test.go, lifecycle_test.go, modulegen/main_test.go, modulegen/mkdocs_test.go, modules/compose/compose_api_test.go, modules/localstack/v1/s3_test.go, modules/localstack/v2/s3_test.go
Using require for essential checks to ensure that tests do not proceed under invalid assumptions, while assert can be used for less critical checks to gather more information about potential issues.
**Suggested Usage of assert and require :-**
**Critical Checks (Use require):**
Use require to check critical conditions that must be true for the test to proceed.
If a require condition fails, the test stops immediately. This prevents any further code from running, which could lead to misleading error messages. 
**Non-Critical Checks (Use assert):**
Use assert to evaluate conditions that are important but not critical for the test's overall success.
If an assert condition fails, the test continues to run, allowing multiple assertions to be evaluated.
It is important to use require for …
=> feat: add require for critical checks

from_dockerfile_test.go, modules/etcd/etcd_test.go, modules/vault/vault_test.go, options_test.go
- replaces `assert` with `require` on critical checks
- reduces noise in test error logs
=> chore: replace 'assert' with 'require' for critical checks

container_ignore_test.go, internal/config/config_test.go, internal/core/docker_host_test.go, modulegen/main_test.go, modulegen/mkdocs_test.go, modules/artemis/artemis_test.go, modules/compose/compose_api_test.go, modules/redpanda/redpanda_test.go
ran through the codebase - these should be the last items for #2802
- use `require` wherever possible
- reduce noise in tests by failing early
- ~~Closes~~ Relates #2808
EDITED by @mdelapenya, as we do not want to close that issue yet. 🙏
=> chore: replace 'assert' with 'require'

modulegen/_template/examples_test.go.tmpl, modulegen/_template/module.go.tmpl, modulegen/_template/module.md.tmpl, modulegen/_template/module_test.go.tmpl, modulegen/internal/context/types.go, modulegen/main_test.go
Fixes the following in modulegen : 
- The generated name of the struct for the module is now `Container` leading to more idiomatic go (e.g postgres.Container)
- Missing imports in test generated files
- Removed `// run{{ $title }}Container {` from the example test as we can use the name of the Example{{$entrypoint}} instead
New generated modules will be more idiomatic and won't have to fix imports manually
No related issue but a request was made in this PR https://github.com/testcontainers/testcontainers-go/pull/2825#discussion_r1801841535 to name the container struct as `Container` from now on in preparation of v1
Generate a new module
=> fix: update module container struct name and missing imports

internal/config/config.go
Update the ryuk version so that shutdown processing is fast after a TERM signal.
=> chore: update ryuk to 0.10.2

container.go, docker.go, docker_mounts.go, generic.go, internal/core/labels.go, lifecycle.go, modules/compose/compose.go, modules/compose/compose_api.go, modules/compose/compose_api_test.go, reaper.go, reaper_test.go, testing.go
Refactor how the reaper is created to allow for proper retries of temporary errors such as container not found issues during startup or shutdown races.
This eliminates the use of sync.Once which wasn't solving the problem at hand and replaces it with a singleton spawner with locked access.
Wrap reaper errors so we can determine the cause of failures more easily.
Fix race condition in port wait when loading from container by always waiting for the port first.
Remove unnecessary use of buffering and invalid retry logic in reaper connection handling which could never recover correctly from a partial read.
Move the reaper creation just before connections are established in compose to ensure its still running when the Connect calls are made.
Previously the reaper was requested in …
=> fix(reaper): refactor to allow retries and fix races

.golangci.yml, docker_auth_test.go, docker_test.go, generic_test.go, internal/config/config_test.go, internal/core/docker_host_test.go, internal/core/docker_rootless_test.go, modulegen/context_test.go, modulegen/main_test.go, modulegen/mkdocs_test.go, modules/artemis/artemis_test.go, modules/clickhouse/clickhouse_test.go, modules/compose/compose_builder_test.go, modules/compose/compose_test.go, modules/couchbase/couchbase_test.go, modules/dolt/dolt_test.go, modules/kafka/consumer_test.go, modules/kafka/kafka_test.go, modules/mariadb/mariadb_test.go, modules/neo4j/neo4j_test.go, modules/ollama/ollama_test.go, modules/redis/redis_test.go, modules/valkey/valkey_test.go, port_forwarding_test.go, reaper_test.go, testing.go
Setup [thelper](https://golangci-lint.run/usage/linters/#thelper) linter and apply it’s recommandations .
Thelper detects tests helpers which is not start with t.Helper() method.
=> golangci-lint: enable thelper linter

container_test.go, docker_test.go, generic_test.go, modules/redpanda/redpanda_test.go, modules/registry/registry_test.go, options_test.go, wait/host_port_test.go
It uses  `require.Contains(t,...)` or `require.ErrorContains(t, err,...)` when possible
It also removes `require.Error(t, err,...)` as it is redundant with `require.ErrorContains(t, err,...)` behavior
To simplify code and not omit to check that error happened befort checking it's message content.
=> fix: use `Contains` or `ErrorContains` with testify

container_file_test.go, docker_files_test.go, docker_test.go, file_test.go, from_dockerfile_test.go, image_substitutors_test.go, image_test.go, lifecycle_test.go, logconsumer_test.go, modules/cassandra/cassandra_test.go, modules/dolt/dolt_test.go, modules/elasticsearch/elasticsearch_test.go, modules/k6/k6_test.go, modules/neo4j/neo4j_test.go, modules/rabbitmq/rabbitmq_test.go, modules/weaviate/weaviate_test.go, wait/exec_test.go, wait/exit_test.go, wait/host_port_test.go, wait/sql_test.go
This uses `require.(No)Error(t,err)` instead of `t.Fatal(err)` calls
This reduce the number of lines required to make an assertion.
It also make the assertion easier to understand.
=> chore: use require.(No)Error(t,err) instead of t.Fatal(err)

.golangci.yml, modules/elasticsearch/elasticsearch_test.go, modules/ollama/examples_test.go, modules/opensearch/opensearch_test.go
Setup [usestdlibvars](https://golangci-lint.run/usage/linters/#usestdlibvars) linter and apply it’s recommandations .
usestdlibvars detect the possibility to use variables/constants from the Go standard library.
=> chore: enable usestdlibvars linter

docs/features/configuration.md, internal/config/config.go, internal/config/config_test.go
- **chore: bump ryuk**
- **chore: use new ryuk variables, with a deprecation path**
It uses the latest ryuk (0.11.0), updating the environment variables that are already in use in tc-go to configure ryuk to use the new format (without the `TESTCONTAINERS_` prefix).
The old variables are deprecated but in the mean time the code will still read them as a part of a deprecation path.
Consume the latest Ryuk, which comes with more improvements regarding reliability.
=> chore: bump ryuk to 0.11.0

lifecycle_test.go, modulegen/main_test.go, modulegen/mkdocs_test.go, modules/compose/compose_api_test.go, modules/compose/compose_test.go, modules/localstack/v1/s3_test.go, modules/localstack/v2/s3_test.go, options_test.go
This uses `require.Len` instead of `assert.Len` calls when element is reused for tests.
When assert.Len is used, this is generally to check the length of a list that is generally used in at least one other test.
=> chore: use require.Len instead of assert.Len

container_test.go, docker_test.go, image_test.go, logconsumer_test.go, modules/influxdb/influxdb_test.go, modules/kafka/kafka_helpers_test.go, modules/kafka/kafka_test.go, modules/mariadb/mariadb_test.go, modules/neo4j/neo4j_test.go, modules/pulsar/pulsar_test.go, modules/rabbitmq/rabbitmq_test.go, modules/redis/redis_test.go, modules/valkey/valkey_test.go, modules/weaviate/weaviate_test.go, port_forwarding_test.go, provider_test.go, testing.go, wait/exec_test.go, wait/sql_test.go
This uses `require` instead of `t.Fatal` calls
This reduce the number of lines required to make an assertion.
It also make the assertion easier to understand.
=> chore: use require instead of t.Fatal

docs/modules/mysql.md, docs/modules/neo4j.md
It removes the block referring to the default image used in the MySQL and Neo4J modules
There is no default image by default, as it's delegated to the end user through the Run function.
=> docs(mysql|neo4j): remove default image codeblock

docker.go, modules/grafana-lgtm/examples_test.go, port_forwarding.go, reaper.go
Remove unused nonamedreturns directives as this linter was replaced by nakedret.
=> chore: remove unused lint directives

lifecycle_test.go, logconsumer_test.go, modules/chroma/chroma_test.go, modules/compose/compose_builder_test.go, modules/compose/compose_test.go, modules/couchbase/couchbase_test.go, modules/elasticsearch/elasticsearch_test.go, modules/influxdb/influxdb_test.go, modules/neo4j/neo4j_test.go, modules/rabbitmq/rabbitmq_test.go, modules/weaviate/weaviate_test.go
This uses `require` instead of `t.Fatal` calls
This reduce the number of lines required to make an assertion.
It also make the assertion easier to understand.
=> chore: use require instead of t.Fatal (part 2)

.github/workflows/docker-moby-latest.yml
Changes the Github actions workflow that ran the tests against a Docker Engine from the `test` channel of download.docker.com to get the nightly build off the `master` branch.
Currently it uses the `crazy-max/ghaction-setup-docker@master` action. We plan to move to to Docker org soon.
It also adds the containerd integration to the test matrix.
Rootless is not supported yet.
The `test` channel isn't updated that often as it requires us to run the whole release pipeline.
With this change, testcontainers tests will be ran against the master branch of moby and test the containerd image store integration.
-
=> feat(ci): Test against the nightly master moby

docker_auth.go, docker_auth_test.go
Fix docker authentication look up so it supports the case where the username is blank which means that the second returned value is an identity token not a password.
=> fix: docker auth for identity tokens

container_file_test.go, container_test.go, docker_test.go, image_substitutors_test.go, internal/config/config_test.go, internal/core/docker_host_test.go, modules/couchbase/couchbase_test.go, modules/postgres/postgres_test.go, provider_test.go, testcontainers_test.go, wait/all_test.go, wait/http_test.go
This uses `github.com/stretchr/testify` instead of `t.Error` calls
This reduce the number of lines required to make an assertion.
It also make the assertion easier to understand.
=> chore: use testify instead of t.Error

container.go, docker.go, docs/features/creating_container.md, lifecycle.go, lifecycle_test.go
Add pre and post build life cycle hooks so the user can see when an image build is occurring and what it's tag is.
Refactor combineContainerHooks to support additional fields automatically.
Reduce overhead of hook error handling by starting with an nil error slice and use append to allocate only if needed, in other words assume the happy path by default hence minimising allocations.
Minimise code used in hook handling by using helper methods.
Eliminate unused / shadowed parameters from defaultPreCreateHook.
GetRepo and GetTag now return a consistent UUID if the Repo or Tag field aren't set by setting their values. This was needed to enable the output of the image we're going to build in the log.
=> feat: add build to life cycle hooks

docker.go, exec/processor.go, port_forwarding.go, port_forwarding_test.go
Fix clean up of sshd container used for HostAccessPorts if the container setup fails.
Fix ensureDefaultNetwork instability by preferring the default network if available. This prevents random port forwarding test failures due to different network bindings between the containers.
Fix data race when reading exec command with Multiplexed enabled.
Fix deadlock if an error was encountered reading from a container exec command.
Refactor port forwarding tests so they can be run individually from code editors.
Add timeout to port forwarding requests so that we don't need to wait for a full test timeout to identify failures.
=> fix: host access port instability

docs/features/creating_container.md
It changes the message around the new lifecycle hooks for running containers from a Dockerfile.
Accurate docs for the win
- Caused by #2653
=> docs: fix new lifecycle hooks section

docs/modules/localstack.md, modules/localstack/go.mod, modules/localstack/go.sum, modules/localstack/v2/s3_test.go
This PR updates the deprecations in the S3 code examples for localstack, using the "github.com/aws/smithy-go/endpoints" Go package and the way the endpoint resolver is obtained from the s3 SDK.
Do not have deprecated code in the project.
- Discovered while testing #2849 (see https://github.com/testcontainers/testcontainers-go/pull/2849#discussion_r1819073008)
=> chore: resolve AWS deprecations for localstack

modules/redpanda/redpanda.go
The Redpanda container does not write files to the local filesystem anymore. It uses `io.Reader` now to copy files to the container.
On some environment it is not possible to write the startup files to the local filesystem and mount them into the container. For example in CI/CD environments where docker in docker is used. The files are written to the filesystem of container A. Then container A tries to start the redpanda container and passes the mount path to the newly created container. The redpanda container tries to mount the files from the host filesystem but cannot find them because they were written inside container A.
Just run the container tests. Everything should be working like before.
=> fix(redpanda): temporary file use

.github/workflows/docker-moby-latest.yml
Enables the rootless moby test workflow to use the nightly master binaries.
- Needs: https://github.com/crazy-max/ghaction-setup-docker/pull/124
- Follow up to: https://github.com/testcontainers/testcontainers-go/pull/2861
=> feat(ci): Enable master moby with rootless

.github/workflows/ci-test-go.yml
Skips the upload to sonar of the artifacts when Ryuk is disabled, to avoid name conflicts.
There is no need to measure metrics when Ryuk is disabled.
- Caused by #2888
=> fix: do not run sonar upload when ryuk is disabled

.github/workflows/ci-test-go.yml
It adds a step to build the artifact name as a shell step, in which it uses the basename of the project dir to build the name. 
For the core library, whose string representation is '.', we'll replace it with core.
Finally, the sonar step will read this new env var.
Fix the build for modules, as sonar does not allow slashes in the name.
- Caused by #2889
=> fix: build artifact name properly

.github/workflows/ci-test-go.yml
Excludes the upload of the sonar files to only those test jobs using ubuntu-latest.
Because `basename` does not exist on Windows, and we don't actually want to upload the coverage for windows atm, it's better to keep it simple for now.
- Follow-ups #2890, #2889 #2888
We must probably need a dedicated issue to target sonar integration. Let's do it after #2876 is merged
=> fix: only upload to sonar on ubuntu-latest

container.go, container_test.go
The container binds syntax is `host-src:container-dest[:options]` or `volume-name:container-dest[:options]` where `options` is a comma separated list of: `nocopy` `[ro|rw]`, `[z|Z]` or `[[r]shared|[r]slave|[r]private]`. See `HostConfig.Binds` of the Create a container request[1]
[1] https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Container/operation/ContainerCreate
It is not possible to set some of these options (e.g. SELinux labels) otherwise.
-
=> fix: container binds syntax

.github/workflows/conventions.yml, docs/contributing.md
This PR adds a GH workflow to enforce that PRs follow conventional commits in their titles, including that info in the contributing guides.
Enforce a consistent format that supports an easier-to-read changelog when the project is released.
- Closes #2910
=> chore(ci): enforce conventional commits syntax in PR titles

.github/workflows/ci-test-go.yml, .github/workflows/docker-moby-latest.yml
Use our official github action to setup rootless docker
-
=> chore(gha): use official docker/setup-docker-action

.github/release-drafter.yml, .github/workflows/conventions.yml, .github/workflows/release-drafter.yml, docs/contributing.md
- **chore: add security as valid convention PR title**
- **chore: add labels based on PR title**
It activates the autolabeler feature from the release-drafter Github Action, adding labels based on the PR title.
This is now possible thanks to the enforcement of conventional commits in the PR title.
It will simplify the burden of adding labels to PRs, making the creation of the release notes easier: as PRs will be automatically labelled, they will land into the right release notes section properly.
- Follows up #2911
=> chore(ci): add Github labels based on PR title

container.go, docker.go, docker_test.go
It adds the ability to configure the output of logs of docker image build from Dockerfile.
Now, there are two options for displaying logs of docker image build from Dockerfile: completely disable the output, however, it may contain useful information in case of problems, output to stderr, but the log may be large and clog up the output.
- Closes https://github.com/testcontainers/testcontainers-go/issues/2924
I have added a test for changes.
=> feat!: build log writer for container request

network/network_test.go, testing.go
The godoc of `CleanupNetwork` states that a `nil` network will result in a no-op.
Fix `ClenaupNetwork` behavior to match with its godoc.
Function behaves differently than documented in godoc.
Closes #2927
=> fix: handle nil value in CleanupNetwork

docs/features/wait/log.md, wait/log.go, wait/log_test.go
Add support for a sub match callback to wait.LogStrategy which allows containers to process the matched pattern storing details or otherwise validating them.
The callback can return a PermanentError if no more retries should be attempted.
=> feat(wait): log sub match callback

modules/localstack/localstack.go, modules/localstack/localstack_test.go
Improves the internal `isLegacyMode` function to handle all tag conventions used by localstack.
I'm currently unable to use the much smaller `localstack/localstack:s3-latest` image tag because it's incorrectly detected as a legacy version.
Unit test included.
=> fix(localstack): more reliable legacy tag detection

container.go, lifecycle.go, lifecycle_test.go, options.go, reaper_test.go
Rename `EnpointSettingsModifier` to `EndpointSettingsModifier`, as discussed in #2940.
=> chore!: rename EnpointSettingsModifier to EndpointSettingsModifier

.golangci.yml, container.go, docker.go, internal/core/docker_rootless.go, modules/compose/compose_api.go, modules/registry/registry.go, wait/exit.go
[revive](https://golangci-lint.run/usage/linters/#revive) is a linter for Go. Drop-in replacement of golint.
This PR list default rules and focus on applying  early-return, indent-error-flow and superfluous-else rules.
=> chore: enable early-return, indent-error-flow and superfluous-else from revive linter

.golangci.yml, container.go, internal/config/config.go, internal/core/images_test.go, modules/dynamodb/dynamodb_test.go
[revive](https://golangci-lint.run/usage/linters/#revive) is a linter for Go. Drop-in replacement of golint.
This PR list default rules and focus on applying var-declaration rule at first
=> chore: enable var-declaration from revive linter

commons-test.mk, modules/ollama/local_test.go
Update golangci-lint to v1.63.4 and fixes newly raised issues
=> chore(deps): bump golangci-lint to v1.63.4

.golangci.yml, lifecycle_test.go, logger.go, modulegen/internal/mkdocs/types.go, modules/chroma/examples_test.go, modules/compose/compose_builder_test.go, modules/compose/compose_local.go, modules/gcloud/spanner_test.go, modules/grafana-lgtm/grafana_test.go, modules/mockserver/examples_test.go, modules/neo4j/neo4j_test.go, modules/pulsar/pulsar_test.go, modules/rabbitmq/rabbitmq_test.go, modules/rabbitmq/types_test.go, modules/surrealdb/surrealdb_test.go
enable [use-any](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any) rule from revive
=> chore: enable use-any from revive

modules/valkey/valkey.go
Fix port race on start up of valkey containers by waiting for the port instead of the log entry.
=> fix(valkey): fix port race

.github/workflows/ci-test-go.yml
It uses the same filter for the sonar steps in the CI workflow.
If artifact name is not properly generated, then the sonarcloud files won't be uploaded correctly, as the artifact name will be empty, causing a collision.
- Caused by #2876
=> fix(ci): use same condition for sonar steps

docs/modules/index.md
In the modules docs, this PR removes two options that were duplicated in the customisers list.
Keep docs up-to-date. Also, they could cause confusion, as the removed options were telling the opposite to the real behavior of the code.
=> docs: remove duplicated options in the customisers lists

docs/modules/redpanda.md, modules/redpanda/admin_api.go, modules/redpanda/options.go, modules/redpanda/redpanda.go, modules/redpanda/redpanda_test.go
Adds an option to have a bootstrap user account when starting the container.
See https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/production-deployment/#bootstrap-a-user-account
Without this option and capability it is not possible to successfully start the Redpanda testcontainers module with Admin API authentication on (`admin_api_require_auth` config set to `true`).
=> feat(redpanda): add bootstrap user account option

.github/settings.yml, .github/workflows/ci.yml
It adds an end job after the tests, if and only if there are modules to be tested. Also updates the GH repo settings to use this end job as GitHub check as the only required check for merging PRs.
The end job needs the `detect-modules` and the `test` jobs in order to be run, so it will always run at the end of the pipeline. The job will check if previous jobs failed or were cancelled, failing the job in those cases. Else, it prints out a success message, finishing the job successfully, creating a passed GH check.
After the refactor of the pipeline to run the modified modules, the GH check was not updated (on purpose). This PR allows maintainers to see if a PR satisfies the required GH checks when reviewing and eventually merging a PR.
- Resolves #2968
=> chore(ci): add an end job to verify the pipeline finished with success

scripts/changed-modules.sh
It adds an exclusion list of files that won't add all the modules to the changed modules list.
A PR adding a new module, i.e. scyllaDB, will include changes in the mkdocs.yml file (for the website) and in the sonar.properties file (for sonar).
Before these changes, it would cause all modules to be added to the build, which is not desired.
Execute the script:
- A module is modified with a file that is excluded:
```shell
ALL_CHANGED_FILES="modules/kafka/a.go mkdocs.yml" ./scripts/changed-modules.sh
The output should be: the modules/kafka module.
```
-  A excluded file and a file from the core module are modified:
```shell
ALL_CHANGED_FILES="mkdocs.yml sonar-project.properties go.mod" ./scripts/changed-modules.sh
The output should be: all modules.
```
- Only excluded files are modified: …
=> fix(ci): exclude mkdocs.yml file and sonar.properties from the changed-modules script

docs/features/creating_container.md
Repair a code example.
Because working examples make people happy.
n/a
n/a
n/a
=> docs: correct container variable

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml
Passes the secret to the reusable workflow.
GH actions needs to explicitly pass the secrets to reusable workflows, else the value is empty, causing the sonar step to fail, breaking the build.
- Completes #3007
=> fix: pass secret to the reusable workflow

port_forwarding.go
Changes host port-forwards to be stopped after the main container is stopped.
This allows the main container's shutdown process to use the host forwarded port.
(E.g., to flush data to the host-port before shutdown).
Closes #3046
Used the repro that originally discovered the issue in #3046:
- start a fluentbit container with a HTTP output sent to the host forwarded port
- trigger shutdown, and ensure that fluentbit can flush data successfully
=> fix(portforward): stop port-forward from the beforeStop container hook to the afterStop

modules/dind/dind.go, modules/dind/dind_test.go
Loading images with docker image import does not preserve metatdata such as entrypoint, cmd, labels and tags. This makes the loaded image unusable as is.
This replaces the command with docker image load which fully preserves the metadata.
Using the previous implementation will have the new test fail because the entrypoint and cmd are not preserved.
=> fix(dind): use docker image load

modules/mssql/Makefile
It adds a Go env var to the shell the tests are run in order to mitigate the recent flakiness we are seeing when parsing the TLS certs in the MSSQL server container:
> TLS Handshake failed: tls: failed to parse certificate from server: x509: negative serial number
The PR is setting the env var in the Makefile for MSSQL.
Reduce flakiness
- Related to https://github.com/golang/go/issues/71606
- Related to https://github.com/influxdata/telegraf/issues/16309
=> fix(mssql): reduce flakiness in tests

docs/modules/aerospike.md, docs/modules/arangodb.md, docs/modules/azure.md, docs/modules/dind.md, docs/modules/etcd.md, docs/modules/pinecone.md, docs/modules/scylladb.md, docs/modules/socat.md, modulegen/_template/module.md.tmpl, modulegen/main_test.go
It updates the Run function code snippets in the recently added modules, as it was incosistent with the real types.
The docs template has been updated to avoid more errors like this one.
Inconsistent docs cause frustration.
=> docs: fix reference to container types in Run function

.github/workflows/codeql.yml
It adds the filter for the modified modules to the codeql workflow
The workflow is analysing all the repository with every PR, when it's not needed, adding around 6 mins to the build.
With this change we expect to reduce that build time.
=> chore(ci): run codeql on the modified modules

docs/modules/socat.md
It adds version markers for the new functions of the socat module.
It's important to mention in which release they were added.
- Should have been added in #3071
=> docs(socat): add missing version marker for new options

.github/workflows/ci-test-go.yml, .github/workflows/ci.yml
It runs the tests on Testcontainers Cloud, only when the core module is added to the build.
For that it extends the existing reusable workflow to accept one boolean argument, and if set to true, install the Testcontainers Cloud Client before running the tests.
Dogfood Testcontainers Cloud.
=> chore(ci): run core tests on Testcontainers Cloud

scripts/changed-modules.sh
It updates the excluded_files array to include those files that, if modified, do not cause the entire project to be rebuilt.
Reduce build time.
=> chore(ci): exclude more files for a full-blown build

.github/workflows/conventions.yml
It detects if the PR was sent from the fork's main branch, and close the PR with a descriptive message.
PRs that are sent from main cannot be contributed by maintainers.
=> chore(ci): close PR if it was sent from main

modules/localstack/localstack.go, modules/localstack/localstack_test.go
Adjusts `isMinimumVersion` to remove potential checksum from image name before extracting the version.
Else in case of image name with checksum the version is incorrectly extracted leading to incorrect errors about minimum version not being met etc.
For example, with following image name, the image name is extracted incorrectly:
```
docker.io/localstack/localstack:4.3.0@sha256:f3cb1a79f3add997575e859c3a2808e6dae4b0de836661de255baa2b576868f8
```
- closes #3128
=> fix(localstack): remove checksum from image name before parsing version

docs/modules/dockermodelrunner.md, modules/dockermodelrunner/dockermodelrunner_test.go, modules/dockermodelrunner/examples_test.go, modules/dockermodelrunner/go.mod, modules/dockermodelrunner/internal/sdk/client/pull.go
It adds a backoff-retry strategy after pulling a model in order to verify the model was actually pulled.
The retry uses the passed context to determine the exit.
When the HTTP connection is closed, the pull cancels, but the code continues its execution, resulting in a not pulled model.
- Caused by #3106
=> fix(dockermodelrunner): wait for the model to be pulled

modules/etcd/cmd_test.go, modules/etcd/etcd.go, modules/etcd/etcd_test.go
Added options listen-client-urls and advertise-client-urls for single etcd cluster execution.
Without this options server cannot handle incoming requests since be default it listens only 127.0.0.1 network interface.
- Closes #3150
=> fix(etcd): single node etcd cluster access

docs/features/common_functional_options.md, docs/modules/index.md, network/network.go, network/network_test.go, options.go, options_test.go
- **feat: add new option for AlwaysPull image**
- **feat: add new option for Lifecycle Hooks image**
- **feat: add new option for log consumer config**
- **feat: new option for attaching to networks by name**
- **feat: add two more options (no-start and name)**
- **feat: add one more option (image platform)**
More options to fully customise a container, from the modules side, or the Run function.
=> feat: add more functional options for customising containers

wait/host_port.go, wait/host_port_test.go
Fix a race condition when processing `HostPortStrategy.WaitUntilReady` which could result in it returning "no port to wait for" when no port is specified as is the case for `ForExposedPort`.
This could happen if the call happens very quickly after the container is started and the port is not yet available.
We now retry the internal port detection until found or the internal context is cancelled.
Fixes: #2945
=> fix(wait): no port to wait for

modules/etcd/etcd.go
It adds the client and peer ports to the exposed ports of the etcd container, so that they are available for discovery.
In #3159 we are adding the ability to auto-expose the image ports, and with that change we exposed this bug: if the ports are not automatically exposed, the etcd module is not able to connect to the client endpoints.
- Discovered while testing #3159
=> fix(etcd): expose ports for the etcd nodes

docs/features/common_functional_options.md, docs/modules/index.md, modules/k3s/k3s_test.go, modules/localstack/examples_test.go, modules/mongodb/examples_test.go, modules/mssql/mssql_test.go, modules/postgres/examples_test.go, modules/postgres/postgres_test.go, modules/postgres/wait_strategies.go, options.go, options_test.go
- **feat: add a new functional option to append wait strategies to modules**
- **chore: update modules**
It adds a new functional option to add additional wait strategies to the container.
It's needed to allow users to append new wait strategies instead of replacing them all. At the moment a user used a module, and customised it with `WithWaitStrategy` the module strategies were overriden.
With this change, users can choose if overriding or appending.
=> feat: support adding wait strategies as functional option

modules/inbucket/inbucket.go, modules/influxdb/influxdb.go, modules/kafka/kafka.go
This is a follow up for https://github.com/testcontainers/testcontainers-go/pull/3198 to fix a few more modules. Smaller PR this time, I haven't addressed all modules to reduce the size.
-
=> fix: use PortEndpoint() in a few more modules

docs/features/files_and_mounts.md, examples_test.go
- **docs: reorder to have more visibility in copy APIs**
- **docs: document CopyFromContainer**
It adds a section for copying files from a running container
It was missing in the docs
=> docs: document copy from container

docker.go
- chore: clarify image auth warning message for public images
This PR updates the log message shown when Docker image authentication credentials are not found during an image pull.
The new message clarifies that missing credentials is expected for public images and is not a critical error.
No functional or behavioral changes are introduced; only the log output is improved for clarity.
The previous log message used the word "Failed", which could be interpreted as a critical error by users, even though missing credentials is normal for public images.
This change helps avoid confusion and reduces unnecessary concern for users pulling public images, improving the developer experience and log readability.
- Relates #2752
=> chore: clarify image auth warning message for public images

docker.go, from_dockerfile_test.go, logconsumer_test.go
According to the log stream specification, the last 4 bytes of the header indicate the length of the log frame. There is an issue when a log message is exactly 10 character long, the header ends with `\00\00\00\10`. The current implementation uses `ReadLine` so it doesn't correctly read the header which results in the header being output. This is what the it looks like with the new test:
```
Error:      	Not equal: 
expected: "abcdefghi\nfoo"
actual  : "\x01\x00\x00\x00\x00\x00\x00\ni\nfoo"
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,3 @@
-abcdefghi
+      
+i
foo
Test:       	TestContainerLogsShouldBeWithoutStreamHeader
```
Relates to #454
=> fix: strip headers from logs using log stream specification 

modules/azure/go.mod
When trying to start service bus emulator via the services package I am getting:
`github.com/testcontainers/testcontainers-go/modules/azure/servicebus /Users/XXXX/go/pkg/mod/github.com/testcontainers/testcontainers-go/modules/azure@v0.37.0/servicebus/servicebus.go:137:65: mssqlContainer.Password undefined (type *mssql.MSSQLServerContainer has no field or method Password, but does have unexported field password)`
So the code cannot even be built.
My temporary fix was to change dependency of mssql to version 0.37 in the indirect dependencies of my go.mod.
Solution:
Instead of using mssql version 0.35 in the direct dependencies version 0.37 should be used.
Start the container with:
```go
// Create a Service Bus container
container, err := servicebus.Run(
ctx, …
```
=> chore(deps): update go.mod in azure module

modules/dockermcpgateway/dockermcpgateway_test.go, modules/dockermcpgateway/examples_test.go
In the tests, this PR replaces the Brave MCP server with the DuckDuckGo one
Brave server was killed with this error:
"Can't start brave: context deadline exceeded"
making the testable examples to fail, as the tools retrieved by the MCP client were not detected.
We probably need to ivestigate why the Brave MCP server is killed :thinking:
=> fix(dockermcpgateway): use duckduckgo instead of brave

modules/postgres/postgres.go
Label: Bug
It fixes #3263 by providing two changes
- Close any existing connection on the snapshot DB
- Drop the database only if it exists
We had very flaky tests without this change.
Seldomly, we still run into #3233 and would be happy about a fix as well.
- Closes #3263
- Relates #3233
As the error(s) only occur in some unknown circumstances it is very hard to enforce their occurrence and also a test situation where they fire.
=> fix(postgres): snapshot restore

modules/postgres/postgres_test.go
This uses `require.NotNil` instead of `assert.NotNil` when the db variable will be used in the remainder of the test.
If the db variable were nil the next line that calls defer db.Close would panic and the following call to db.Exec that we are setting up could panic too.
=> chore(postgres): use require.NotNil instead of assert.NotNil

internal/config/config.go
Updates the Ryuk version to the latest released image.
It uses scratch, a smaller and greener image
=> chore(deps): bump ryuk to v0.13.0, which uses scratch as base image

docs/modules/registry.md, modules/registry/examples_test.go, modules/registry/registry.go, modules/registry/registry_test.go
This PR adds a couple of helper functions to interact with the registry module:
* `PullImage`
* `TagImage`
When pulling images, it will use the same architecture as the image used to run the registry, as it could be using and arm-based image. Important to notice that, when inspecting an image, the field `ImageManifestDescriptor` response field is only available with containerd integration enabled. This happens on recent installations of Docker Desktop. If that field is `nil`, the pulled image will use `linux` as OS and the host's architecture.
Currently, the registry module does not support these two simple operations.
I've found them useful to have in the library, since most tests that rely on `modules/registry` will probably need to use them.
- Supersedes and Closes #3271
=> feat(registry): add helper functions to pull and tag images

docs/contributing.md, docs/modules/index.md
- Document a policy to **not bundle client SDKs** in production modules/images, in contributing.d
- Keep artifacts driver-agnostic, reduce maintenance/version churn, and let users pick their client.
- #2832
=> docs: clarify no client SDKs in production modules/images, in contributing.md

container_test.go, examples/nginx/nginx.go, options_test.go, options_unit_test.go
It uses the Run function in more places from the core library (no modules yet)
Consistenty and progress towards the new Run API
- Relates #3174
=> chore: use Run in more tests (part 4)

.golangci.yml
update relative-path-mode to "gitroot" in golangci configuration
Provide a clean path to files in output
-
=> chore: update relative-path-mode to "gitroot" in golangci configuration

modules/artemis/artemis.go, modules/artemis/artemis_test.go
- **chore(artemis): use Run function**
- **chore: use a constant**
- **chore: more robust wait strategy using listening port**
- **chore: set credentials properly**
Use Run function in the Artemis module
- Relates #3174
=> chore(artemis): use Run function

image_substitutors_test.go, options.go
This MR swaps `url.JoinPath` with `path.Join` in image substitutors.
`url.JoinPath` uses `url.Parse` internally, which doesn't correctly parse URLs like `example.com:443` without a schema. Docker image reference cannot have a schema [\[docs\]](https://docs.docker.com/reference/cli/docker/image/tag/). Incorrectly parsed URL inside `url.JoinPath` causes the image tag (second argument) to be completely ignored [\[go playground\]](https://go.dev/play/p/8HjldoU6qyG), which results in 404 errors when pulling an image.
- Closes  #3306.
- Relates https://github.com/testcontainers/testcontainers-go/issues/2746.
I've added a test case to `image_substitutors_test.go`:
```sh
go test -v -run TestPrependHubRegistrySubstitutor
```
=> fix: use path.Join instead of url.JoinPath when prepending a custom registry to an image

modules/databend/databend.go, modules/databend/databend_test.go
Use Run function in the Databend module
=> chore(databend): use Run function

modules/couchbase/couchbase.go
Use Run function in the Couchbase module
=> chore(couchbase): use Run function

modules/dolt/dolt.go
- **chore(dolt): use Run function**
- **chore: deprecate option**
Use Run function in the Dolt module, deprecating an option that should be internal.
=> chore(dolt): use Run function

modules/grafana-lgtm/grafana.go, modules/grafana-lgtm/grafana_test.go
- **chore(grafana): use Run function**
- **chore: add test for endpoints**
Use the Run function in the Grafana LGTM module
=> chore(grafana): use Run function

modules/k3s/k3s.go, modules/k6/k6.go, modules/kafka/kafka.go, modules/kafka/kafka_helpers_test.go, modules/localstack/localstack.go, modules/localstack/localstack_test.go, modules/localstack/types.go, modules/mariadb/mariadb.go, modules/mariadb/mariadb_test.go
Use the Run function in k6, localstack, kafka, and mariadb modules
- Relates to https://github.com/testcontainers/testcontainers-go/pull/3413
=> chore(k6|localstack|kafka|mariadb): use Run function

modules/meilisearch/meilisearch.go, modules/memcached/memcached.go, modules/milvus/milvus.go, modules/minio/minio.go, modules/mockserver/mockserver.go, modules/mssql/mssql.go
Use the Run function in meilisearch, memcached, milvus, minio, mockserver and mssql modules
Also fixes test flakiness in milvus by adding wait strategies for both HTTP and gRPC ports.
=> chore(meilisearch|memcached|milvus|minio|mockserver|mssql): use Run function

modules/mysql/mysql.go, modules/mysql/mysql_test.go
Use the Run function in mysql module
- Closes #3323
=> chore(mysql): use Run function

modules/nats/nats.go
Use the Run function in nats module
=> chore(nats): use Run function

modules/openfga/openfga.go
Use the Run function in openfga
=> chore(openfga): use Run function

modules/pinecone/pinecone.go
Use the Run function in pinecone
=> chore(pinecone): use Run function

modules/opensearch/opensearch.go, modules/opensearch/options.go
Use the Run function in opensearch
=> chore(opensearch)!: use Run function
