- docker_test.go
This test is added based on a comment I get from reddit about the
ability to reach two containers exposing the same port without any
collision.
> Tests to cover the ability to expose the same ports

- docker_test.go
> Fix copy paste error #9

- docker_test.go
- wait/http.go
> Wait Stategy For Http

- docker.go
- docker_test.go
When trying to access the docker container running the test remotely, it can be hard to get the IP address and port of the host.
This PR adds functionality where the host IP and port are exposed via the new `GetHostEndpoint` function
> feat(docker): add exposed host ip and port

- docker.go
Fixed #26
@MeneDev here we are, what do you think?
> Pull only if an image doesn't exist in the host

- docker.go
Addresses todo at [docker.go#L319](https://github.com/testcontainers/testcontainer-go/blob/15ebe77a7f97d7229efdce775f5d9cff309e86e8/docker.go#L319). 
We were using this lib for testing custom go services at Spotify and needed to implement this when running integration tests in a container, so I thought it would be helpful. Mirrors [this](https://github.com/testcontainers/testcontainers-java/blob/3ad8d80e2484864e554744a4800a81f6b7982168/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L15) Java implementation.
Would love to hear your comments and suggestions for a comprehensive testing strategy for this.
> Retrieve gateway address if inside container

- legacy_test.go
> Fixed panic in docker_test

- docker_test.go
- legacy_test.go
The test code didn't handle some of the returned errors from function calls.
> Handle returned errors

- docker_test.go
- wait/log.go
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> support timeout for NewLogStrategy

- wait/http.go
This fix #45 @MeneDev I cherry-picked your PR.
> Allow insecure TLS

- container.go
- docker.go
add option for start privileged container
> support privileged option

- docker.go
- docker_test.go
- go.mod
- go.sum
- reaper.go
> Fixed regression after SkipRepaer

- README.md
- container.go
- docker.go
- docker_test.go
> Using a slice of strings ([]string) for Docker Cmd.

- docker_test.go
- go.mod
- go.sum
- network_test.go
I would like to use more the Exercise feature provided by golang, in
order to get useful and verified use case for testcontainers that are
easy to pick up and well understood from who ever comes from the Go
community
https: //blog.golang.org/examples
> Added few examples around Container Create and Network

- wait/http.go
When using this for a variety of tests, generally it's better to retry on _any_ http failure raised rather than just a subset. If the container has issues bootstrapping, this makes the library handle those cases better where the listener may be "active" but still in an unexpected state
> Retry on any http failure

- container.go
- docker.go
- docker_test.go
- wait/host_port.go
- wait/log_test.go
- wait/wait.go
#46 host port waiting strategy inside container
> #46 host port waiting strategy inside container

- wait/host_port.go
Fixes #146 as well as potential stack overflow issue caused by calling defer inside a loop
> fix retry logic

- docker.go
> #136 log start-up progress

- reaper.go
Fixes #149 
Fix reaper connect failure by waiting for listening port
> Fix reaper connect failure by waiting for listening port

- docker.go
- docker_test.go
> Fix infinite loop caused by "image not found"

- docker.go
- go.mod
- go.sum
> fix(uuid): wrong replacement for uuid

- wait/sql.go
> Use default timeout in SQL waiter

- docs/index.md
It fixes a typo and an URL in the docs
> Fix typo and URL in docs

- docs/features/garbage_collector.md
- docs/quickstart/gotest.md
- testing.go
Thanks for the package!
This is just a few random spelling and grammar corrections I made while reading through the docs, for my first setup.
> Grammar and spelling fixes

- docs/index.md
Fixes an incorrect URL and some punctuation marks.
> Fix docs index

- container.go
- docker.go
- docker_test.go
> Allow hostname to be configured

- docker.go
The `getGatewayIp` originally refers to testcontainers-java [here](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L46) which is deprecated. The new flow is described [here](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L257): Network inspect for gateway IP -> get default gateway IP -> "localhost".
This PR implemented the new approach and marked the `getDefaultGatewayIP` as deprecated to be consistent with testcontainers-java.
> Use NetworkInspect to get the gateway's IP and fallback to getDefaultGatewayIP when fails

- container.go
- wait/log.go
Hi there!
Split typos from #253
> fix: fixed typos

- wait/log.go
Hi there!
I hope you don't mind if fix #240
> Fix: comment log strategy

- docs/modules.md
- mkdocs.yml
Fixed #101 
Fixed #108 
Fixed #102 
Fixed #98 
Fixed #117
> Document our approach to modules

- docker.go
- logconsumer_test.go
I've noticed an issue in logs producers where the daemon will close the connection due to container logging inactivity.  These changes add an updated retry instead of silently ignoring the error and update the test that demonstrates the problem.
> Retry follow logs request on closed connection

- docs/modules.md
Hey @gianarb! Hope you find this PR well, just wanted to share the canned kafka I had around here.
Tks
> Add canned kafka to module doc

- reaper.go
Updated default reaper image to a newer version.
Old one didn't have arm version, this one does.
> Updated default ryuk image to testcontainers/ryuk:0.3.3.

- docs/features/garbage_collector.md
> docs: fix ryuk link

- container.go
- docker.go
- docker_test.go
Hi, option to stop containers is not exposed through interface although it exists in docker provider.
> add ability to stop container

- README.md
- docker.go
- docs/index.md
- docs: prepare for neutral branch name
- chore: update link to main
It prepares for neutral branch name
- Relates #410
> chore: preparation to rename to main

- docker_test.go
I think it will be better, if we add this check to tests
Close https://github.com/testcontainers/testcontainers-go/issues/304
> add missing test for checking status code matcher

- reaper.go
Use latest ryuk's version. See [release notes](https://github.com/testcontainers/moby-ryuk/releases/tag/0.3.4)
> Update testcontainers/ryuk version to 0.3.4

- docs/examples/nginx.md
- docs/examples/pulsar.md
- docs/examples/redis.md
It fixes the syntax in the example docs
The code in the examples don't compile, this PR is fixing it.
- Causes by #569
- Relates to #603
> docs: fix syntax

- .github/dependabot.yml
It uses go-yaml format for indents, as it seems the library has different issues regarding not honoring the indents.
Preparing for #654 
- Block #654
- Relates https://github.com/go-yaml/yaml/issues/899
> chore: format dependabot using go-yaml indents

- mkdocs.yml
It uses the indent format of go-yaml v3 in the mkdocs.yml file
Keep consistency with the yaml library, as we are generating code that will modify this file
- Continues #564
> chore: update mkdocs format to go-yaml v3

- docker.go
It wraps the Docker client call to ImageBuild into a backoff retry
It could be the case the ImageBuild needs to pull images, and for some reason the network has a glitch. In those cases, we need to retry to avoid failures.
- Discovered while testing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17556
At some point we should make the backoff wait strategy configurable, e.g. using the .testcontainers.properties file or an env var.
> chore: build images with backoff retries

- internal/version.go
- mkdocs.yml
Bumps the version to the next minor
> chore: prepare for next minor development cycle (0.19.0)

- docs/index.md
It includes the haskell logo to the website
Let's include our new friend :)
> docs: include haskell logo to the website

- docs/index.md
As suggested by @mdelapenya in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18739
> docs: add usage reference in OpenTelemetry Collector

- docs/index.md
Update the link for testcontainers-node from the GH README to the official mkdocs.
Consistency + Better documentation experience.
-
> Update docs link for tc-node

- .github/dependabot.yml
- modulegen/dependabot.go
- modulegen/dependabot_test.go
It updates dependabot's config file and the code generator that updates dependabot.
With the raise of modules, we receive multiple PRs from dependabot, so better to handle them month by month
> chore: monthly updates for dependabot

- .github/release-drafter.yml
Automated sync for OSS governance files
> chore: sync governance files

- examples/bigtable/go.mod
- examples/bigtable/go.sum
- examples/cockroachdb/go.mod
- examples/cockroachdb/go.sum
- examples/consul/go.mod
- examples/consul/go.sum
- examples/datastore/go.mod
- examples/datastore/go.sum
- examples/firestore/go.mod
- examples/firestore/go.sum
- examples/mongodb/go.mod
- examples/mongodb/go.sum
- examples/mysql/go.mod
- examples/mysql/go.sum
- examples/nginx/go.mod
- examples/nginx/go.sum
- examples/postgres/go.mod
- examples/postgres/go.sum
- examples/pubsub/go.mod
- examples/pubsub/go.sum
- examples/redis/go.mod
- examples/redis/go.sum
- examples/spanner/go.mod
- examples/spanner/go.sum
- examples/toxiproxy/go.mod
- examples/toxiproxy/go.sum
- modules/pulsar/go.mod
- modules/pulsar/go.sum
It runs `go mod tidy` after the recent updates on dependabot
Keep dependencies up-to-date
> chore: sync dependencies in Go modules

- reaper.go
It bumps Ryuk to its latest release: 0.4.0
Consume latest improvements in Ryuk (see https://github.com/testcontainers/moby-ryuk/releases/tag/0.4.0)
> chore: bump Ryuk to latest release

- docs/modules/couchbase.md
- modules/couchbase/bucket.go
- modules/couchbase/couchbase.go
- modules/couchbase/couchbase_test.go
- modules/couchbase/options.go
- modules/couchbase/storage_mode.go
It adds a module reference section in the docs, describing each exposed function in the public API, including code snippets extracted from the code.
At the same time, we are adding Go docs for the public API.
Finally, we are moving the test methods to a test package, so that we demonstrate the real usage of the module from inside.
Render URL: https://deploy-preview-971--testcontainers-go.netlify.app/modules/couchbase
Make the module more usable through docs
- Completes #876
> docs: extend Couchbase docs

- docs/modules/neo4j.md
It uses the right technology name in the docs for Neo4j module
I missed the typo while reviewing it
- Completes #937
> docs: fix technology name

- modulegen/_template/docs_example.md.tmpl
- modulegen/main_test.go
It adds a dedicated section in the docs for a new module (or example module) to demonstrate how to install the module.
Enrich the generated code for a new module.
- Discovered while testing #990
> chore: include how to install the module in the generated docs

- scripts/release.sh
It escapes slashes in the URL while releasing modules
Undesired stash/unstash while commiting #1081
- Completes #1081
> fix: escape slashes

- docker.go
This reverts commit 5185956fa1de650bf1021fd34dbacabc029c6255.
We identified that the changes in the logic changed the behaviour of the StartProducer method causing the StartStop test for the log consumers to fail in a non-consistent manner (flakiness).
After debugging the issue for a while, and instead of commenting/skipping the test, I decided to revert the original commit from #947 until we get to a deterministic behaviour.
Please see:
- https://github.com/testcontainers/testcontainers-go/pull/947#issuecomment-1531133129
- https://github.com/testcontainers/testcontainers-go/pull/947#issuecomment-1541588628
- Caused by #947
- Reopens #946
- Reopens #606
> Revert "fix: don't panic when logs waits for more than 5 seconds (#947)"

- modulegen/README.md
It uses the right domain and path for the link to the modules
It could confuse the onboarding from our README files.
> fix: update link to modules docs

- .github/settings.yml
Updates the GH check that is needed to mark a PR as green
Consistency
- Completes #1414
> chore: fix branch protection settings

- .github/settings.yml
Use proper check name
Old name left PRs in unmergeable state
- Completes #1418
> fix: proper check name in branch protection settings

- .github/dependabot.yml
Generates the `dependabot.yml` configuration file
As the number of modules or package system growth it keeps the generation easy
> ci(deps): add github-actions and pip package-ecosystems

- .github/workflows/ci-windows.yml
Downgrades the GH action to 0.9.0
There is a regression in the recently bumped version of the action. Rolling back to 0.9.0
-
> chore: downgrade GH action github-script

- .github/workflows/ci-windows.yml
> fix: proper semver name

- .devcontainer/devcontainer.json
Updates go version to 1.19 for devcontainer
> fix devcontainer go version to 1.19

- .github/workflows/release-drafter.yml
It copies tc-node's GH workflow for the release drafter,
in order to have a consistent process for drafting releases.
> chore: add a GH action for release drafter

- .github/workflows/ci.yml
Adds windows-latest to the build matrix for the module generator.
Check if the generator fails on Windows
- Closes #1477
> chore: run modulegen tests on Windows

- .github/dependabot.yml
- modulegen/dependabot.go
Support groups in dependabot updates
> Support groups in dependabot updates

- modulegen/internal/tools/exec.go
- modulegen/main.go
Refactor exec (go vet and go mod tidy) code in modulegen
> modulegen: create internal/module

- modulegen/_template/module.md.tmpl
It removes a block that is not needed anymore. Probably here after a wrong rebase
That block is already appended by a markdown include.
- Completes #1648
> docs: remove shared docs in template

- modules/redpanda/redpanda.go
Add additional parameters to Redpanda start command.
To improve Redpanda resource usage.
-
> Improve redpanda resource usage

- lifecycle.go
This is a very tiny fix for the lifecycle logs so that they correctly print the error.
The actual error content is more useful than `%!w(...)` 😄 
none
> fix: use correct formatting directive for errors in lifecycle logs

- docs/features/image_name_substitution.md
It updates the file in which the code snippet for image substitutors live.
Do not break the docs site.
- Caused by #1894
> docs: fix code snippet for image substitution

- internal/config/config.go
It bumps Ryuk to the latest 0.6.0 release.
Use latest Ryuk, which resolves some CVEs
> chore: bump Ryuk to 0.6.0

- .github/workflows/ci-windows-trigger.yml
- .github/workflows/ci-windows.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/release-drafter.yml
- modulegen/_template/ci.yml.tmpl
Pin github-actions dependencies and define permissions on workflows and jobs when necessary
This help improve OSSF score
> improve OSSF score

- modules/redpanda/redpanda_test.go
This change adds the admin client ListTopic requested in https://github.com/testcontainers/testcontainers-go/pull/2140/files#r1478741534.
Meaningful test assertions ✔️ 
- #2140
> redpanda/test: add admin client call

- docs/modules/index.md
This PR improves the docs on how to create a module, adding the initial considerations regarding where to host a module before actually creating it.
There is a big difference hosting a module in our repo compared to letting users to host them themselves. This PR sets the expectations for all the use cases: official modules, community modules and regular/core modules.
Render URL: https://deploy-preview-2239--testcontainers-go.netlify.app/modules/
> docs: improve module creation section

- docs/modules/mongodb.md
- modules/mongodb/examples_test.go
- modules/mongodb/mongodb_test.go
It moves the existing examples to an examples_test.go file, creating a new one for testing that the given images are valid.
Confirm the new MongoDB images are valid for the module.
> chore: confirm support for new mongo images

- internal/config/config.go
It bumps Ryuk to the latest v0.7.0 release.
This version comes with support for Windows containers, so we could start working on the Windows support for testcontainers-go.
> chore: bump ryuk to latest v0.7.0

- .github/FUNDING.yml
Adds the Github sponsors button to the project.
Align with the java project and display the icon in case people wants to contribute
-
> chore: add funding button for testcontainers

- docs/features/follow_logs.md
Add missing package in the example.
More easy to copy/paste, use and understand.
> [doc] Fix follow_logs.md by adding missing package

- .github/workflows/ci-test-go.yml
Bumps test-summary action to resolve NodeJS deprecation.
Remove deprecation errors from the GH workflows.
- Relates https://github.com/test-summary/action/pull/42
> chore(deps): bump test-summary action to v2.3

- .github/workflows/ci-test-go.yml
- commons-test.mk
- docker_test.go
update golangci-lint to v1.59.1
Older versions may not be fully compatible with newer versions of Go 😃 
-
> gha: update golangci-lint to v1.59.1

- container_test.go
- docker.go
- lifecycle.go
- options_test.go
- wait/wait.go
Improve the lifecycle errors with wrapping so that its easier to determine the cause of an error.
> chore: improve lifecycle errors

- modules/mysql/examples_test.go
Add a missing error check in the mysql example for connection setup.
> chore(mysql): add missing error check in example

- internal/config/config.go
It bumps Ryuk from 0.8.1 to 0.9.0
Use latest version of the companion resource reaper. See updates here: https://github.com/testcontainers/moby-ryuk/releases/tag/0.9.0
> chore: use new testcontainers/ryuk:0.9.0 image

- modulegen/_template/ci.yml.tmpl
Updates the template
Users of modulegen will receive the same checkout version
- Accidentally caused by #2762
> fix: update checkout action in template

- README.md
It aligns all badges in one line, keeping codespaces and slack ones in a second line.
Avoid having the content too down in the page.
> docs: refine heading badges in README

- modules/compose/compose_api.go
Fix a race condition in compose module when setting up multiple containers.
> fix(compose): race condition

- .github/dependabot.yml
- modulegen/_template/ci.yml.tmpl
- **chore: update template**
- **chore: include modulegen templates in dependabot**
> deps(fix): include modulegen templates dir in dependabot updates

- .golangci.yml
- logconsumer_test.go
enable [empty-block](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block) rule from revive
> chore: enable empty-block from revive

- docs/modules/grafana-lgtm.md
Fixes a small typo in the grafana-lgtm module docs.
To not drive others insane like it drove me insane for about 10 minutes.
> docs: fix typo of grafanalgtm -> grafana-lgtm module package

- .github/workflows/ci-test-go.yml
Use the empty path for the core library
> fix: use empty dir for the core

- .github/workflows/ci-test-go.yml
Uses the current dir for the core project
> fix(ci): update core path in sonar build

- .github/workflows/ci-test-go.yml
- scripts/bump-go.sh
It skips running the sonar stages on runners that are not ubuntu-latest, and using a Go version that is not the lowest in the matrix.
Update sonar just once.
-
> fix(sonar): run on ubuntu and the lowest Go version

- .github/workflows/ci-test-go.yml
Passes the `sonar.branch.name` to the Sonar analisis, set to main.
Avoid setting it manually in the GUI
> chore(sonar): set main as default branch

- .github/workflows/sonar-bulk-operations.yml
- .github/workflows/sonar-delete-project.yml
Fux the script name in the call
Wrong copy paste after a refactor
- Caused by #3039
> fix(ci): update sonar script path in the GH actions

- .gitignore
- Makefile
- docs/contributing.md
It replaces python virtualenv with a docker container.
Simpler, inspired by @cristianrgreco's work in the tc-node project.
> chore: dockerise docs build

- modules/dind/dind.go
Small typo in the Run comment for the dind module.
> chore(dind): instance of Docker in Docker

- modules/influxdb/influxdb.go
Chore
Fixes a typo referencing mysql instead of InfluxDB in `influxdb` module/package.
To keep things accurate
None
> chore: fixed comment typo in InfluxDB

- .github/workflows/docker-projects-latest.yml
- .github/workflows/sonar-bulk-operations.yml
- .github/workflows/sonar-create-project.yml
- .github/workflows/sonar-delete-project.yml
Uses pinned dependencies on Github actions
Security matters
> deps: use pinned dependencies on GH actions

- .github/workflows/ci.yml
It avoid aborting the build on the matrix for Testcontainers Cloud.
If it fails in one but passes in the other, it's just flakiness
> chore(ci): do not fail fast in the Testcontainers Cloud run

- .github/workflows/ci-test-go.yml
It excludes Testcontainers Cloud from the sonar analysis.
We don't want duplicated sonar runs, just one.
> fix(ci): do not run sonar for Testcontainers Cloud

- internal/config/config.go
It uses the latest Ryuk release, `0.12.0`
Keep dependencies updated
-
> chore: bump ryuk to 0.12.0

- port_forwarding.go
It bumps the sshd image to the latest release.
It addresses some security concerns
> deps: update testcontainers/sshd image to 1.3.0

- modules/arangodb/arangodb.go
- modules/arangodb/options.go
Use Run function in the ArangoDB module
- Relates #3174
> chore(arangodb): use Run function

- modules/consul/consul.go
Use Run function in the Consul module
> chore(consul): use Run function

- modules/dockermcpgateway/dockermcpgateway.go
- modules/dockermodelrunner/dockermodelrunner.go
Update error messages in Docker modules
Consistency
> chore(docker): fix error messages

- docs/modules/mssql.md
It documents the MSSQL issue with self-signed certificates.
Improve the docs
> docs(mssql): describe MSSQL issue with negative certificates
